### PR TITLE
fix TestRebalancePipeline test

### LINKED ISSUE #1156: Fix invalid session id in TestRebalancePipeline (testDuplicateMsg)
In the test `testDuplicateMsg` from TestRebalancePipeline, currently an invalid session id is used. Here's the detail:
setCurrentState(clusterName, "localhost_0", resourceName, resourceName + "_0", "session_1", "SLAVE");
"session_1" is not the correct session id and we should use `liveInstances.get(0).getEphemeralOwner()` instead. The wrong session id makes the following test and assertion meaningless.

### PR DESCRIPTION
**Pull request by zhangmeng916**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1156 

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:
In the test testDuplicateMsg from TestRebalancePipeline, currently an invalid session id is used. Here's the detail:
setCurrentState(clusterName, "localhost_0", resourceName, resourceName + "_0", "session_1", "SLAVE"); 
The wrong session id makes the following test and assertion meaningless. This PR uses the correct session id  liveInstances.get(0).getEphemeralOwner() instead. Meanwhile, we found a NPE thrown out during the pipeline and cause the pipeline to stop, which is due to the missing of `setAsyncTasksThreadPool` action. This PR also fixed the issue.

### Tests
helix-core
- [X] The following is the result of the "mvn test" command on the appropriate module:
[ERROR] Failures:
[ERROR]   TestClusterInMaintenanceModeWhenReachingMaxPartition.testDisableCluster:119 expected:<true> but was:<false>
[ERROR]   TestRebalanceRunningTask.testFixedTargetTaskAndEnabledRebalanceAndNodeAdded:330 expected:<true> but was:<false>
[INFO]
[ERROR] Tests run: 1153, Failures: 2, Errors: 0, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:14 h
[INFO] Finished at: 2020-07-19T22:08:21-07:00

helix-rest:
[INFO] Tests run: 163, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 30.642 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 163, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  35.801 s
[INFO] Finished at: 2020-07-19T23:40:27-07:00
### Commits

- [X] My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- [X] My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Comment by narendly** [comment]
Could you do "fixes #N" in Issues section? That way, the issue gets closed when PR gets merged into master automatically :)

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java [hunk 1]
```diff
@@ -61,8 +62,9 @@ public void testDuplicateMsg() {
     HelixManager manager = new DummyClusterManager(clusterName, accessor);
     ClusterEvent event = new ClusterEvent(ClusterEventType.Unknown);
     event.addAttribute(AttributeName.helixmanager.name(), manager);
-    event.addAttribute(AttributeName.ControllerDataProvider.name(),
-        new ResourceControllerDataProvider());
+    ResourceControllerDataProvider dataCache = new ResourceControllerDataProvider();
+    dataCache.setAsyncTasksThreadPool(Executors.newSingleThreadExecutor());
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java:66]: Could you add a comment here stating why we need to set async tasks thread pool? What happens if we don't?

Comment (zhangmeng916) [reply helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java:66]: Sure. I'll add. The reason I found this issue is that when I changed the session Id to be a valid one, the test actually failed. And debugging, I found it's due to the Executor was not set up, and thus the periodically clean up job for pending messages throw an NPE, which caused the pipeline to stop.

Comment (narendly) [reply helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java]: I see. Although not directly related to this PR, do you think we should consider handling this NPE? It seems like something we should handle more gracefully (we probably won't have this issue in production).

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java [hunk 2]
```diff
@@ -61,8 +62,11 @@ public void testDuplicateMsg() {
     HelixManager manager = new DummyClusterManager(clusterName, accessor);
     ClusterEvent event = new ClusterEvent(ClusterEventType.Unknown);
     event.addAttribute(AttributeName.helixmanager.name(), manager);
-    event.addAttribute(AttributeName.ControllerDataProvider.name(),
-        new ResourceControllerDataProvider());
+    ResourceControllerDataProvider dataCache = new ResourceControllerDataProvider();
+    // The AsyncTasksThreadPool needs to be set, otherwise to start pending message cleanup job
+    // will throw NPE and stop the pipeline.
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java:67]: Once we create an issue, you could link that issue number in the comment so we could track it better.

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java (hunk 1 above)
Comment (zhangmeng916) [reply helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java]: Our controller has properly set this field during construction: cache.setAsyncTasksThreadPool(_asyncTasksThreadPool);
I'd think the code itself should be safe.

**Comment by zhangmeng916** [comment]
This PR is ready to be merged, approved by @narendly 
Final commit message:
Fix TestRebalancePipeline using correct session id and cache initialization.

**Comment by narendly** [comment]
In the test testDuplicateMsg from TestRebalancePipeline, currently an invalid session id is used.
The wrong session id makes the following test and assertion meaningless. This PR uses the correct session id liveInstances.get(0).getEphemeralOwner() instead. 

Also, we found a NPE thrown during the pipeline, causing the pipeline to stop, due to the missing thread pool in setAsyncTasksThreadPool. This PR works around the issue by giving it a thread pool and adds an issue reference in the comment block.

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java [hunk 3]
```diff
@@ -61,8 +62,11 @@ public void testDuplicateMsg() {
     HelixManager manager = new DummyClusterManager(clusterName, accessor);
     ClusterEvent event = new ClusterEvent(ClusterEventType.Unknown);
     event.addAttribute(AttributeName.helixmanager.name(), manager);
-    event.addAttribute(AttributeName.ControllerDataProvider.name(),
-        new ResourceControllerDataProvider());
+    ResourceControllerDataProvider dataCache = new ResourceControllerDataProvider();
+    // The AsyncTasksThreadPool needs to be set, otherwise to start pending message cleanup job
+    // will throw NPE and stop the pipeline. TODO: https://github.com/apache/helix/issues/1158
+    dataCache.setAsyncTasksThreadPool(Executors.newSingleThreadExecutor());
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java:68]: Another important thing we should do here is to shut down the threads/thread pool. Otherwise, there will be a thread pool/thread leak throughout the test suite. This has been a real pain for Helix's test suite, so let's make sure we don't leak it here.

We could pull out this single thread executor to create a reference and shut it down at the end of the test.

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java [hunk 4]
```diff
@@ -45,10 +47,17 @@
 import org.apache.helix.model.Message;
 import org.apache.helix.model.Partition;
 import org.testng.Assert;
+import org.testng.annotations.AfterClass;
 import org.testng.annotations.Test;
 
 public class TestRebalancePipeline extends ZkUnitTestBase {
   private final String _className = getShortClassName();
+  private ExecutorService _executorService;
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java:55]: Should we not have this variable in the scope of the class? Since this isn't being used throughout the class, we could just create the reference in the test method and shut down at the very end of the method. That way, we don't need to add the afterClass() method.

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java [hunk 5]
```diff
@@ -61,8 +70,12 @@ public void testDuplicateMsg() {
     HelixManager manager = new DummyClusterManager(clusterName, accessor);
     ClusterEvent event = new ClusterEvent(ClusterEventType.Unknown);
     event.addAttribute(AttributeName.helixmanager.name(), manager);
-    event.addAttribute(AttributeName.ControllerDataProvider.name(),
-        new ResourceControllerDataProvider());
+    ResourceControllerDataProvider dataCache = new ResourceControllerDataProvider();
+    // The AsyncTasksThreadPool needs to be set, otherwise to start pending message cleanup job
+    // will throw NPE and stop the pipeline. TODO: https://github.com/apache/helix/issues/1158
+    _executorService = Executors.newSingleThreadExecutor();
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java:76]: `_executorService ` does not have to be a private variable. We could probably just use a local reference, and shut down at the end of the method.

**Comment by zhangmeng916** [comment]
This PR is ready to be merged, approved by @narendly
Final commit message:
Fix TestRebalancePipeline using correct session id and cache initialization.
