### PR TITLE
Compatible support for ZNRecord to work with Jackson 1 mapper

### LINKED ISSUE #1655: Jackson 1.x serializer does not work with ZNRecord
### Description
"org.codehaus.jackson:jackson-mapper-asl:1.9.13" because 1.9.13 can not deserialize the bytes when used by helix client.

```
org.codehaus.jackson.map.JsonMappingException: Type variable 'T' can not be resolved (with context of class org.apache.helix.zookeeper.datamodel.ZNRecord)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCache2(StdDeserializerProvider.java:315) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCacheValueDeserializer(StdDeserializerProvider.java:290) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
        at org.codehaus.jackson.map.deser.StdDeserializerProvider.findValueDeserializer(StdDeserializerProvider.java:159) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
        at org.codehaus.jackson.map.deser.StdDeserializerProvider.findTypedValueDeserializer(StdDeserializerProvider.java:180) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
        at org.codehaus.jackson.map.ObjectMapper._findRootDeserializer(ObjectMapper.java:2829) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
        at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2728) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1909) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
        at com.abc.PropertyCompressedJsonSerializer.deserialize(PropertyCompressedJsonSerializer.java:81) []
        at org.apache.helix.zookeeper.zkclient.serialize.BasicZkSerializer.deserialize(BasicZkSerializer.java:39) [helix-core-1.0.1.2402.jar:1.0.1.2402]
        at org.apache.helix.zookeeper.zkclient.ZkClient.deserialize(ZkClient.java:1791) [helix-core-1.0.1.2402.jar:1.0.1.2402]
        at org.apache.helix.zookeeper.zkclient.ZkClient.readData(ZkClient.java:1830) [helix-core-1.0.1.2402.jar:1.0.1.2402]
        at org.apache.helix.zookeeper.zkclient.ZkClient.readData(ZkClient.java:1814) [helix-core-1.0.1.2402.jar:1.0.1.2402]
        at org.apache.helix.manager.zk.ZkBaseDataAccessor.get(ZkBaseDataAccessor.java:472) [helix-core-1.0.1.2402.jar:1.0.1.2402]
        at org.apache.helix.manager.zk.ZkCacheBaseDataAccessor.get(ZkCacheBaseDataAccessor.java:391) [helix-core-1.0.1.2402.jar:1.0.1.2402]
```

### Root cause
Jackson was upgraded in helix from 1.x to 2.x. Jackson 1.x does not support Jackson 2.x annotations.

### Proposed solution
According to Jackson's recommendation on GitHub doc: https://github.com/FasterXML/jackson-annotations,
Backwards compatibility:

- You can make Jackson 2 use Jackson 1 annotations with [jackson-legacy-introspector](https://github.com/Laures/jackson-legacy-introspector)

### PR DESCRIPTION
**Pull request by pkuwm**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1655 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Jackson was upgraded in helix from 1.x to 2.x (https://github.com/apache/helix/pull/1293). Jackson 1.x does not support Jackson 2.x annotations.

This PR rolls back Jackson 2 annotations to Jackson 1, and adds a custom `CodehausJacksonAnnotationIntrospector` to make Jackson 2 work with Jackson 1 annotations. The custom "CodehausJacksonAnnotationIntrospector" is based on Jackson's recommendation on GitHub doc: https://github.com/FasterXML/jackson-annotations,
Backwards compatibility: You can make Jackson 2 use Jackson 1 annotations with [jackson-legacy-introspector](https://github.com/Laures/jackson-legacy-introspector)

The introspector is simplified and customized to ONLY work with Jackson 1 annotations in helix. It is implemented for backward compatibility, and should be deprecated once all Jackson 1 annotations are upgrade/removed in Helix.

Classes that roll back to use Jackson 1 annotations:
- `ZNRecord`
- `SessionAwareZNRecord`

### Tests

- [x] The following tests are written for this issue:

 - `testCodehausJacksonSerializer`

- The following is the result of the "mvn test" command on the appropriate module:

zookeeper-api
```
[INFO] Tests run: 53, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 67.799 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 53, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:11 min
[INFO] Finished at: 2021-02-26T17:56:52-08:00
[INFO] ------------------------------------------------------------------------
```

helix-core
```
[INFO] Tests run: 1264, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4,989.124 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1264, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:23 h
[INFO] Finished at: 2021-02-28T14:25:40-08:00
[INFO] ------------------------------------------------------------------------
```

helix-rest
```
[INFO] Tests run: 171, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 93.342 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 171, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:38 min
[INFO] Finished at: 2021-02-27T21:08:48-08:00
[INFO] ------------------------------------------------------------------------
```

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Review by jiajunwang — COMMENTED** [review]
Thanks for the fix. One thing, is it possible to create a util method for all the Helix code to get a modified ObjectMapper? So we don't need to do such a change again once we get rid of codehaus.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/introspect/CodehausJacksonIntrospector.java [hunk 1]
```diff
@@ -0,0 +1,289 @@
...
+import org.codehaus.jackson.map.annotate.JsonSerialize;
+import org.codehaus.jackson.map.annotate.NoClass;
+
+/**
+ * This introspector works with jackson 1 annotations used in
+ * {@link org.apache.helix.zookeeper.datamodel.ZNRecord}.
+ * This is supposed used ONLY in Helix as it could be deprecated in the next major release.
+ */
+// TODO: remove this class once upgrading to Jackson 2.x in ZNRecord
+public class CodehausJacksonIntrospector extends NopAnnotationIntrospector {
```
Comment (dasahcc) [inline zookeeper-api/src/main/java/org/apache/helix/zookeeper/introspect/CodehausJacksonIntrospector.java:48]: This is class we implemented, right? Then let's try to make the naming more readable.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/introspect/CodehausJacksonIntrospector.java [hunk 2]
```diff
@@ -0,0 +1,289 @@
...
+    if (param != null) {
+      JsonProperty pann = param.getAnnotation(JsonProperty.class);
+      if (pann != null) {
+        return pann.value();
+      }
+    }
+    return null;
+  }
+
+  @SuppressWarnings("deprecation")
```
Comment (dasahcc) [inline zookeeper-api/src/main/java/org/apache/helix/zookeeper/introspect/CodehausJacksonIntrospector.java:120]: Question: This is deprecated. Do we need to override it?

File: helix-core/src/test/java/org/apache/helix/manager/zk/TestZNRecordSerializer.java [hunk 3]
```diff
@@ -271,4 +278,83 @@ public void testCompression() {
...
+    public byte[] serialize(Object data) {
+      SerializationConfig serializationConfig = mapper.getSerializationConfig();
+      serializationConfig.set(SerializationConfig.Feature.INDENT_OUTPUT, true);
+      serializationConfig.set(SerializationConfig.Feature.AUTO_DETECT_FIELDS, true);
+      serializationConfig.set(SerializationConfig.Feature.CAN_OVERRIDE_ACCESS_MODIFIERS, true);
+      StringWriter sw = new StringWriter();
+
+      try {
+        mapper.writeValue(sw, data);
+
```
Comment (xyuanlu) [inline helix-core/src/test/java/org/apache/helix/manager/zk/TestZNRecordSerializer.java:329]: nit: extra line

**Review by pkuwm — COMMENTED** [review]
> Thanks for the fix. One thing, is it possible to create a util method for all the Helix code to get a modified ObjectMapper? So we don't need to do such a change again once we get rid of codehaus.

@jiajunwang Good question. I thought about it too. My thought was return the ObjectMapper configured with the introspector from the util `ObjectMapper mapper = JacksonUtil.newObjectMapper();` Once we remove codehaus, we just need to remove the config in `JacksonUtil.newObjectMapper()` method.

Thinking again, if we do so, there'll be mixed usages in creating an ObjectMapper: `new ObjectMapper()` and `JacksonUtil.newObjectMapper()`. After we remove codehaus, `JacksonUtil.newObjectMapper()` will just do the same as `New ObjectMapper()`, which makes `newObjectMapper()` look redundant.

Plus, there are only 6 places that need to set Introspector in this PR. Once we remove the codehaus and the introspector, we just need to remove the 6 places that set introspector - pretty simple. So I just don't think we need to have the util :)

File: metadata-store-directory-common/pom.xml [hunk 4]
```diff
@@ -47,7 +47,7 @@
     <dependency>
       <groupId>com.fasterxml.jackson.core</groupId>
       <artifactId>jackson-databind</artifactId>
-      <version>2.10.2</version>
+      <version>2.11.0</version>
```
Comment (zhangmeng916) [inline metadata-store-directory-common/pom.xml:50]: I'm a bit confused about the lib changes in several pom files. Would you explain a bit? Also does it require any ivy file change later?

**Comment by jiajunwang** [comment]
> > Thanks for the fix. One thing, is it possible to create a util method for all the Helix code to get a modified ObjectMapper? So we don't need to do such a change again once we get rid of codehaus.
> 
> @jiajunwang Good question. I thought about it too. My thought was return the ObjectMapper configured with the introspector from the util `ObjectMapper mapper = JacksonUtil.newObjectMapper();` Once we remove codehaus, we just need to remove the config in `JacksonUtil.newObjectMapper()` method.
> 
> Thinking again, if we do so, there'll be mixed usages in creating an ObjectMapper: `new ObjectMapper()` and `JacksonUtil.newObjectMapper()`. After we remove codehaus, `JacksonUtil.newObjectMapper()` will just do the same as `New ObjectMapper()`, which makes `newObjectMapper()` look redundant.
> 
> Plus, there are only 6 places that need to set Introspector in this PR. Once we remove the codehaus and the introspector, we just need to remove the 6 places that set introspector - pretty simple. So I just don't think we need to have the util :)

Yeah, not a big deal. I don't think we will miss any of the reference since the method will be removed in the future.

File: helix-core/src/test/java/org/apache/helix/TestShuffledIdealState.java [hunk 5]
```diff
@@ -65,7 +66,8 @@ public void testInvocation() throws Exception {
     IdealCalculatorByConsistentHashing.printNodeOfflineOverhead(result3);
 
     // System.out.println(result);
-    ObjectMapper mapper = new ObjectMapper();
+    ObjectMapper mapper =
```
Comment (zhangmeng916) [inline helix-core/src/test/java/org/apache/helix/TestShuffledIdealState.java:69]: Is this the only test that you picked to change?

File: metadata-store-directory-common/pom.xml (hunk 4 above)
Comment (pkuwm) [reply metadata-store-directory-common/pom.xml:50]: Sure.
1. jackson-databind depends on jackson-core, so no need to explicitly specify jackson-core
2. If jackson 2.11.0 is used in helix, I believe it is better to make the version consistent. So change 2.10.2 -> 2.11.0
3. Yeah, better to also change the version in Ivy.

File: helix-core/src/test/java/org/apache/helix/TestShuffledIdealState.java (hunk 5 above)
Comment (pkuwm) [reply helix-core/src/test/java/org/apache/helix/TestShuffledIdealState.java:69]: If an ObjectMapper needs to deserialize ZNRecord, it needs to set the introspector.
This test is the only test in helix-core that explicitly creates an ObjectMapper to work with ZNRecord. If we want to do better, this test should use the `ZNRecordSerializer` to deserialize it. To make the code minimum, I just don't want to do the refactoring work.

**Review by dasahcc — APPROVED** [review]

**Review by xyuanlu — APPROVED** [review]

**Comment by pkuwm** [comment]
This PR is ready to be merged, approved by @dasahcc @xyuanlu 

Jackson was upgraded in helix from 1.x to 2.x (#1293). Jackson 1.x does not support Jackson 2.x annotations.

This commit rolls back Jackson 2 annotations to Jackson 1, and adds a custom CodehausJacksonAnnotationIntrospector to make Jackson 2 in helix work with Jackson 1 annotations.
