### PR TITLE
Fix error partition blocks load rebalance

### LINKED ISSUE #1866: Per replica throttling ERROR partition blocks load reblance
### Describe the bug
With error partition threshold, not only downward is allowed but other non downward load rebalance processed as well.

### To Reproduce
Set error partition threshold and make error partition number of that.
There will still be non downward STs going out.

### Expected behavior
No non downward STs going out when error partition threshold reaches.

### PR DESCRIPTION
**Pull request by junkaixue**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1866 

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

There are three things fixed:
1. State priority is higher priority with smaller number.
2. When only downward is allowed, any non downward STs must be removed from message and throttled.
3. Even for downward STs should be respect to the throttling as backward compatible behavior.

### Tests

- [X] The following tests are written for this issue:

Add test case in TestReplicaLevelThrottling.java

- The following is the result of the "mvn test" command on the appropriate module:

[INFO] Tests run: 1284, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5,047.108 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1284, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.6:report (generate-code-coverage-report) @ helix-core ---
[INFO] Loading execution data file /home/jxue/helix/helix-core/target/jacoco.exec
[INFO] Analyzed bundle 'Apache Helix :: Core' with 909 classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:24 h
[INFO] Finished at: 2021-09-12T01:23:08-07:00
[INFO] Final Memory: 35M/733M
[INFO] ------------------------------------------------------------------------

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java [hunk 1]
```diff
@@ -520,8 +520,12 @@ private void loadRebalance(Resource resource, Partition partition,
        ResourceControllerDataProvider cache,
       boolean onlyDownwardLoadBalance, StateModelDefinition stateModelDefinition, Set<String> messagesThrottled,
       Map<Partition, List<Message>> resourceMessageMap) {
-    if (onlyDownwardLoadBalance && isLoadBalanceDownwardStateTransition(messageToThrottle, stateModelDefinition)) {
-      // Remove the message already allowed for downward state transitions.
+    // If only downward allowed: 1) any non-downward ST messages will be throttled and removed.
+    //                           2) any downward ST messages will respect the throttling.
+    // If not only downward allowed, all ST messages should respect the throttling.
+    if (onlyDownwardLoadBalance && !isLoadBalanceDownwardStateTransition(messageToThrottle, stateModelDefinition)) {
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java:526]: The change makes sense now. But ideally, I think we should let the throttling class handle extra logic like "onlyDownwardLoadBalance". I propose that we refactor this when deprecating the IntermediateStateCalcStage class. Please add a TODO here if you think it makes sense.

**Review by jiajunwang — APPROVED** [review]

File: helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java (hunk 1 above)
Comment (junkaixue) [reply helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java:526]: Yeah. That makes sense to me. Will change it.
