### PR TITLE
ExpiredJob Workaround for Selective Update Race Conditions

### LINKED ISSUE #1469: Task Garbage Collection deletes jobs due to selective update phantom read
### Describe the bug
Due to the way selective update is done, it's possible to read a WorkflowConfig containing more jobs in a DAG than the actual JobConfigs read. That causes Garbage Collection stage to remove the jobs from the DAG as well. 

### To Reproduce
1. Add job 1; 
2. finishes the "listing" operation during selective update; 
3. add job 2 and update WorkflowConfig DAG;
4. finishes the "updating" operation during selective update.
This results in a WorkflowConfig containing a DAG of both job 1 and job 2, but only job 1 is read into the cache. 

### Expected behavior
Task Garbage Collection stage should try not to delete jobs like those before a better solution is implemented.

### PR DESCRIPTION
**Pull request by NealSun96**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1469 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Cache selective update is a two step procedure. It first "lists", which gets all the ZNodes, and then it "updates" by comparing ZNode metadata to determine which ZNodes have been changed. Job enqueue is also a two step procedure, where it adds all JobConfigs one by one, and update WorkflowConfig's DAG in the end.  

If selective update "lists" before all JobConfigs are added, and "updates" after the WorkflowConfig is done updating, it's possible to read in a DAG containing more jobs than JobConfigs that are seen by selective update. This causes TaskGarbageCollection to remove the jobs that are "missing" JobConfigs, even though their JobConfigs actually exist. This PR implements a workaround for determining expired jobs while avoiding this case of cache "phantom read": if JobConfig doesn't exist in the cache, check ZK directly.

### Tests

- [x] The following is the result of the "mvn test" command on the appropriate module:

```
[ERROR] Tests run: 1234, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 4,885.942 s <<< FAILURE! - in TestSuite
[ERROR] testPeriodicRefresh(org.apache.helix.integration.spectator.TestRoutingTableProviderPeriodicRefresh)  Time elapsed: 2.022 s  <<< FAILURE!
java.lang.AssertionError: expected:<4> but was:<3>
        at org.apache.helix.integration.spectator.TestRoutingTableProviderPeriodicRefresh.testPeriodicRefresh(TestRoutingTableProviderPeriodicRefresh.java:214)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestRoutingTableProviderPeriodicRefresh.testPeriodicRefresh:214 expected:<4> but was:<3>
[INFO] 
[ERROR] Tests run: 1234, Failures: 1, Errors: 0, Skipped: 1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:21 h
[INFO] Finished at: 2020-10-21T12:14:46-07:00
[INFO] ------------------------------------------------------------------------
```
### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Comment by NealSun96** [comment]
Disclaimer: with help from @kaisun2000 , I used the debugger to create a situation outlined in the description, which causes certain job enqueuing tests (such as TestEnqueueJobs) to consistently fail. With this change, these tests consistently pass. The job enqueuing tests were also run for 20 times to verify consistent passing.

**Review by alirezazamani — APPROVED** [review]
LGTM

File: helix-core/src/main/java/org/apache/helix/task/TaskUtil.java [hunk 1]
```diff
@@ -789,14 +789,19 @@ protected static boolean removeJobsFromWorkflow(final HelixDataAccessor dataAcce
    */
   public static Set<String> getExpiredJobsFromCache(
       WorkflowControllerDataProvider workflowControllerDataProvider, WorkflowConfig workflowConfig,
-      WorkflowContext workflowContext) {
+      WorkflowContext workflowContext, HelixManager manager) {
```
Comment (kaisun2000) [inline helix-core/src/main/java/org/apache/helix/task/TaskUtil.java:792]: This is a public API change. If there is other place using this API, the compilation may fail.

File: helix-core/src/main/java/org/apache/helix/controller/stages/TaskGarbageCollectionStage.java [hunk 2]
```diff
@@ -81,8 +81,8 @@ public void process(ClusterEvent event) throws Exception {
         if (nextPurgeTime <= currentTime) {
           nextPurgeTime = currentTime + purgeInterval;
           // Find jobs that are ready to be purged
-          Set<String> expiredJobs =
-              TaskUtil.getExpiredJobsFromCache(dataProvider, workflowConfig, workflowContext);
+          Set<String> expiredJobs = TaskUtil
+              .getExpiredJobsFromCache(dataProvider, workflowConfig, workflowContext, manager);
```
Comment (kaisun2000) [inline helix-core/src/main/java/org/apache/helix/controller/stages/TaskGarbageCollectionStage.java:85]: This is public API change. I know it is added recently, but are we sure this won't break some other code using TaskUtil?

The other way can be simply add a check after line 85 to see if any expiredJobs are in the config and remove them from the expiredJob set.

**Comment by kaisun2000** [comment]
The other thing is that can we run this fix in githut say 20 times to see if it fails any previous sensitive test? The 20 times test would give a signal as to whether the fix would work. Do we feel this is necessary?

File: helix-core/src/main/java/org/apache/helix/controller/stages/TaskGarbageCollectionStage.java (hunk 2 above)
Comment (NealSun96) [reply helix-core/src/main/java/org/apache/helix/controller/stages/TaskGarbageCollectionStage.java:85]: I see the concern here, but doing it in the way you described is not so clean. We need to check for the case of "JobConfig missing from cache but exist in ZK" for all the expiredJobs, and for each of those cases, we need to apply the "isJobExpired" logic again. There is a lot of logic redundancy here. 

Is that better than changing the signature? I think both ways have minor drawbacks, but I personally think changing the signature is fine.

Comment (kaisun2000) [reply helix-core/src/main/java/org/apache/helix/controller/stages/TaskGarbageCollectionStage.java:85]: Good point. Maybe let us create something like `TaskUtil.getExpiredJobsFromCacheAndCheckZk` which uses `TaskUtil.getExpiredJobsFromCache()`

Comment (NealSun96) [reply helix-core/src/main/java/org/apache/helix/controller/stages/TaskGarbageCollectionStage.java:85]: Is that going to be a public function? If so, can we remove that public function after we fix phantom write? 

I don't think this is a big problem; this function is too new to cause large impact imo.

Comment (kaisun2000) [reply helix-core/src/main/java/org/apache/helix/controller/stages/TaskGarbageCollectionStage.java:85]: We can make something like "TaskUtil.getExpiredJobsFromCacheAndCheckZk" deprecated once we fixed root of the selective update issue. The fix may take several quarters though.

If you believe `TaskUtil.getExpiredJobsFromCache()` is not used by others. Then shall we run this diff against TMC build to see parterners in upstream can build against this one successfully? It would be much more costly if people later find this thing does not work in release time.

Comment (NealSun96) [reply helix-core/src/main/java/org/apache/helix/controller/stages/TaskGarbageCollectionStage.java:85]: I think this may be an overkill. I did a code search and didn't find any code calling this function. 

In addition, I can allow `manager` to be null for maximum backward compatibility.

Comment (kaisun2000) [reply helix-core/src/main/java/org/apache/helix/controller/stages/TaskGarbageCollectionStage.java:85]: Some of the partners code are actually also hosted in github. Code search won't really yield the current usage. In fact last time we  found some issue when integrating with Gobblin. Let me slack you the command to check build. 

If the build works, we can just use this diff without any change.

Comment (kaisun2000) [reply helix-core/src/main/java/org/apache/helix/controller/stages/TaskGarbageCollectionStage.java:85]: The build seems working. let us just keep this change then.

**Review by kaisun2000 — APPROVED** [review]

**Comment by NealSun96** [comment]
This PR is ready to be merged, approved by @alirezazamani @kaisun2000 
Final commit message:
## ExpiredJob Workaround for Selective Update Race Conditions  ##
This PR implements a workaround for determining expired jobs that avoids selective update race condition: if JobConfig doesn't exist in the cache, check ZK directly.
