### PR TITLE
Fixing the TestClusterStatusMonitorLifecyle integration test

### LINKED ISSUE #2200: [Failed CI Test] testClusterStatusMonitorLifecycle(org.apache.helix.monitoring.TestClusterStatusMonitorLifecycle)
This issue is created for tracking unstable test: testClusterStatusMonitorLifecycle(org.apache.helix.monitoring.TestClusterStatusMonitorLifecycle)

### PR DESCRIPTION
**Pull request by parakhnr**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:
* #2200, #2387

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

#### Brief overview of the integration test
In a nutshell, the integration test verifies that he metrics for the `ClusterStatus` are emitted correctly when participants/controller_participants are added/removed.

#### What's the failure?
Towards the end of the test, we disconnect all the controller from the super cluster and ensure that there are 0 metrics related to the `ClusterStatus` being emitted.

#### Analysis
Upon debugging the test failure from the logs, I found a race condition for the last controller `controller_9(CONTROLLER_PARTICIPANT) ` in the super cluster disconnect process which can be explained from the logs below:

```
--- Disconnect initiated for **controller_9[CONTROLLER_PARTICPANT]**
2023-05-09T17:14:02.0244076Z 5813977 [ClusterManager_Watcher_CONTROLLER_TestClusterStatusMonitorLifecycle_controller_9_CONTROLLER_PARTICIPANT_11918] INFO  org.apache.helix.manager.zk.ZKHelixManager [] - disconnect controller_9(CONTROLLER_PARTICIPANT) from CONTROLLER_TestClusterStatusMonitorLifecycle

--- Message to become leader sent by the **controller_9**
2023-05-09T17:14:02.2758113Z 5814083 [HelixController-pipeline-default-CONTROLLER_TestClusterStatusMonitorLifecycle-(075feaf2_DEFAULT)] INFO  org.apache.helix.controller.stages.MessageDispatchStage [] - Event 075feaf2_DEFAULT : Sending Message 1495e9e6-e04c-4e43-b565-8aa64f22039e to
 controller_9 transit TestClusterStatusMonitorLifecycle0.TestClusterStatusMonitorLifecycle0_9|[] from:STANDBY to:LEADER, relayMessages: 0

--- **controller_9** attempts to become leader for **TestClusterStatusMonitorLifecycle0_9** due to the StateModel transition
2023-05-09T17:14:02.4001289Z 5814212 [HelixTaskExecutor-message_handle_STATE_TRANSITION] INFO  org.apache.helix.participant.DistClusterControllerStateModel [] - controller_9 becoming leader from standby for TestClusterStatusMonitorLifecycle0_9

--- Rest the state model which disconnects **controller_9** from being the controller for **TestClusterStatusMonitorLifecycle0_9**
2023-05-09T17:14:02.4037210Z 5814273 [ClusterManager_Watcher_CONTROLLER_TestClusterStatusMonitorLifecycle_controller_9_CONTROLLER_PARTICIPANT_11918] INFO  org.apache.helix.participant.HelixStateMachineEngine [] - Operating on TestClusterStatusMonitorLifecycle0::TestClusterStatusMonitorLifecycle0_9

--- *controller_9** becomes leader for **TestClusterStatusMonitorLifecycle0_9** due to the StateModel transition
2023-05-09T17:14:03.9794014Z 5815598 [HelixTaskExecutor-message_handle_STATE_TRANSITION] INFO  org.apache.helix.participant.AbstractHelixLeaderStandbyStateModel [] - Helix Service Controller for cluster TestClusterStatusMonitorLifecycle0_9 on instance controller_9 became LEADER from STANDBY
```

Based on the above logs, reset for `TestClusterStatusMonitorLifecycle0_9` happens before the `controller_9` transitions to being leader [NOTE: Timestamps are very close, and since it's separate thread trying to invoke different methods there is race over here too, which results in reset being processed first] for `TestClusterStatusMonitorLifecycle0_9` which results in disconnect being not [invoked](https://github.com/apache/helix/blob/1f5c5c82fb5bc8273f3d6e04b4cc245e77ece2c8/helix-core/src/main/java/org/apache/helix/participant/DistClusterControllerStateModel.java#L116) as reset only works if the controller is the leader for that resource partition. So, this leaves `controller_9` be the leader despite it's disconnected. 

#### Solution
We should wait for the cluster to stabilize before we disconnect it especially when are taking controllers from the super cluster one after another. 
**NOTE: This is not fixing the actual race condition. Fixing the race condition will be prioritized later since it's a larger and complex effort.**

### Tests

- [X] The following tests are written for this issue:

Ran the `TestClusterStatusMonitorLifecyle` integration test locally 10 times in a loop successfully.

### Changes that Break Backward Compatibility (Optional)
N/A

### Documentation (Optional)

N/A

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/manager/zk/ZKHelixManager.java [hunk 1]
```diff
@@ -793,13 +793,14 @@ void createClient() throws Exception {
 
   @Override
   public void connect() throws Exception {
-    LOG.info("ClusterManager.connect()");
```
Comment (rahulrane50) [inline helix-core/src/main/java/org/apache/helix/manager/zk/ZKHelixManager.java:796]: It's still useful to have this log if we return if we are already connected.

Comment (parakhnr) [reply helix-core/src/main/java/org/apache/helix/manager/zk/ZKHelixManager.java:796]: We already log a warn message on 797 if we are already connected before we return.

File: helix-core/src/test/java/org/apache/helix/monitoring/TestClusterStatusMonitorLifecycle.java [hunk 2]
```diff
@@ -164,46 +136,41 @@ public void beforeClass() throws Exception {
...
+    for (int i = 0; i < n; i++) {
+      ClusterDistributedController controller = _controllers[i];
+      if (controller != null) {
+        ZkHelixClusterVerifier controllerClusterVerifier =
+            new BestPossibleExternalViewVerifier.Builder(controller.getClusterName()).setZkClient(
+                    _gZkClient).setWaitTillVerify(TestHelper.DEFAULT_REBALANCE_PROCESSING_WAIT_TIME)
+                .build();
+        Assert.assertTrue(controllerClusterVerifier.verifyByPolling(),
+            "Controller cluster NOT in ideal state");
+        System.out.println(String.format("Disconnecting controller %s from cluster %s at %s",
```
Comment (rahulrane50) [inline helix-core/src/test/java/org/apache/helix/monitoring/TestClusterStatusMonitorLifecycle.java:167]: is this println intentional or we can replace it with log message?

File: helix-core/src/test/java/org/apache/helix/monitoring/TestClusterStatusMonitorLifecycle.java [hunk 3]
```diff
@@ -164,46 +136,41 @@ public void beforeClass() throws Exception {
...
-      if (_controllers[i] != null) {
-        _controllers[i].syncStop();
-      }
-    }
     for (MockParticipantManager participant : _participants) {
       if (participant != null) {
         participant.syncStop();
       }
     }
-    cleanupControllers();
```
Comment (rahulrane50) [inline helix-core/src/test/java/org/apache/helix/monitoring/TestClusterStatusMonitorLifecycle.java:177]: Umm why are we removing this? We still want to remove all controllers at the end of this test case right?

File: helix-core/src/main/java/org/apache/helix/manager/zk/ZKHelixManager.java (hunk 1 above)
Comment (rahulrane50) [reply helix-core/src/main/java/org/apache/helix/manager/zk/ZKHelixManager.java:796]: Ahh completely missed it.

File: helix-core/src/test/java/org/apache/helix/monitoring/TestClusterStatusMonitorLifecycle.java (hunk 2 above)
Comment (parakhnr) [reply helix-core/src/test/java/org/apache/helix/monitoring/TestClusterStatusMonitorLifecycle.java:167]: We have log level of `ERROR` enabled, which means no `INFO` logs will be shown when we run the test. I intentionally used `sys.out` so that they show up in the CI logs.

**Review by rahulrane50 — APPROVED** [review]

**Comment by xyuanlu** [comment]
Thanks for working on this! Detailed analysis! LGTM. 
Could you please run the whole CI suite 20 times and update the link? 
Thanks!

**Comment by desaikomal** [comment]
Thanks Naman for fixing the bug.
Wrt - reset() and disconnect() happening in parallel and reset() takes precedence over disconnect() seems wrong to me. Will you have another issue created to track the above race?

**Review by desaikomal — APPROVED** [review]
LGTM

**Comment by parakhnr** [comment]
> Thanks Naman for fixing the bug. Wrt - reset() and disconnect() happening in parallel and reset() takes precedence over disconnect() seems wrong to me. Will you have another issue created to track the above race?

Yes. I will create another issue for this one.

**Comment by parakhnr** [comment]
> Thanks for working on this! Detailed analysis! LGTM. Could you please run the whole CI suite 20 times and update the link? Thanks!

I ran the `PR_CI` workflow 20 times and the results can be found over [here](https://github.com/parakhnr/helix/actions?query=branch%3Afix-clusterstatusmonitor-test-20). For the tests that failed I didn't saw any failures related to `TestClusterStatusMonitorLifecycle`.

**Comment by parakhnr** [comment]
The code has been reviewed and approved by @rahulrane50, @desaikomal  and @xyuanlu.
Commit message: Fixing the TestClusterStatusMonitorLifecyle integration test.
