### PR TITLE
Fix Issue#1941 - Incorrect condition caused not to log error message.

### LINKED ISSUE #1941: Error partition logging is not in effect
### Describe the bug
Error partition logging in IntermediateStateCalcStage does not work since the if condition is always false. 

### To Reproduce
The logging is absent with error partitions. 

### Expected behavior
The logging should work correctly when there are error partitions.

### PR DESCRIPTION
**Pull request by desaikomal**
### Issues
- [x] My PR addresses the following Helix issues and references them in the PR description:
Resolves #1941 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
There is a wrong condition which will never log the error message.

Fixed the condition by populating the partition information with ERROR state.

Earlier condition: 
    if (!partitionsWithErrorStateReplica.isEmpty()) {
      LogUtil.logInfo(logger, _eventId,
          String.format("Partition currently has an ERROR replica in %s partitions: %s",
              resourceName, partitionsWithErrorStateReplica));
    }
The partitionsWithErrorStateReplica was never populated as a result we were never logging the error message.
The error message will now populate the resource/partition information appropriately.

### Tests

- [ ] The following tests are written for this issue:

(List the names of added unit/integration tests)

- The following is the result of the "mvn test" command on the appropriate module:

(If CI test fails due to known issue, please specify the issue and test PR locally. Then copy & paste the result of "mvn test" to here.)
[INFO] Results:
[INFO] 
[INFO] Tests run: 1287, Failures: 0, Errors: 0, Skipped: 0
[INFO] 

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

No API change, just bug fix.

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java [hunk 1]
```diff
@@ -31,6 +31,7 @@
 
 import java.util.stream.Collectors;
 import java.util.stream.IntStream;
+
```
Comment (NealSun96) [inline helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java:34]: @desaikomal It occurred to me that you might not be using helix-style-intellij.xml to format the code. It's a requirement for Helix PRs, and you can find guidelines here: https://github.com/apache/helix/wiki/Helix-Code-Style-in-Intellij-IDE :)

**Review by NealSun96 — CHANGES_REQUESTED** [review]
For the PR description, please move the first paragraph under Description section, and check all boxes as you have finished them.

**Review by NealSun96 — APPROVED** [review]

**Comment by desaikomal** [comment]
This PR is ready to be merged, approved by @NealSun96 
Final commit message:

Properly populate the error log messages for partitions and resource names whose replica status is in ERROR state.
