### PR TITLE
[apache/helix] -- Fix PreferenceList Ordering Changes during Maintenance Mode

### LINKED ISSUE #2777: Fix PreferenceList Ordering Changes during Maintenance Mode
### Describe the bug
When entering maintenance-mode, we observed that instance order in preference list changes by PreferenceListNodeComparator as it uses the order in which the current-state is materialized in array list.
For instance:
Lets say we have 3 hosts, and here's the Current state:
```
{
   A: LEADER,
   B: FOLLOWER
   C: FOLLOWER
 }
```

Now when we create a preference-list using new ArrayList(currentState.keySet), the order in array-list depends on the hash order the keys (A, B, C). With sorting using PreferenceListNodeComparator, we put Leader at the front and ordering among Followers can be anything and could either be [A, B, C] or [A, C, B ]

### To Reproduce
If we have a set of string where the hash order is different than the insert order then we can see this issue:
Insert order: [Q3ZZuCeBpu, QY9U91XBYo, GMYBW20gmC]
Hash set order: [GMYBW20gmC, QY9U91XBYo, Q3ZZuCeBpu]

### Expected behavior
The preference list order should not change as computed earlier.

### PR DESCRIPTION
**Pull request by himanshukandwal**
### Issues
- [x] My PR addresses the following Helix issues and references them in the PR description:
Fixes #2777

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
When entering maintenance-mode, we observed that instance order in preference list changes by PreferenceListNodeComparator as it uses the order in which the current-state is materialized in array list.
For instance:
Lets say we have 3 hosts, and here's the Current state:
```
{
   A: LEADER,
   B: FOLLOWER
   C: FOLLOWER
 }
```
Now when we create a preference-list using new ArrayList(currentState.keySet), the order in array-list depends on the hash order the keys (A, B, C). With sorting using PreferenceListNodeComparator, we put Leader at the front and ordering among Followers can be anything and could either be [A, B, C] or [A, C, B ]

### Tests

- [x] The following tests are written for this issue:

Added Tests:  `TestMaintenanceRebalancer.testComputeIdealState`
This covers various scenarios where the preference list should be preserved wrt current state

- The following is the result of the "mvn test" command on the appropriate module:

```
mvn clean install -Dmaven.test.skip.exec=true && mvn test -o -Dtest=TestMaintenanceRebalancer -pl=helix-core

[INFO] --- surefire:3.0.0-M3:test (default-test) @ helix-core ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.helix.controller.rebalancer.TestMaintenanceRebalancer
Test case comment: [Case 1] Same state - No (A, B, C) -> (A, C, B) for different hash order
[lKmBBEPisM, 8PNpMU7EgT, HOs3rOFCad]
[lKmBBEPisM, 8PNpMU7EgT, HOs3rOFCad]
Test case comment: [Case 2] Same state - No (A, B, C) -> (A, C, B) for different hash order
[Q3ZZuCeBpu, QY9U91XBYo, GMYBW20gmC]
[Q3ZZuCeBpu, QY9U91XBYo, GMYBW20gmC]
Test case comment: [Case 3] second becomes leader, (A, B, C) -> (B, A, C) for different hash order
[8PNpMU7EgT, lKmBBEPisM, HOs3rOFCad]
[8PNpMU7EgT, lKmBBEPisM, HOs3rOFCad]
Test case comment: [Case 4] second becomes leader, (A, B, C) -> (B, A, C) for different hash order
[QY9U91XBYo, Q3ZZuCeBpu, GMYBW20gmC]
[QY9U91XBYo, Q3ZZuCeBpu, GMYBW20gmC]
Test case comment: [Case 5] leader becomes offline, (A, B, C) -> (B, C, A) for different hash order
[8PNpMU7EgT, HOs3rOFCad, lKmBBEPisM]
[8PNpMU7EgT, HOs3rOFCad, lKmBBEPisM]
Test case comment: [Case 6] leader becomes offline, (A, B, C) -> (B, C, A) for different hash order
[QY9U91XBYo, GMYBW20gmC, Q3ZZuCeBpu]
[QY9U91XBYo, GMYBW20gmC, Q3ZZuCeBpu]
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.983 s - in org.apache.helix.controller.rebalancer.TestMaintenanceRebalancer
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jacoco:0.8.6:report (generate-code-coverage-report) @ helix-core ---
[INFO] Loading execution data file /Users/hkandwal/Documents/workspaces/projects/helix_os_hk/helix-core/target/jacoco.exec
[INFO] Analyzed bundle 'Apache Helix :: Core' with 950 classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  42.293 s
[INFO] Finished at: 2024-03-14T11:50:53-07:00
[INFO] ------------------------------------------------------------------------

```

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/MaintenanceRebalancer.java [hunk 1]
```diff
@@ -55,16 +59,46 @@ public IdealState computeNewIdealState(String resourceName, IdealState currentId
...
+      preferenceList.sort(new StatePriorityComparator(stateMap, stateModelDef));
+
       currentIdealState.setPreferenceList(partition.getPartitionName(), preferenceList);
     }
     LOG.info(String
         .format("End computing ideal state for resource %s in maintenance mode.", resourceName));
     return currentIdealState;
   }
+
+  public static void main(String[] args) {
```
Comment (desaikomal) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/MaintenanceRebalancer.java:82]: any reason to have 'main' in this file?

Comment (himanshukandwal) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/MaintenanceRebalancer.java]: Sorry, this is not intended.. Removed now!

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/MaintenanceRebalancer.java [hunk 2]
```diff
@@ -55,12 +59,19 @@ public IdealState computeNewIdealState(String resourceName, IdealState currentId
...
       List<String> preferenceList = new ArrayList<>(stateMap.keySet());
+
+      // This sorting preserves the ordering of current state hosts in the order of current IS pref list
       Collections.sort(preferenceList, new PreferenceListNodeComparator(stateMap,
-          clusterData.getStateModelDef(currentIdealState.getStateModelDefRef()),
-          Collections.<String>emptyList()));
+          stateModelDef, currentIdealState.getPreferenceList(partition.getPartitionName())));
+
+      // This sorts the current state hosts based on the priority
+      preferenceList.sort(new StatePriorityComparator(stateMap, stateModelDef));
```
Comment (junkaixue) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/MaintenanceRebalancer.java:73]: This will not help, right? It was the problem the order of two followers are not deterministic.

File: helix-core/src/test/java/org/apache/helix/controller/rebalancer/TestMaintenanceRebalancer.java [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+
+  @DataProvider(name = "TestComputeIdealStateInput")
+  public Object[][] loadTestComputeIdealStateInput() {
+    final String[] params = {
+        "comment", "stateModel", "liveInstances", "preferenceList", "currentStateMap", "expectedPreferenceList"
+    };
+    return TestInputLoader.loadTestInputs("MaintenanceRebalancer.ComputeNewIdealState.json", params);
+  }
+
+}
```
Comment (junkaixue) [inline helix-core/src/test/java/org/apache/helix/controller/rebalancer/TestMaintenanceRebalancer.java:60]: NIT: new line.

File: helix-core/src/test/resources/MaintenanceRebalancer.ComputeNewIdealState.json [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+    "currentStateMap": {
+      "Q3ZZuCeBpu" : "OFFLINE",
+      "QY9U91XBYo" : "MASTER",
+      "GMYBW20gmC" : "SLAVE"
+    },
+    "expectedPreferenceList": [
+      "QY9U91XBYo", "GMYBW20gmC", "Q3ZZuCeBpu"
+    ]
+  }
+]
```
Comment (junkaixue) [inline helix-core/src/test/resources/MaintenanceRebalancer.ComputeNewIdealState.json:98]: Same here.

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/MaintenanceRebalancer.java [hunk 5]
```diff
@@ -21,13 +21,17 @@
 
 import java.util.ArrayList;
 import java.util.Collections;
+import java.util.HashSet;
 import java.util.List;
 import java.util.Map;
+import java.util.Set;
 
+import org.apache.commons.lang3.RandomStringUtils;
```
Comment (junkaixue) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/MaintenanceRebalancer.java:29]: Why we need this?

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/MaintenanceRebalancer.java (hunk 2 above)
Comment (himanshukandwal) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/MaintenanceRebalancer.java:73]: So this is getting applied when we have already sorted the current state hosts in the preference-list order. (line: 70)
```
pref-list: [A, B, C]
current-state: {
    A: FOLLOWER,
    B: LEADER,
    C: FOLLOWER
}
```
Lets say `newPrefList = new ArrayList<>(current-state.keySet())` => `[C, B, A]`
```
Sort 1: Sort based on preference-list order:
newPrefList = [C, B, A] => [A, B, C]

Sort 2: Sort based on state-priority order:
newPrefList = [A, B, C] => [B, A, C]
```
Here, A will be 2nd and C will be third always as both have same priority so original (pref-list) order will be maintained.

File: helix-core/src/test/java/org/apache/helix/controller/rebalancer/TestMaintenanceRebalancer.java (hunk 3 above)
Comment (himanshukandwal) [reply helix-core/src/test/java/org/apache/helix/controller/rebalancer/TestMaintenanceRebalancer.java]: Yes, updated. Thanks!

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/MaintenanceRebalancer.java (hunk 5 above)
Comment (himanshukandwal) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/MaintenanceRebalancer.java]: Removed the extra import. Thanks!

File: helix-core/src/test/resources/MaintenanceRebalancer.ComputeNewIdealState.json (hunk 4 above)
Comment (himanshukandwal) [reply helix-core/src/test/resources/MaintenanceRebalancer.ComputeNewIdealState.json]: Yes, updated. Thanks!

**Comment by himanshukandwal** [comment]
Successful CI Build: https://github.com/himanshukandwal/helix/actions/runs/8286133854

**Review by zpinto — APPROVED** [review]
LGTM

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/MaintenanceRebalancer.java (hunk 2 above)
Comment (desaikomal) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/MaintenanceRebalancer.java:70]: May be adding comment with details will be useful.

**Review by desaikomal — APPROVED** [review]
You should update the description or add comments:
1. We first sort on Preference List (does it have any special comparator?) 
2. We sort on StateModelDef

it would be useful to add comments.

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/MaintenanceRebalancer.java (hunk 2 above)
Comment (himanshukandwal) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/MaintenanceRebalancer.java:89]: Yes, updated code with an example as well. Thanks Komal!

**Comment by himanshukandwal** [comment]
> You should update the description or add comments:
> 
> 1. We first sort on Preference List (does it have any special comparator?)
> 2. We sort on StateModelDef
> 
> it would be useful to add comments.

Yes, updated the code with comments. Thanks Komal!

**Review by desaikomal — APPROVED** [review]

**Comment by himanshukandwal** [comment]
This change has been reviewed and approved by @zpinto and @desaikomal 

Final Commit Message:   Fixed PreferenceList Ordering Changes (indeterminism) during Maintenance Mode.
