### PR TITLE
fix TestCleanupExternalView.test 

### LINKED ISSUE #1458: fix TestCleanupExternalView.test
LOG 2901
>2020-10-10T05:38:01.4787071Z [ERROR] test(org.apache.helix.integration.TestCleanupExternalView)  Time elapsed: 1.462 s  <<< FAILURE!
2020-10-10T05:38:01.4894203Z java.lang.AssertionError: external-view for TestDB0 should be removed, but was: ZnRecord=TestDB0, {BUCKET_SIZE=0, IDEAL_STATE_MODE=AUTO, NUM_PARTITIONS=2, REBALANCE_MODE=SEMI_AUTO, REBALANCE_STRATEGY=DEFAULT, REPLICAS=2, STATE_MODEL_DEF_REF=MasterSlave, STATE_MODEL_FACTORY_NAME=DEFAULT}{TestDB0_0={localhost_12918=SLAVE, localhost_12919=MASTER}, TestDB0_1={localhost_12918=MASTER, localhost_12919=SLAVE}}{}, Stat=Stat {_version=6, _creationTime=1602305095151, _modifiedTime=1602305095369, _ephemeralOwner=0} expected:<true> but was:<false>
2020-10-10T05:38:01.4970061Z 	at org.apache.helix.integration.TestCleanupExternalView.test(TestCleanupExternalView.java:122)
2020-10-10T05:38:01.4972687Z 
2020-10-10T05:38:01.8976500Z [ERROR] Failures: 
2020-10-10T05:38:01.8991408Z [ERROR]   TestCleanupExternalView.test:122 external-view for TestDB0 should be removed, but was: ZnRecord=TestDB0, {BUCKET_SIZE=0, IDEAL_STATE_MODE=AUTO, NUM_PARTITIONS=2, REBALANCE_MODE=SEMI_AUTO, REBALANCE_STRATEGY=DEFAULT, REPLICAS=2, STATE_MODEL_DEF_REF=MasterSlave, STATE_MODEL_FACTORY_NAME=DEFAULT}{TestDB0_0={localhost_12918=SLAVE, localhost_12919=MASTER}, TestDB0_1={localhost_12918=MASTER, localhost_12919=SLAVE}}{}, Stat=Stat {_version=6, _creationTime=1602305095151, _modifiedTime=1602305095369, _ephemeralOwner=0} expected:<true> but was:<false>
2020-10-10T05:38:01.9001717Z [ERROR] Tests run: 1211, Failures: 1, Errors: 0, Skipped: 0
2020-10-10T05:38:01.9107617Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project helix-core: There are test failures.
2020-10-10T05:38:01.9110958Z [ERROR]

### PR DESCRIPTION
**Pull request by kaisun2000**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

fix #1458 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
Flaky test with 10 * 100ms. This may not be enough when there is
logging or Zk is slow in github. Fix with TestHelper.verify();

### Tests

- [ ] The following tests are written for this issue:

(List the names of added unit/integration tests)

- [x] The following is the result of the "mvn test" command on the appropriate module:

github run
### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/test/java/org/apache/helix/integration/TestCleanupExternalView.java [hunk 1]
```diff
@@ -109,18 +109,14 @@ public void test() throws Exception {
...
-    }
 
-    Assert.assertNull(externalView, "external-view for TestDB0 should be removed, but was: "
-        + externalView);
+    result = TestHelper.verify(() -> {
+      ExternalView externalView = accessor.getProperty(keyBuilder.externalView("TestDB0"));
+      return externalView == null;
+    }, TestHelper.WAIT_DURATION);
+
+    ExternalView ev = accessor.getProperty(keyBuilder.externalView("TestDB0"));
```
Comment (jiajunwang) [inline helix-core/src/test/java/org/apache/helix/integration/TestCleanupExternalView.java:118]: Why get it once more?

Comment (jiajunwang) [reply helix-core/src/test/java/org/apache/helix/integration/TestCleanupExternalView.java:118]: If it is just for the assert log, then you can do this,

ExternalView externalView = null;
result = TestHelper.verify(() -> {
  externalView = accessor.getProperty(keyBuilder.externalView("TestDB0"));
  return externalView == null;
}, TestHelper.WAIT_DURATION);
Assert.assertTrue(result, "external-view for TestDB0 should be removed, but was: " + externalView);

Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/integration/TestCleanupExternalView.java]: This way does not work. Lambda varable captured (externalView here) needs to be final. Changed it to use instance variable then.

File: helix-core/src/test/java/org/apache/helix/integration/TestCleanupExternalView.java [hunk 2]
```diff
@@ -42,6 +42,7 @@
  * orphan external-view
  */
 public class TestCleanupExternalView extends ZkUnitTestBase {
+  private ExternalView _externalView = null;
```
Comment (zhangmeng916) [inline helix-core/src/test/java/org/apache/helix/integration/TestCleanupExternalView.java:45]: nit: = null is not needed.

**Review by zhangmeng916 — APPROVED** [review]
LGTM

File: helix-core/src/test/java/org/apache/helix/integration/TestCleanupExternalView.java (hunk 1 above)
Comment (jiajunwang) [reply helix-core/src/test/java/org/apache/helix/integration/TestCleanupExternalView.java]: It certainly works. But it would be better to have a wrapper class (AtomicReference for example), to contain the result. The wrapper class can be final. Anyway, the goal is to ensure all test cases are independent of each other as far as we can.
Just a suggestion, the current logic is also fine : )

File: helix-core/src/test/java/org/apache/helix/integration/TestCleanupExternalView.java (hunk 2 above)
Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/integration/TestCleanupExternalView.java:45]: right. 
just to make sure this is explicit, namely in normal path this is expected to be null all the time.

**Comment by kaisun2000** [comment]
This diff is approved. Please help to merge

>Flaky test with 10 * 100ms. This may not be enough when there is
logging or Zk is slow in github. Fix with TestHelper.verify();
