### PR TITLE
Fix CustomRebalancer's assignment computation

### LINKED ISSUE #467: Make CustomRebalancer re-compute BestPossibleAssignment upon CurrentState and Message change
CustomRebalancer would cache the result of the previous best possible mapping and use it and skip the whole calculation step.

For the users of CustomRebalancer, this was causing the cluster to not converge intermittently. This is because the rebalancer should recompute the best possible mapping upon cluster change, but it was not doing so for changes like CurrentState and Message changes.

### PR DESCRIPTION
**Pull request by narendly**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #467 and #377 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

It was observed that sometimes CustomRebalancer would leave out an instance entirely if an instance is disabled or the partition on the instance was still bootstrapping (current state is null). This would cause a cluster not to converge. 

This diff fixes this by 1) still including an assignment from IdealState even though the current state is null (maybe due to a pending state transition) 2) putting disabled partitions in InitialState.

### Tests

- [x] The following tests are written for this issue:

**TestCustomRebalancer**

This problem was originally reported by Apache Pinot. **Ran the following test repeatedly several hundred times for 10+ hours without failure**.

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.313 sec - in **org.apache.pinot.controller.helix.ControllerInstanceToggleTest**
testInstanceToggle(org.apache.pinot.controller.helix.ControllerInstanceToggleTest)  Time elapsed: 7.004 sec
08:44:21.209 zk.zookeeper.ZkClient: (Thread 22) - zookeeper state changed (Disconnected)
08:44:21.209 zk.zookeeper.ZkClient: (Thread 22) - zookeeper state changed (Disconnected)
08:44:21.209 zk.zookeeper.ZkClient: (Thread 22) - zookeeper state changed (Disconnected)

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- jacoco-maven-plugin:0.7.7.201606060606:report-aggregate (report) @ pinot-controller ---
[INFO] Loading execution data file /home/hulee/mp/incubator-pinot/pinot-controller/target/jacoco.exec
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  28.132 s
[INFO] Finished at: 2019-09-12T08:44:24-07:00
[INFO] ------------------------------------------------------------------------

- [x] The following is the result of the "mvn test" command on the appropriate module:

[ERROR] testTagSetIncorrect(org.apache.helix.integration.TestAlertingRebalancerFailure)  Time elapsed: 180.085 s  <<< FAILURE!
java.lang.AssertionError: expected:<true> but was:<false>
	at org.apache.helix.integration.TestAlertingRebalancerFailure.checkResourceBestPossibleCalFailureState(TestAlertingRebalancerFailure.java:310)
	at org.apache.helix.integration.TestAlertingRebalancerFailure.testTagSetIncorrect(TestAlertingRebalancerFailure.java:174)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestAlertingRebalancerFailure.testTagSetIncorrect:174->checkResourceBestPossibleCalFailureState:310 expected:<true> but was:<false>
[INFO] 
[ERROR] Tests run: 854, Failures: 1, Errors: 0, Skipped: 1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  56:35 min
[INFO] Finished at: 2019-09-15T19:45:48-07:00
[INFO] ------------------------------------------------------------------------

[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.234 s - in org.apache.helix.integration.TestAlertingRebalancerFailure
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.046 s
[INFO] Finished at: 2019-09-15T23:08:35-07:00
[INFO] ------------------------------------------------------------------------

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- [x] My diff has been formatted using helix-style.xml

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/CustomRebalancer.java [hunk 1]
```diff
@@ -130,14 +130,17 @@ public ResourceAssignment computeBestPossiblePartitionState(ResourceControllerDa
...
-          currentStateMap == null || currentStateMap.get(instance) == null
-              || !currentStateMap.get(instance).equals(HelixDefinedState.ERROR.toString());
-
+      boolean notInErrorState = currentStateMap != null
+          && !HelixDefinedState.ERROR.toString().equals(currentStateMap.get(instance));
       boolean enabled = !disabledInstancesForPartition.contains(instance) && isResourceEnabled;
 
-      if (liveInstancesMap.containsKey(instance) && notInErrorState && enabled) {
-        instanceStateMap.put(instance, idealStateMap.get(instance));
+      if (liveInstancesMap.containsKey(instance) && notInErrorState) {
```
Comment (lei-xia) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/CustomRebalancer.java]: One more things, even an instance is not live, we should put the bestpossible as OFFLINE too, right?  The current code will remove it from BestPossible.

Comment (narendly) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/CustomRebalancer.java]: @lei-xia I am not sure. If an instance is not live, we won't be sending it a message anyways. So there's no point in including it in the best possible mapping.

Suppose that instance comes back online later, then that would be a liveInstance change, which would require the cache to be invalidated, forcing the rebalancer to recompute the assignment. 

So it's okay to not include it in the best possible mapping here.

**Comment by narendly** [comment]
@lei-xia Unit test added: TestCustomRebalancer.

**Comment by narendly** [comment]
This PR is ready to be merged, approved by @lei-xia
