### PR TITLE
Fix redundant workflow context updates for finished workflows

### LINKED ISSUE #1582: Workflow context is written to ZK even if workflow is finished
### Describe the bug
Currently in the task framework, even when the workflow is finished, the controller updates the workflow context in each pipeline

### To Reproduce
Have a finished workflow and start another one. Then the old workflow context version will increase in each pipeline.

### Expected behavior
Remove these redundant writes.

### PR DESCRIPTION
**Pull request by alirezazamani**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:
Fixes #1582 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
If the workflow has been finished before, there is no need to update the workflow context.
In this PR, this behavior has been fixed and optimized.

### Tests

- [x] The following tests are written for this issue:
TestContextRedundantUpdates
More test will be added to this file as we move toward reducing context writes

- [x] The following is the result of the "mvn test" command on the appropriate module:
Helix-core:
```
[INFO] Tests run: 1253, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5,396.908 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1253, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:30 h
[INFO] Finished at: 2020-12-09T00:16:20-08:00
[INFO] ------------------------------------------------------------------------
```
The failed test is unrelated to this change and is failing even without this PR.

Helix-rest:
```
[INFO] Tests run: 171, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 103.579 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 171, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:49 min
[INFO] Finished at: 2020-12-09T09:28:35-08:00
[INFO] ------------------------------------------------------------------------
```

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/task/WorkflowDispatcher.java [hunk 1]
```diff
@@ -217,7 +217,6 @@ public void assignWorkflow(String workflow, WorkflowConfig workflowCfg,
     } else {
       LOG.debug("Workflow {} is not ready to be scheduled.", workflow);
     }
-    _clusterDataCache.updateWorkflowContext(workflow, workflowCtx);
```
Comment (alirezazamani) [inline helix-core/src/main/java/org/apache/helix/task/WorkflowDispatcher.java:220]: This update is not necessary. When there is a job that needs to be scheduled, we update the workflow context there. If there is no job, then we do not need to update the workflow context

File: helix-core/src/test/java/org/apache/helix/integration/task/TestContextRedundantUpdates.java [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+import org.apache.helix.task.TaskUtil;
+import org.apache.helix.task.Workflow;
+import org.testng.Assert;
+import org.testng.annotations.BeforeClass;
+import org.testng.annotations.Test;
+
+/**
+ * This test checks of the workflow and job context get updates only if the update is necessary
+ */
+public class TestContextRedundantUpdates extends TaskTestBase {
```
Comment (alirezazamani) [inline helix-core/src/test/java/org/apache/helix/integration/task/TestContextRedundantUpdates.java:35]: More test will be added to this file as we move toward reducing context writes

**Review by jiajunwang — APPROVED** [review]

**Comment by alirezazamani** [comment]
This PR is ready to be merged.

Final commit message:
Fix redundant workflow context updates for finished workflows

If the workflow has been finished, there is no need to update the workflow context.
In this commit, this behavior has been fixed and optimized.
