### PR TITLE
Fix TestDropResourceMetricsReset

### LINKED ISSUE #1980: [Failed CI Test] testDropWithNoCurrentState(org.apache.helix.monitoring.mbeans.TestDropResourceMetricsReset)
This issue is created for tracking unstable test: testDropWithNoCurrentState(org.apache.helix.monitoring.mbeans.TestDropResourceMetricsReset)

### PR DESCRIPTION
**Pull request by qqu0127**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:
Fixes #1980 

#### Overview

Fix failing test TestDropResourceMetricsReset

A recent ZK version bump reveals a seemingly long-hidden code issue regarding resource metrics. It's possible the test never works in the expected way. 

#### What
Is it a faulty test or a code issue we should fix?
-- More ideas welcome! 
As of now we believe it's a code issue and need a fix, please also see https://github.com/apache/helix/pull/2011#issuecomment-1087807581

#### Why
The test failure could be reproduced stably using **either ZK version** by adding Thread.sleep() between `participant.syncStop()` and `setupTool.dropResourceFromCluster`. So this indicates the test was wrong (and succeeded in a wrong way) for a while, there are race condition and zk version change introduce unrelated delay that finally reveal the issue.

mBean is only unregistered during ExternalViewComputeStage in https://github.com/apache/helix/blob/master/helix-core/src/main/java/org/apache/helix/controller/stages/ExternalViewComputeStage.java#L99.
 It's not always happening after the resource is dropped as there is no `CurrentStateChange` event anymore, only `IdealStateChange`. 

#### How

Fixing the issue itself requires more changes and careful design. We'd want to first put a temp workaround for the test case by manually triggering a cluster event.

### Tests

- [ ] The following tests are written for this issue:

(List the names of added unit/integration tests)

- The following is the result of the "mvn test" command on the appropriate module:

(If CI test fails due to known issue, please specify the issue and test PR locally. Then copy & paste the result of "mvn test" to here.)

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/controller/GenericHelixController.java [hunk 1]
```diff
@@ -552,7 +552,7 @@ private static PipelineRegistry createDefaultRegistry(String pipelineName) {
       autoExitMaintenancePipeline.addStage(new MaintenanceRecoveryStage());
 
       registry.register(ClusterEventType.IdealStateChange, dataRefresh, dataPreprocess,
-          rebalancePipeline);
+          externalViewPipeline, rebalancePipeline);
```
Comment (desaikomal) [inline helix-core/src/main/java/org/apache/helix/controller/GenericHelixController.java:555]: It is non-deterministic test which we all agree as test is not failing consistently in CI. Just curious, changing the code is the right behavior or should mock<> implementation of controller needs to change??

**Review by desaikomal — COMMENTED** [review]
Thanks a lot Quincy for taking a look at the failure (Appreciate a lot)

File: helix-core/src/main/java/org/apache/helix/controller/GenericHelixController.java (hunk 1 above)
Comment (qqu0127) [reply helix-core/src/main/java/org/apache/helix/controller/GenericHelixController.java:555]: Right now I doubt the non-deterministic part, like, what if we have `setupTool.dropResourceFromCluster` long enough after `participant.syncStop()`, will the test still pass occasionally? I documented something in description regarding ExternalViewComputeStage.
This is a good topic for discussion, we need to review and define the expected behavior. If the test is describing the right behavior, then it's a bug in code we need to fix.

**Comment by qqu0127** [comment]
The attempted fix caused another test failure in `TestClusterMaintenanceMode.testMaintenanceModeAddNewResource`, where it checks the external view of resource added when cluster is in maintenance mode.

File: helix-core/src/main/java/org/apache/helix/controller/stages/ExternalViewComputeStage.java [hunk 2]
```diff
@@ -96,7 +96,7 @@ public void execute(final ClusterEvent event) throws Exception {
 
     // Keep MBeans for existing resources and unregister MBeans for dropped resources
     if (clusterStatusMonitor != null) {
-      clusterStatusMonitor.retainResourceMonitor(monitoringResources);
+      //clusterStatusMonitor.retainResourceMonitor(monitoringResources);
```
Comment (narendly) [inline helix-core/src/main/java/org/apache/helix/controller/stages/ExternalViewComputeStage.java:99]: First off, great work on debugging this and identifying the root cause!

Have a few points to add:

- First, with a guiding question: conceptually, where would be the "correct" place for metric-cleanup logic to be? 
- We want the metric cleanup logic to be in an async stage in order to not block the critical controller pipeline. As such, adding the metric-cleanup logic in ResourceValidation may not be appropriate (this is not an async stage). If you believe that this logic shouldn't belong in ExternalViewComputeStage, then can we think about a different (or a new) async stage where this logic can be appropriately placed? With that said though, if you place it in another async stage, would we still face the same issue of this logic not triggering in tests?
- If you think ExternalViewComputeStage is an appropriate place for this cleanup logic, can we simply add a CurrentState change event to artificially trigger the stage just for the sake of making the test case work? I think this is also a valid way because in real-life scenarios we can rely on the ExtViewComputeStage to eventually get called asynchronously. We can think of this as making the test environment model the real environment more closely.

**Comment by qqu0127** [comment]
Adding more ideas and discussion from offline regarding the fundamental problem statement:

- @qqu0127 : I’d like to first check with you, do you agree if it’s a code issue we need to fix? (compared to disabling / removing the test). I’m debating myself with another argument like -- it is there for a long time, it seems not hurting anything and almost a feature.
- @narendly : Short answer is that I do think we need to have coverage of this ... We have had issues for Helix where metrics were never properly cleaned up and caused JVM heap OOM issues

File: helix-core/src/main/java/org/apache/helix/controller/stages/ExternalViewComputeStage.java (hunk 2 above)
Comment (qqu0127) [reply helix-core/src/main/java/org/apache/helix/controller/stages/ExternalViewComputeStage.java:99]: Thanks for the comment!

> where would be the "correct" place for metric-cleanup logic to be?

With limited context and knowledge, I think both `ResourceValidationStage` and `ExternalViewComputeStage` make sense. MetricsMonitors belong to, or at least associated with resources. On the other hand, generally speaking, it's also a "view". 
it's also applicable to be in a standalone stage instead of mixing up with other logic.

> async stage...

Yeah, this is a good point I wasn't aware of. So essentially, we'd want to run it in async way, and make sure all related cluster events trigger such computation. 

> add a CurrentState change event to artificially trigger the stage

This is definitely an option for the fix. But could it introduce more overhead and side effect? And what the difference from adding `externalViewPipeline` to `IdealStateChange` registry? All we need is refresh the resource monitors, but we will be running a few other pipelines.

**Comment by qqu0127** [comment]
The failing test `testBatchMessageThreadPoolSize` is a known issue in https://github.com/apache/helix/issues/1989

File: helix-core/src/test/java/org/apache/helix/monitoring/mbeans/TestDropResourceMetricsReset.java [hunk 3]
```diff
@@ -148,6 +148,10 @@ public void testDropWithNoCurrentState() throws Exception {
     // Drop the resource
     setupTool.dropResourceFromCluster(clusterName, RESOURCE_NAME);
 
+    // TEMP WORKAROUND, trigger a CurrentStateChange to remove the resource monitor
+    // https://github.com/apache/helix/issues/1980
+    participant.syncStart();
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/monitoring/mbeans/TestDropResourceMetricsReset.java:153]: could we give a little more context? (e.g. adding a liveinstance has an effect of creating a CurrentStageChange event, **which in turn triggers ExternalViewStage that includes the metric cleanup logic**)

also, should we stop this participant when we clean up (line 159 and beyond)? otherwise, it will leave a dangling thread.

Comment (qqu0127) [reply helix-core/src/test/java/org/apache/helix/monitoring/mbeans/TestDropResourceMetricsReset.java]: Good point, updated. Thanks.

**Review by junkaixue — APPROVED** [review]

**Review by narendly — APPROVED** [review]
Thanks for a thorough root cause analysis! Hope you got a good look at some Helix internals through this :)

**Comment by qqu0127** [comment]
This PR is ready to merge, approved by @junkaixue @narendly 
Commit message:

Fix TestDropResourceMetricsReset
Add a temp workaround by manually triggering a CurrentStageChange event for ExternalViewStage computation so that resource monitor can be cleaned up in unit test.
