### PR TITLE
Fix flaky tests org.apache.helix.rest.metadatastore.TestZkMetadataStoreDirectory (#2645)

### LINKED ISSUE #2645: flaky test assertions in org.apache.helix.rest.metadatastore.TestZkMetadataStoreDirectory
### Describe the bug
The test assertions in org.apache.helix.rest.metadatastore.TestZkMetadataStoreDirectory#testGetAllMetadataStoreRealms and org.apache.helix.rest.metadatastore.TestZkMetadataStoreDirectory#testGetAllShardingKeys are flaky. 
These tests compare two sets for containing the same elements in the same order – but it is not deterministic in which order the elements are returned from a set – resulting in a flaky test.

### To Reproduce
run:
```shell
mvn -pl helix-rest edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.helix.rest.metadatastore.TestZkMetadataStoreDirectory
``` 

### Expected behavior
Test should not be flaky – it should pass or fail (in the current case it should pass)

### Additional context
non

### PR DESCRIPTION
**Pull request by hofi1**
## Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #2645

## Description

Sets return the elements in a non-deterministic order, which means that this assertion is not correct, because it checks whether the collections contain the same elements in the same order. This leads to a flack test. To fix this problem, the assertion has been rewritten to check if the collections contain the same amount of elements as well as booth collections contain all values of the other collection.

Tests that cause problems: 

https://github.com/apache/helix/blob/5f1a3f716ec71178f2f1f98c2ef48c62d6285df5/helix-rest/src/test/java/org/apache/helix/rest/metadatastore/TestZkMetadataStoreDirectory.java#L133-L141

and 
https://github.com/apache/helix/blob/5f1a3f716ec71178f2f1f98c2ef48c62d6285df5/helix-rest/src/test/java/org/apache/helix/rest/metadatastore/TestZkMetadataStoreDirectory.java#L144-L152

This problem was found by the [NonDex](https://github.com/TestingResearchIllinois/NonDex) Engine – to reproduce run
```shell
mvn -pl helix-rest edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.helix.rest.metadatastore.TestZkMetadataStoreDirectory
``` 

## Solution
Replace the assertions with a custom matcher, which checks if the sets contain the same elements without taking care of the order of the elements returned by the set. 

Custom Matcher:

https://github.com/apache/helix/blob/9cd4181fe361ee2015e3e8fd507e158a2eb78991/helix-rest/src/test/java/org/apache/helix/rest/metadatastore/TestZkMetadataStoreDirectory.java#L378-L383

## Tests

No test have been written – one existing test has been updated.

- The following is the result of the "mvn test" command on the appropriate module:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:51 min
[INFO] Finished at: 2023-10-04T23:16:04-05:00
[INFO] ------------------------------------------------------------------------

### CODE REVIEW

File: helix-rest/src/test/java/org/apache/helix/rest/metadatastore/TestZkMetadataStoreDirectory.java [hunk 1]
```diff
@@ -375,4 +375,10 @@ private void clearRoutingData() throws Exception {
       return true;
     }, TestHelper.WAIT_DURATION), "Routing data path should be deleted after the tests.");
   }
+  private void assertCollectionsContainSameElementsIgnoringOrder(Collection<String> collection1,
+   Collection<String> collection2) {
+     Assert.assertEquals(collection2.size(), collection1.size());
+     Assert.assertTrue(collection2.containsAll(collection1));
+     Assert.assertTrue(collection1.containsAll(collection2));
+  }
```
Comment (junkaixue) [inline helix-rest/src/test/java/org/apache/helix/rest/metadatastore/TestZkMetadataStoreDirectory.java:383]: Would be good to have it in the abstractestclass to be a common used method.

**Comment by junkaixue** [comment]
Since no update for a couple of days. I think it is OK to just fix this and move forward.
