### PR TITLE
Fix tests in apache/zooscalability and rebase from apache/master

### LINKED ISSUE #786: Fix failing tests on helix-rest in metadata store directory module
There are some failing tests due to environment issues.

### PR DESCRIPTION
**Pull request by narendly**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #786 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

There are some failing tests due to environment issues. This PR fixes them by enforcing a deterministic order among tests.
This PR also rebases apache/zooscalability from apache/master.

### Tests

- [x] The following is the result of the "mvn test" command on the appropriate module:

[INFO] Tests run: 123, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 22.476 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 123, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  51.287 s
[INFO] Finished at: 2020-02-20T13:27:27-08:00
[INFO] -------------------------------------------------

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- [x] My diff has been formatted using helix-style.xml

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/task/TaskUtil.java [hunk 1]
```diff
@@ -1043,23 +1043,40 @@ public static void purgeExpiredJobs(String workflow, WorkflowConfig workflowConf
...
+    Set<String> existingContexts;
+    /*
+     * Here try-catch is used to avoid concurrent modification exception while doing deep copy.
+     * Map.keySet() can produce concurrent modification exception.
+     * Reason: If the map is modified while an iteration over the set is in progress, concurrent
+     * modification exception will be thrown.
+     */
+    try {
+      existingContexts = new HashSet<>(dataProvider.getContexts().keySet());
+    } catch (Exception e) {
```
Comment (pkuwm) [inline helix-core/src/main/java/org/apache/helix/task/TaskUtil.java]: If we are catching concurrent modification exception, I think it is better to just catch this exception, instead of the general Exception.

Comment (narendly) [reply helix-core/src/main/java/org/apache/helix/task/TaskUtil.java]: Please create a separate issue tracking that item. In my opinion, catching ConcurrentModificationException is awkward and I personally prefer catching a general Exception.
