### PR TITLE
Fix conflicting MonitorDomainNames in metrics-common and helix-core

### LINKED ISSUE #1022: Duplicate and Conflicting Class MonitorDomainNames
### Issue

We realized that there are two MonitorDomainNames classes in modules: helix-core and metrics-common. The one in metrics-common is old and missing a field Rebalancer. This would cause errors and failure for customers' running if the old class is being used in runtime: `java.lang.NoSuchFieldError: Rebalancer`

### Stacktrace
```
java.lang.RuntimeException: java.lang.NoSuchFieldError: Rebalancer
...
Caused by: java.lang.NoSuchFieldError: Rebalancer
        at org.apache.helix.InstanceType.<clinit>(InstanceType.java:39)
```

### Solution
Update the class MonitorDomainNames in metrics-common and remove the duplicate one in helix-core.

### PR DESCRIPTION
**Pull request by pkuwm**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1022 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

We realized that there are two MonitorDomainNames classes in modules: helix-core and metrics-common. The one in metrics-common is old and missing a field Rebalancer. This would cause RuntimeException error and failure for customers' running if the old class is being used in runtime: `java.lang.NoSuchFieldError: Rebalancer`

This PR updates the class MonitorDomainNames in metrics-common and removes the duplicate one in helix-core.

### Tests

- [ ] The following tests are written for this issue:

NA

- [x] The following is the result of the "mvn test" command on the appropriate module:

```
helix-core

[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   TestRecurringJobQueue.testDeletingRecurrentQueueWithHistory:296 expected:<true> but was:<false>
[ERROR]   TestWorkflowTermination.testWorkflowPausedTimeout:170->verifyWorkflowCleanup:257 expected:<true> but was:<false>
[ERROR]   TestAssignableInstanceManager.testGetAssignableInstanceMap:115 expected:<true> but was:<false>
[INFO]
[ERROR] Tests run: 1146, Failures: 3, Errors: 0, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:19 h
[INFO] Finished at: 2020-05-22T13:46:21-07:00
[INFO] ------------------------------------------------------------------------


[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 104.805 s - in org.apache.helix.integration.task.TestRecurringJobQueue
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------


[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 36.447 s - in org.apache.helix.integration.task.TestWorkflowTermination
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------


[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.345 s - in org.apache.helix.task.TestAssignableInstanceManager
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------


Module zookeeper-api

[INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.825 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------


helix-rest

[INFO] Tests run: 159, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 44.578 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 159, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

```

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation (Optional)

- [ ] In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Code Quality

- [x] My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/monitoring/mbeans/MonitorDomainNames.java [hunk 1]
```diff
@@ -1,33 +0,0 @@
...
- * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
- * KIND, either express or implied.  See the License for the
- * specific language governing permissions and limitations
- * under the License.
- */
-
-/**
- * This enum defines all of domain names used with various Helix monitor mbeans.
- */
-public enum MonitorDomainNames {
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/monitoring/mbeans/MonitorDomainNames.java:25]: Is this a backward compatibility violation?

I think we need a more complete solution to ensure backward compatibility, or we just finish the full migration.

Comment (pkuwm) [reply helix-core/src/main/java/org/apache/helix/monitoring/mbeans/MonitorDomainNames.java:25]: The key point is, both classes are packaged in `org.apache.helix.monitoring.mbeans`, so I think it is backward compatible. Although this class is public, client's code doesn't have to change the import. Helix-core.jar depends on helix-common.jar and metrics-common.jar, so it is OK to remove this class in helix-core, as long as we have it in the same package.

Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/monitoring/mbeans/MonitorDomainNames.java:25]: You are right. I missed the package path.
Since they are the same, it would be fine.

**Comment by pkuwm** [comment]
This PR is ready to be merged, approved by @jiajunwang @narendly 

Commit message
```
There are two MonitorDomainNames classes in modules: helix-core and metrics-common. The one in metrics-common misses a field Rebalancer and would cause RuntimeException error and failure for customers' running if the old class is being used in runtime: java.lang.NoSuchFieldError: Rebalancer.

This commit fixes this issue by updating the class MonitorDomainNames in metrics-common and removing the duplicate one in helix-core
```
