### PR TITLE
The fix for assigning partitions when instance weight = 0

### LINKED ISSUE #368: Set instance_weight = 0 in config doesn't mean no partition assigned to the instance
**Problem**
The issue is raised by our internal client who sets the instance_weight = 0 in instance/config. Instead of expecting zero partitions assigned to it, based on our Helix controller algorithm, there's still a good chance some partitions assigned to the instance.

**Code of issue**
After investigation, the issue was due to the current CardDealingAlgorithm. It treats instance weight as a comparator factor or preference, rather than respecting the weight = 0. 
> https://github.com/apache/helix/blob/d5bf3ad410e0a54b1e79d9570d3e7897c0e2c947/helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/CardDealingAdjustmentAlgorithmV2.java

**Solution** 
There's no way to strictly follow all the weight setting of instances now. Because the algorithm is not designed for the purpose. But for the extreme case of instance weight = 0, the current workaround solution is add a simple check to skip the assignment of the instance.

### PR DESCRIPTION
**Pull request by i3wangyi**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR title:

(fix #368  - Link your issue number here)

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

(Write a concise description including what, why, how)

- Added the unit test to cover the existing assignment calculations
- Added the fix to skip assignment when instance weight == 0
- Allow the partitions originally assigned to an instance of weight = 0, re-assigned to other instances if other fault zones if space allowed.

### Tests

- [x] The following tests are written for this issue:

TestCardDealingAdjustmentAlgorithmV2

- [x] The following is the result of the "mvn test" command on the appropriate module:

[INFO] Running TestSuite
Start zookeeper at localhost:2183 in thread main
[ERROR] Tests run: 2853, Failures: 1, Errors: 0, Skipped: 2852, Time elapsed: 258.074 s <<< FAILURE! - in TestSuite
[ERROR] beforeSuite(org.apache.helix.integration.paticipant.TestRestartParticipant)  Time elapsed: 3.286 s  <<< FAILURE!
java.lang.IllegalStateException: Zookeeper port 2183 was already in use. Running in single machine mode?

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   TestRestartParticipant>ZkTestBase.beforeSuite:126 » IllegalState Zookeeper por...
[INFO]
[ERROR] Tests run: 2109, Failures: 1, Errors: 0, Skipped: 2108

The single failure test method is passed locally in IDE

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Code Quality

- [x] My diff has been formatted using helix-style.xml

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/CardDealingAdjustmentAlgorithmV2.java [hunk 1]
```diff
@@ -55,6 +55,26 @@ public CardDealingAdjustmentAlgorithmV2(Topology topology, int replica, Mode mod
     }
   }
 
+  public Map<Node, Node> getInstanceFaultZone() {
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/CardDealingAdjustmentAlgorithmV2.java]: No need to use public if these methods are just for testing?

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/topology/Node.java [hunk 2]
```diff
@@ -36,6 +36,11 @@
 
   public Node() { }
 
+  public Node(String name, long id) {
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/topology/Node.java]: Shall we just have a complete constructor? This one only has part of the fields initialized.

**Comment by narendly** [comment]
Please follow https://github.com/apache/helix/wiki/Pull-Request-Template

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/CardDealingAdjustmentAlgorithmV2.java [hunk 3]
```diff
@@ -193,9 +213,7 @@ public int compare(Node node1, Node node2) {
         List<String> partitions = assignmentMap.containsKey(instance) ?
             assignmentMap.get(instance) :
             new ArrayList<String>();
-        int space =
-            (int) (Math.floor(targetPartitionCount.get(instance))) + targetAdjustment - partitions
-                .size();
+        int space = instance.getWeight() <= 0 ? 0: (int) (Math.floor(targetPartitionCount.get(instance))) + targetAdjustment - partitions.size();
```
Comment (pkuwm) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/CardDealingAdjustmentAlgorithmV2.java]: Format the style before `:`?

File: helix-core/src/test/java/org/apache/helix/controller/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java [hunk 4]
```diff
@@ -0,0 +1,329 @@
+package org.apache.helix.controller.strategy.crushMapping;
```
Comment (pkuwm) [inline helix-core/src/test/java/org/apache/helix/controller/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java]: Add the apache license?

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/CardDealingAdjustmentAlgorithmV2.java [hunk 5]
```diff
@@ -55,6 +55,26 @@ public CardDealingAdjustmentAlgorithmV2(Topology topology, int replica, Mode mod
...
+
+  public Map<Node, Long> getInstanceWeight() {
+    return _instanceWeight;
+  }
+
+  public long getTotalWeight() {
+    return _totalWeight;
+  }
+
+  public Map<Node, Long> getFaultZoneWeight() {
```
Comment (lei-xia) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/CardDealingAdjustmentAlgorithmV2.java]: Add methods into a class just for testing is not quite recommended.  If you have to do that, setting fields to protected are a bit better than adding more codes here?

Comment (i3wangyi) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/CardDealingAdjustmentAlgorithmV2.java]: Making it `protected` field won't make it better. `protected` is not designed for unit testing purpose but for inheritance and it exposes the internal field directly. I could make the methods package private so these methods won't be misused publicly

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/topology/Node.java (hunk 2 above)
Comment (i3wangyi) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/topology/Node.java]: That's the problem of using not final field, I don't know what are must-have fields which are set later. Given we have all set methods for the rest of fields, I'm not making it worse by only selecting interesting fields.

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/CardDealingAdjustmentAlgorithmV2.java [hunk 6]
```diff
@@ -55,6 +74,27 @@ public CardDealingAdjustmentAlgorithmV2(Topology topology, int replica, Mode mod
     }
   }
 
+  // expose internal fields only for testing purpose
```
Comment (narendly) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/CardDealingAdjustmentAlgorithmV2.java]: As I mentioned in another PR, one trick you can use is to create a MockCardDealingAdjustmentAlgorithmV2 that extends this class and that contains these methods. That way you should be able to access all protected fields, and use the mock class for unit testing.

File: helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java [hunk 7]
```diff
@@ -0,0 +1,328 @@
...
+      {7, 8, 9}  // zone0: i7, i8, i9
+  };
+
+  @BeforeClass
+  public void setUpTopology() {
+    _topology = mock(Topology.class);
+    when(_topology.getFaultZones()).thenReturn(createFaultZones(_defaultFaultZones));
+  }
+
+  @Test(description = "Verify a few properties after algorithm instance is created")
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java]: I like how you consistently add the description. Here, though, could you add a few lines on what properties are tested?

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/topology/Node.java (hunk 2 above)
Comment (narendly) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/topology/Node.java]: I think this is a minor point. Alternatively, you could just use the empty constructor and call set methods but either way I think would work?

File: helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java [hunk 8]
```diff
@@ -0,0 +1,328 @@
...
+
+  private List<Node> createFaultZones(int[][] instancesMap) {
+    List<Node> faultZones = new ArrayList<>();
+    int zoneId = 0;
+    for (int[] instances : instancesMap) {
+      Node zoneNode = new Node("zone" + zoneId, zoneId++);
+      int weight = 0;
+      for (int instanceId : instances) {
+        Node instanceNode = new InstanceNode(new Node("instance" + instanceId, instanceId), "instance" + instanceId);
+        instanceNode.addWeight(instanceId);
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java]: Just curious, is there a reason you're using instanceId as the node weight?

File: helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java [hunk 9]
```diff
@@ -0,0 +1,328 @@
...
+    long sum = 0;
+    for (long weight : faultZoneWeights.values()) {
+      sum += weight;
+    }
+    // verify total weight is computed correct
+    if (sum != algorithm.getTotalWeight()) {
+      Assert.fail(String.format("total weight %s != total weight of zones %s", algorithm.getTotalWeight(), sum));
+    }
+    Map<Node, Node> instanceFaultZone = algorithm.getInstanceFaultZone();
+    Assert.assertEquals(instanceFaultZone.size(), 9);
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java]: Magic number 9! Let's make this a constant: `NUM_INSTANCES`.

File: helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java [hunk 10]
```diff
@@ -0,0 +1,328 @@
...
+
+    // verify zone mapping is correct
+    for (Node zone : faultZones) {
+      long zoneId = zone.getId();
+      Set<Long> instanceIds = ImmutableSet.of(3 * zoneId + 1L, 3 * zoneId + 2L, 3 * zoneId + 3L);
+      List<Node> instanceNodes = zone.getChildren();
+      Assert.assertEquals(instanceNodes.size(), 3);
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java]: Magic number -> constant

File: helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java [hunk 11]
```diff
@@ -0,0 +1,328 @@
...
+      Assert.fail(
+          String.format("Total movements: %s != expected %s, replica: %s", totalMovements, expected.get(replica),
+              replica));
+    }
+  }
+
+  @Test(description = "Test performance given different preference (evenness or less movements)")
+  public void testComputeMappingForDifferentPreference() {
+    CardDealingAdjustmentAlgorithmV2 algorithm1 =
+        new CardDealingAdjustmentAlgorithmV2(_topology, 3, CardDealingAdjustmentAlgorithmV2.Mode.EVENNESS);
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java]: Magic number -> constant

File: helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java [hunk 12]
```diff
@@ -0,0 +1,328 @@
...
+    CardDealingAdjustmentAlgorithmV2 algorithm2 =
+        new CardDealingAdjustmentAlgorithmV2(_topology, 3, CardDealingAdjustmentAlgorithmV2.Mode.MINIMIZE_MOVEMENT);
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java]: Magic number -> constant

File: helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java [hunk 13]
```diff
@@ -0,0 +1,328 @@
...
+      int end = start + (int) instanceNode.getWeight();
+      nodeToPartitions.put(instanceNode, createDummyPartitions(start, end));
+    }
+    Map<Long, Set<String>> oldSimpleMapping = getSimpleMapping(nodeToPartitions);
+    // deep clone the original mapping
+    Map<Node, List<String>> newMapping = new HashMap<>();
+    for (Map.Entry<Node, List<String>> entry : nodeToPartitions.entrySet()) {
+      newMapping.put(entry.getKey(), new ArrayList<>(entry.getValue()));
+    }
+    boolean isAllAssigned1 = algorithm1.computeMapping(nodeToPartitions, 10);
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java]: Magic number -> constant

File: helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java [hunk 14]
```diff
@@ -0,0 +1,328 @@
...
+    boolean isAllAssigned2 = algorithm2.computeMapping(newMapping, 10);
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java]: Magic number -> constant

File: helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java [hunk 15]
```diff
@@ -0,0 +1,328 @@
...
+
+    CardDealingAdjustmentAlgorithmV2 algorithm =
+        new CardDealingAdjustmentAlgorithmV2(_topology, 1, CardDealingAdjustmentAlgorithmV2.Mode.EVENNESS);
+    Set<Node> instanceNodes = algorithm.getInstanceFaultZone().keySet();
+    Map<Node, List<String>> nodeToPartitions = new HashMap<>();
+    for (Node instanceNode : instanceNodes) {
+      nodeToPartitions.put(instanceNode, createDummyPartitions(0, 2)); // assign 2 partitions to each instance
+    }
+    Map<Long, Set<String>> oldSimpleMapping = getSimpleMapping(nodeToPartitions);
+    boolean isAssigned = algorithm.computeMapping(nodeToPartitions, 100);
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java]: Why does the random seed change to 100 here? 
Magic number -> constant

**Comment by jiajunwang** [comment]
I just notice the title, this is not a workaround. Please remove this to avoid confusion.

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/CardDealingAdjustmentAlgorithmV2.java (hunk 6 above)
Comment (lei-xia) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/crushMapping/CardDealingAdjustmentAlgorithmV2.java]: +1 on Hunter's suggestion, that will minimize the production code.

File: helix-core/src/test/java/org/apache/helix/controller/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java (hunk 4 above)
Comment (narendly) [reply helix-core/src/test/java/org/apache/helix/controller/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java]: Was the license added?

Comment (i3wangyi) [reply helix-core/src/test/java/org/apache/helix/controller/strategy/crushMapping/TestCardDealingAdjustmentAlgorithmV2.java]: Just added, thanks for catching it!

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/AbstractEvenDistributionRebalanceStrategy.java [hunk 16]
```diff
@@ -82,7 +85,23 @@ public void init(String resourceName, final List<String> partitions,
...
+        getNonEmptyWeightNodes(allNodes, clusterData.getInstanceConfigMap()),
+        getNonEmptyWeightNodes(liveNodes, clusterData.getInstanceConfigMap()), currentMapping,
+        clusterData);
+  }
+
+  private List<String> getNonEmptyWeightNodes(List<String> nodes, Map<String, InstanceConfig> instanceConfigMap) {
+    if (instanceConfigMap == null) {
+      return nodes;
+    }
+    return nodes.stream().filter(node -> instanceConfigMap.get(node).getWeight() != 0).collect(Collectors.toList());
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/AbstractEvenDistributionRebalanceStrategy.java]: What if instance config map does not contain the instance name? This filter will throw NPE.

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/AbstractEvenDistributionRebalanceStrategy.java [hunk 17]
```diff
@@ -82,7 +85,23 @@ public void init(String resourceName, final List<String> partitions,
   @Override
   public ZNRecord computePartitionAssignment(final List<String> allNodes,
       final List<String> liveNodes, final Map<String, Map<String, String>> currentMapping,
-      ResourceControllerDataProvider clusterData) throws HelixException {
+      ResourceControllerDataProvider clusterData) {
+    // only compute assignments for instances with available spaces
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/AbstractEvenDistributionRebalanceStrategy.java]: Note that instance weight != available space. Just say filtering out all the instances with zero weight.

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/AbstractEvenDistributionRebalanceStrategy.java [hunk 18]
```diff
@@ -82,7 +85,23 @@ public void init(String resourceName, final List<String> partitions,
...
+    return computeBestPartitionAssignment(
+        getNonEmptyWeightNodes(allNodes, clusterData.getInstanceConfigMap()),
+        getNonEmptyWeightNodes(liveNodes, clusterData.getInstanceConfigMap()), currentMapping,
+        clusterData);
+  }
+
+  private List<String> getNonEmptyWeightNodes(List<String> nodes, Map<String, InstanceConfig> instanceConfigMap) {
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/AbstractEvenDistributionRebalanceStrategy.java]: How about just call it getNonZeroWeightNodes()

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/topology/Topology.java [hunk 19]
```diff
@@ -28,6 +28,7 @@
 import java.util.List;
 import java.util.Map;
 import java.util.Set;
+import java.util.stream.Collectors;
```
[the remark this answers is not in the document]
Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/topology/Topology.java]: Is this one used? Please comment, @i3wangyi

[the remark this answers is not in the document]
Comment (i3wangyi) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/topology/Topology.java]: confirmed. It's an unused import

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/AbstractEvenDistributionRebalanceStrategy.java (hunk 16 above)
Comment (i3wangyi) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/AbstractEvenDistributionRebalanceStrategy.java]: Added the check, it will throw HelixException if no instance config found.

Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/AbstractEvenDistributionRebalanceStrategy.java]: Note that there is no guarantee the all node list will contain all live nodes. So what you checked will not pretect liveNodes. In my opinion, we just check and throw Exception in getNonZeroWeightNodes.

Comment (i3wangyi) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/AbstractEvenDistributionRebalanceStrategy.java]: I've noticed the strange behavior in local testing. By reading the code, allNodes means all the instances. They should include the liveNodes as subset. I don't know which part of helix is messing up the things. If it errors out due to the exception, it is also true that some resource of weight = 0 instance could stick there why the rebalancer failed to compute the new ideal mapping.

Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/AbstractEvenDistributionRebalanceStrategy.java]: allNodes means all the nodes with instance config. There is no guarantee a live instance has the config. When rebalance, just ignore the live instance with no config.

Let's just check for allNodes. That shall be good enough.

Comment (i3wangyi) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/AbstractEvenDistributionRebalanceStrategy.java]: Updated the PR, and the checks are only for `allNodes` only. I've also manually tested the changes on some cluster, setting one instance weight = 0, the result is expected.

**Comment by i3wangyi** [comment]
The PR is ready to merge into master, approved by @jiajunwang. 

I've done a manual verification on a testing cluster environment.

**Comment by jiajunwang** [comment]
@narendly Do you need to take another look? Since you have a change request here.

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/AbstractEvenDistributionRebalanceStrategy.java [hunk 20]
```diff
@@ -82,7 +85,24 @@ public void init(String resourceName, final List<String> partitions,
   @Override
   public ZNRecord computePartitionAssignment(final List<String> allNodes,
       final List<String> liveNodes, final Map<String, Map<String, String>> currentMapping,
-      ResourceControllerDataProvider clusterData) throws HelixException {
+      ResourceControllerDataProvider clusterData) {
+    // valida the instance configs
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/AbstractEvenDistributionRebalanceStrategy.java]: nit: "validate"

Comment (i3wangyi) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/strategy/AbstractEvenDistributionRebalanceStrategy.java]: done

**Comment by i3wangyi** [comment]
The commit message: 

Filter instances of weight = 0 for any partition assignment …

1. Fix the available space calculation issue in card dealing algorithm
2. Remove the instances of weight 0 from AbstractEvenDistributionRebalanceStrategy.java#computePartitionAssignment's input parameters
