### PR TITLE
Fix management mode history duplicate recording

### LINKED ISSUE #1845: Duplicate management history entries recorded
### Describe the bug
The management mode history has duplicate entries. It does not impact the normal function, but it's good to get it fixed to avoid confusion.

### To Reproduce
Enable cluster freeze mode in a staging cluster. Because of multiple events(live instance change events), the management mode pipeline could be run multiple times. Then the same mode history is recorded multiple times.

```
 "MANAGEMENT_MODE_HISTORY": [
      "{STATUS=COMPLETED, CONTROLLER=host1, MODE=CLUSTER_FREEZE, FROM_HOST=host2, TIME=2021-08-18T20:58:51.659Z}",
      "{STATUS=COMPLETED, CONTROLLER=host1, MODE=CLUSTER_FREEZE, FROM_HOST=host2, TIME=2021-08-18T21:02:08.893Z}",
      "{STATUS=COMPLETED, CONTROLLER=host1, MODE=CLUSTER_FREEZE, FROM_HOST=host2, TIME=2021-08-18T21:09:03.659Z}",
      "{STATUS=COMPLETED, CONTROLLER=host1, MODE=CLUSTER_FREEZE, FROM_HOST=host2 TIME=2021-08-18T21:13:03.660Z}",
```

### Expected behavior
Should only record one time.

### PR DESCRIPTION
**Pull request by huizhilu**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixed #1845

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

The management mode history has duplicate entries. It does not impact the normal function, but it's good to get it fixed to avoid confusion.

Enable cluster freeze mode in a staging cluster. Because of multiple events(live instance change events), the management mode pipeline could be run multiple times. Then the same mode history is recorded multiple times.

```
 "MANAGEMENT_MODE_HISTORY": [
      "{STATUS=COMPLETED, CONTROLLER=host1, MODE=CLUSTER_FREEZE, FROM_HOST=host2, TIME=2021-08-18T20:58:51.659Z}",
      "{STATUS=COMPLETED, CONTROLLER=host1, MODE=CLUSTER_FREEZE, FROM_HOST=host2, TIME=2021-08-18T21:02:08.893Z}",
      "{STATUS=COMPLETED, CONTROLLER=host1, MODE=CLUSTER_FREEZE, FROM_HOST=host2, TIME=2021-08-18T21:09:03.659Z}",
      "{STATUS=COMPLETED, CONTROLLER=host1, MODE=CLUSTER_FREEZE, FROM_HOST=host2 TIME=2021-08-18T21:13:03.660Z}
```

### Tests

- [x] The following tests are written for this issue:

TestManagementModeStage
TestClusterFreezeMode

- The following is the result of the "mvn test" command on the appropriate module:

```
12:45:13,985 [INFO] Results:
12:45:13,985 [INFO]
12:45:13,985 [ERROR] Failures:
12:45:13,985 [ERROR]   TestZeroReplicaAvoidance.testWagedRebalancer:182 expected:<true> but was:<false>
12:45:13,985 [INFO]
12:45:13,985 [ERROR] Tests run: 1282, Failures: 1, Errors: 0, Skipped: 0
12:45:13,986 [INFO]
12:45:13,991 [INFO] ------------------------------------------------------------------------
12:45:13,992 [INFO] BUILD FAILURE
12:45:13,992 [INFO] ------------------------------------------------------------------------
12:45:13,993 [INFO] Total time:  01:21 h
12:45:13,993 [INFO] Finished at: 2021-08-23T12:45:13-07:00
12:45:13,993 [INFO] ------------------------------------------------------------------------


13:50:28,577 [INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 31.701 s - in TestSuite
13:50:28,962 [INFO]
13:50:28,962 [INFO] Results:
13:50:28,963 [INFO]
13:50:28,963 [INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0
13:50:28,963 [INFO]
13:50:28,967 [INFO]
13:50:28,968 [INFO] --- jacoco-maven-plugin:0.8.6:report (generate-code-coverage-report) @ helix-core ---
13:50:29,003 [INFO] Loading execution data file /home/hulu/Projects/helix/helix-core/target/jacoco.exec
13:50:29,473 [INFO] Analyzed bundle 'Apache Helix :: Core' with 909 classes
13:50:30,936 [INFO] ------------------------------------------------------------------------
13:50:30,936 [INFO] BUILD SUCCESS
13:50:30,937 [INFO] ------------------------------------------------------------------------
13:50:30,938 [INFO] Total time:  37.736 s
13:50:30,938 [INFO] Finished at: 2021-08-23T13:50:30-07:00
13:50:30,939 [INFO] ------------------------------------------------------------------------
```

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/controller/stages/ManagementModeStage.java [hunk 1]
```diff
@@ -157,14 +163,14 @@ private void recordClusterStatus(ClusterManagementMode mode, HelixDataAccessor a
       return;
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/controller/stages/ManagementModeStage.java:163]: If it is a new state record, but it is fully frozen, we don't record the history? I guess this is not what we want.

Comment (junkaixue) [reply helix-core/src/main/java/org/apache/helix/controller/stages/ManagementModeStage.java:163]: +1. I guess what we should do is:

if the current status is equal the status passed in, we skip it. Otherwise, we move forward to update it.

File: helix-core/src/main/java/org/apache/helix/controller/stages/ManagementModeStage.java [hunk 2]
```diff
@@ -146,6 +145,13 @@ private void recordClusterStatus(ClusterManagementMode mode, HelixDataAccessor a
     ClusterManagementMode.Type recordedType = clusterStatus.getManagementMode();
     ClusterManagementMode.Status recordedStatus = clusterStatus.getManagementModeStatus();
 
+    if (mode.getMode().equals(recordedType) && mode.getStatus().equals(recordedStatus)) {
```
Comment (junkaixue) [inline helix-core/src/main/java/org/apache/helix/controller/stages/ManagementModeStage.java:148]: This is more like a patch for history. If there are duplicates, it suppose to be something in logic error.

File: helix-core/src/main/java/org/apache/helix/controller/stages/ManagementModeStage.java (hunk 1 above)
Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/controller/stages/ManagementModeStage.java:163]: @huizhilu pinged me and explained. This logic is to prevent misleading records if a certain participant gets any message after FROZEN. In such a case, without this block, we will record additional cluster freeze records.

I agree that we don't need a history record in this case. So the logic is good.

Could you please add an example the the comment so others won't be confused like me in the future? Thanks.

Comment (junkaixue) [reply helix-core/src/main/java/org/apache/helix/controller/stages/ManagementModeStage.java:163]: I think this is still some room to improve. If it is "FROZEN" and get any message, the status is still "FROZEN" and we should not record any history. This will not cause duplicated record.

This should be fixed at logic level.

Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/controller/stages/ManagementModeStage.java:163]: Do you mean to pull the check logic outside to make the recording logic clean?
Sounds like a good plan to me.

File: helix-core/src/main/java/org/apache/helix/controller/stages/ManagementModeStage.java (hunk 2 above)
Comment (huizhilu) [reply helix-core/src/main/java/org/apache/helix/controller/stages/ManagementModeStage.java:163]: No. It's because of the timing. Ex: 2 live instance change events A and B. For A, the cache refresh already gets all the changes and calculates that the status is fully frozen. And event B, the result is the same.
So I would say, the duplicate status result is expected. But we don't want to write it again to reduce the writes.

File: helix-core/src/main/java/org/apache/helix/controller/stages/ManagementModeStage.java (hunk 1 above)
Comment (huizhilu) [reply helix-core/src/main/java/org/apache/helix/controller/stages/ManagementModeStage.java]: Thanks for the review, Guys.

This part is not a logic issue. Controller does not know the status has recorded **completed freeze mode**, until it reads the status znode. And the read logic is needed for updating the status. So the dedup logic can be and should be put in the record function. I treat them as a whole part of updating the status, including dedup.

To make the logic a bit cleaner, I've pulled the check logic out to another private method `shouldSkipRecording()`, which makes it easier to read and maintain.

Let me know if you have any questions or suggestions.

File: helix-core/src/main/java/org/apache/helix/controller/stages/ManagementModeStage.java (hunk 2 above)
Comment (junkaixue) [reply helix-core/src/main/java/org/apache/helix/controller/stages/ManagementModeStage.java:163]: If you already refreshed and get the status, then you already know what status is. So the history recording is idempotent.  There should not be any duplication. I would suggest to have an offline sync.

**Review by junkaixue — APPROVED** [review]

**Comment by huizhilu** [comment]
This PR is ready to be merged, approved by @junkaixue 

The management mode history has duplicate entries. It does not impact the normal function, but it's good to get it fixed to avoid confusion. This commit fixes the issue by adding a check for the status in metadata store and the calculated status.
