### PR TITLE
Remove the unnecessary checks to allow cleaning up map/list fields in the ClusterConfig and InstanceConfig.

### LINKED ISSUE #627: ClusterConfig/InstanceConfig set methods does not allow removal of keys for map and list fields
```
  /**
   * Set the required Instance Capacity Keys.
   * @param capacityKeys
   */
  public void setInstanceCapacityKeys(List<String> capacityKeys) {
    if (capacityKeys == null || capacityKeys.isEmpty()) {
      throw new IllegalArgumentException("The input instance capacity key list is empty.");
    }
    _record.setListField(ClusterConfigProperty.INSTANCE_CAPACITY_KEYS.name(), capacityKeys);
  }
```

I remember leaving a comment on the PR that added this that we need to allow the user to be able to set empty capacityKeys. @jiajunwang

### PR DESCRIPTION
**Pull request by jiajunwang**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:

Resolves #627 

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

The null check or empty check disallow class users to clean up the corresponding fields.
This change remove these checkes in follow methods,
- ClusterConfig.setDefaultCapacityMap
- ClusterConfig.setGlobalRebalancePreference
- ClusterConfig.setAbnormalStateResolverMap
- InstanceConfig.setInstanceCapacityMap

### Tests

- [X] The following tests are written for this issue:

Modify the existing tests to cover the new change.

- [X] The following is the result of the "mvn test" command on the appropriate module:

helix-core
[ERROR] Failures:
[ERROR]   TestAutoRebalance.testAutoRebalance:177 expected:<true> but was:<false>
[INFO]
[ERROR] Tests run: 1151, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:17 h
[INFO] Finished at: 2020-08-04T00:12:37-07:00
[INFO] ------------------------------------------------------------------------

Rerun
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.694 s
[INFO] Finished at: 2020-08-04T11:03:57-07:00
[INFO] ------------------------------------------------------------------------

helix-rest
[INFO] Tests run: 164, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 53.047 s
[INFO] Finished at: 2020-08-04T11:05:11-07:00
[INFO] ------------------------------------------------------------------------

### Commits

- [X] My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation (Optional)

- [x] In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Code Quality

- [X] My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java [hunk 1]
```diff
@@ -709,9 +709,6 @@ public void enableP2PMessage(boolean enabled) {
    * @param capacityKeys
    */
   public void setInstanceCapacityKeys(List<String> capacityKeys) {
-    if (capacityKeys == null || capacityKeys.isEmpty()) {
-      throw new IllegalArgumentException("The input instance capacity key list is empty.");
-    }
```
Comment (kaisun2000) [inline helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java:714]: What is the meaning of setting to 'null' and empty? What is the difference between  'null' and empty?

Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java:714]: Both empty the list. Null will remove the key. Empty list will set an empty list to the key. Both are fine for our logic.

Comment (kaisun2000) [reply helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java:714]: How about add an comment to let user know the intention. This would save further clarification etc,

Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java:714]: I was wrong, it actually just put a null value there. This is not what I want to do. Let me change it to the right behavior. Good catch!

File: helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java [hunk 2]
```diff
@@ -788,39 +791,43 @@ public void setDefaultPartitionWeightMap(Map<String, Integer> weightDataMap)
   private void setDefaultCapacityMap(ClusterConfigProperty capacityPropertyType,
       Map<String, Integer> capacityDataMap) throws IllegalArgumentException {
     if (capacityDataMap == null) {
-      throw new IllegalArgumentException("Default capacity data is null");
+      _record.getMapFields().remove(capacityPropertyType.name());
+    } else {
+      Map<String, String> data = new HashMap<>();
+      capacityDataMap.entrySet().stream().forEach(entry -> {
+        if (entry.getValue() < 0) {
```
Comment (kaisun2000) [inline helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java:798]: If the value string is not valid integer representation, will this throw other Exception? If so, do you want to catch it and convert to IllegalArgumentException?

File: helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java [hunk 3]
```diff
@@ -859,13 +866,18 @@ public boolean isGlobalRebalanceAsyncModeEnabled() {
 
   /**
    * Set the abnormal state resolver class map.
+   * @param resolverMap - the resolver map
+   *                    If null, the resolver map item will be removed from the config.
    */
   public void setAbnormalStateResolverMap(Map<String, String> resolverMap) {
-    if (resolverMap.values().stream()
-        .anyMatch(className -> className == null || className.isEmpty())) {
+    if (resolverMap != null && resolverMap.values().stream()
```
Comment (kaisun2000) [inline helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java:873]: I am a little bit confused. 

`anyMatch(className -> className == null))` means if there is a className (key) in resolverMap, we throw exception. 

Then how about value in resolverMap, can it be null? What does it mean then?

File: helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java (hunk 2 above)
Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java:798]: The value is not a string, it is Integer.

File: helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java (hunk 3 above)
Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java:873]: It is searching through the value set. The stream() is not done to the key set. I think you missed the first part.

But it is a good catch that I should not remove "className.isEmpty()" check.

Comment (kaisun2000) [reply helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java]: Right, we are saying value can't be empty or 'null'. However, don't forget about key, the key in resovlerMap is potentially can be null too, right? Shall we also throw an exception there?

File: helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java [hunk 4]
```diff
@@ -859,14 +866,20 @@ public boolean isGlobalRebalanceAsyncModeEnabled() {
...
-          "Invalid Abnormal State Resolver Map definition. Class name cannot be empty.");
+    if (resolverMap == null) {
+      _record.getMapFields().remove(ClusterConfigProperty.ABNORMAL_STATES_RESOLVER_MAP.name());
+    } else {
+      if (resolverMap.values().stream()
+          .anyMatch(className -> className == null || className.isEmpty())) {
+        throw new IllegalArgumentException(
+            "Invalid Abnormal State Resolver Map definition. Class name cannot be empty.");
+      }
+      _record.setMapField(ClusterConfigProperty.ABNORMAL_STATES_RESOLVER_MAP.name(), resolverMap);
```
Comment (kaisun2000) [inline helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java:881]: resolverMap can also contain key as null. Do we want to throw exception of this case?

Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java:885]: I see what you mean now. Make sense. Let me add the check for keys too.

File: helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java [hunk 5]
```diff
@@ -859,14 +866,24 @@ public boolean isGlobalRebalanceAsyncModeEnabled() {
...
+      _record.getMapFields().remove(ClusterConfigProperty.ABNORMAL_STATES_RESOLVER_MAP.name());
+    } else {
+      if (resolverMap.entrySet().stream().anyMatch(e -> {
+        String stateModelDefName = e.getKey();
+        String className = e.getValue();
+        return stateModelDefName == null || stateModelDefName.isEmpty() || className == null
+            || className.isEmpty();
+      })) {
+        throw new IllegalArgumentException(
+            "Invalid Abnormal State Resolver Map definition. StateModel definition name and the resolver class name cannot be empty.");
```
Comment (kaisun2000) [inline helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java:883]: nit. 

StateModel definition name can't be null, resolver class name cannot be empty can't be null or empty.

Comment (kaisun2000) [reply helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java:883]: We have a test case for this?

Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java:883]: Yes, the test has been added. Let me modify the log string.

**Comment by jiajunwang** [comment]
This PR is ready to be merged.
