### PR TITLE
Fix the queue not going to IN_PROGRESS state

### LINKED ISSUE #1113: JobQueue state stays STOPPED even after the queue is resumed
It has been observed that when a which was running before is being stopped, after user resumes the queue, the state of the queue will remain STOPPED. This happens when the queue does not contain any job that needs to be run.

### PR DESCRIPTION
**Pull request by alirezazamani**
### Issues
- [x] My PR addresses the following Helix issues and references them in the PR title:
Fixes #1113  

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
This PR fixes the scenario where the workflow context does not change
to IN_PROGRESS when it does not contain any job that needs to be run.
Also, since I have been observed that TestDeleteWorkflow is becoming unstable. Hence, in this PR, the DELETE_DELAY has been increase to 5 seconds.

### Tests
- [x] The following tests are written for this issue:
TestStopAndResumeQueue

- [x] The following is the result of the "mvn test" command on the appropriate module:

helix-core:
```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestJobQueueCleanUp.testJobQueueAutoCleanUp » ThreadTimeout Method org.testng....
[ERROR]   TestTaskRebalancer.timeouts:200 expected:<true> but was:<false>
[INFO] 
[ERROR] Tests run: 1146, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:27 h
[INFO] Finished at: 2020-06-22T12:15:29-07:00
[INFO] ------------------------------------------------------------------------
```
The failed test succeeded when run individually.
mvn test -Dtest="TestJobQueueCleanUp,TestTaskRebalancer"
```
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 34.156 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  39.794 s
[INFO] Finished at: 2020-06-22T14:55:23-07:00
[INFO] ------------------------------------------------------------------------
```
helix-rest:
```
[INFO] Tests run: 163, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 46.595 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 163, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  51.789 s
[INFO] Finished at: 2020-06-22T14:58:27-07:00
[INFO] ------------------------------------------------------------------------
```

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- [x] My diff has been formatted using helix-style.xml

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/task/WorkflowDispatcher.java [hunk 1]
```diff
@@ -174,6 +174,16 @@ public void updateWorkflowStatus(String workflow, WorkflowConfig workflowCfg,
       }
       return;
     }
+
+    // Step 6: handle workflow that should go IN_PROGRESS state after is has been resumed
+    // This block is added to make sure if workflow/queue context state becomes IN_PROGRESS for the
+    // case where A Queue which has been stopped before is just resumed and queue does not contain
+    // any job that needs to be run.
+    if (targetState.equals(TargetState.START)
+        && workflowCtx.getWorkflowState().equals(TaskState.STOPPED)) {
```
Comment (narendly) [inline helix-core/src/main/java/org/apache/helix/task/WorkflowDispatcher.java:183]: `workflowCtx.getWorkflowState()` is not going to be null right? If it could return null, we should do a reverse check.

Also, for enums, == would be the standard for comparison vs using equals().

Comment (alirezazamani) [reply helix-core/src/main/java/org/apache/helix/task/WorkflowDispatcher.java:183]: No it can't. If it is null, the method will return NOT_STARTED:
```
  public TaskState getWorkflowState() {
    String state = _record.getSimpleField(WorkflowContextProperties.STATE.name());
    if (state == null) {
      return TaskState.NOT_STARTED;
    }

    return TaskState.valueOf(state);
  }
```

Comment (alirezazamani) [reply helix-core/src/main/java/org/apache/helix/task/WorkflowDispatcher.java:183]: Thanks for the review. I will change it to ==

**Comment by alirezazamani** [comment]
This PR is ready to be merged, approved by @narendly 

Final commit message:
Change the queue state to IN_PROGRESS after being resumed

This commit fixes the scenario where the workflow context state
 does not change to IN_PROGRESS after being resumed.
