### PR TITLE
Fix TaskGarbageCollectionStage rebalance trigger when job purge interval is negative

### LINKED ISSUE #1353: Negative delay case in TaskGarbageCollectionStage
### Describe the bug
Since `Rebalancer.scheduleRebalance` takes in negative delay value and schedules immediately with the negative delay, `TaskGarbageCollectionStage` will incorrectly schedule rebalances if the job purge interval is set to a negative value. 

### To Reproduce
Set job purge interval to a negative value. 

### Expected behavior
If job purge interval is a negative value, do not purge.

### PR DESCRIPTION
**Pull request by NealSun96**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1353 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Since we allow negative delay in `scheduleRebalance`, which leads to immediate rebalance (on-demand), the current logic is incorrect. When job purge interval is non-positive, a rebalance is always triggered immediately. 

Adding a check earlier to disable the rebalance triggering when job purge interval is non-positive. 

### Tests
- [x] The following is the result of the "mvn test" command on the appropriate module:

[WARNING] Tests run: 1210, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 4,007.762 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 1210, Failures: 0, Errors: 0, Skipped: 1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:06 h
[INFO] Finished at: 2020-10-05T17:04:49-07:00
[INFO] ------------------------------------------------------------------------
### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Review by lei-xia — APPROVED** [review]

**Comment by NealSun96** [comment]
This PR is ready to be merged, approved by @lei-xia   
Final commit message:
## Fix TaskGarbageCollectionStage rebalance trigger when job purge interval is negative  ##
When job purge interval is negative, skip rebalance scheduling for the workflow.

File: helix-core/src/main/java/org/apache/helix/controller/stages/TaskGarbageCollectionStage.java [hunk 1]
```diff
@@ -73,9 +73,12 @@ public void process(ClusterEvent event) throws Exception {
           continue;
         }
         long purgeInterval = workflowConfig.getJobPurgeInterval();
+        if (purgeInterval <= 0) {
+          continue;
+        }
         long currentTime = System.currentTimeMillis();
         long nextPurgeTime = workflowContext.getLastJobPurgeTime() + purgeInterval;
-        if (purgeInterval > 0 && nextPurgeTime <= currentTime) {
```
Comment (kaisun2000) [inline helix-core/src/main/java/org/apache/helix/controller/stages/TaskGarbageCollectionStage.java:78]: why the previous way has a bug?

Comment (NealSun96) [reply helix-core/src/main/java/org/apache/helix/controller/stages/TaskGarbageCollectionStage.java:78]: Since we allow negative delay in scheduleRebalance, which leads to immediate rebalance (on-demand), the current logic is incorrect. When job purge interval is non-positive, a rebalance is always triggered immediately.

See after this if statement for the rebalance scheduling line. That line is always triggered in the previous version.

Comment (kaisun2000) [reply helix-core/src/main/java/org/apache/helix/controller/stages/TaskGarbageCollectionStage.java:78]: I see due to this line:
```
        scheduleNextJobPurge(workflowConfig.getWorkflowId(), nextPurgeTime, _rebalanceScheduler,
            manager);
```

previously it always schedule the purge. 

Help me to understand the impact of this a little bit more. With this change, event this is not always scheduled. From the perspective of flaky test, it does not matter, right? I mean with this pull change, we will still see the flaky test to be flaky.
