### PR TITLE
Use dedicated ZkClient in HelixPropertyFactory

### LINKED ISSUE #1106: Fix getHelixManagerProperty
Creating an issue for tracking.

  /**
   * Retrieve Helix manager property. It returns the property object with default values.
   * Clients may override these values.
   */
  public HelixManagerProperty getHelixManagerProperty(String zkAddress, String clusterName) {
    // This configAccessor is a dedicated zkclient because HelixManager is single realm
    HelixZkClient.ZkConnectionConfig connectionConfig =
        new HelixZkClient.ZkConnectionConfig(zkAddress);
    HelixZkClient zkClient = DedicatedZkClientFactory.getInstance().buildZkClient(connectionConfig);
    ConfigAccessor configAccessor = new ConfigAccessor(zkClient);
    CloudConfig cloudConfig;
    // The try-catch logic is for backward compatibility reason only. Even if the cluster is not set
    // up yet, constructing a new ZKHelixManager should not throw an exception
    try {
      cloudConfig =
          configAccessor.getCloudConfig(clusterName) == null ? buildEmptyCloudConfig(clusterName)
              : configAccessor.getCloudConfig(clusterName);
    } catch (HelixException e) {
      cloudConfig = buildEmptyCloudConfig(clusterName);
    }
    configAccessor.close();
    Properties properties = new Properties();

Need to use a dedicated ZkClient instead of creating a configaccessor with a sharedZkClient. Only an issue in locally run tests.

### PR DESCRIPTION
**Pull request by narendly**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1106 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

It's been observed that sometimes using a shared Zk connection could cause issues when we write in-memory tests that shut down ZK server and restart it. This is because with a shared Zkconnection, we may see the client's zxid be higher than that of the server, which is an invalid state in ZooKeeper. Since HelixManager is a single-realm dedicated concept, it is okay to use a dedicated zk connection to pull CloudConfig in getHelixManagerProperty() method. This will solve issues caused by zxid mismatches.

### Tests

- [x] The following tests are written for this issue:

No tests needed.

- [x] The following is the result of the "mvn test" command on the appropriate module:

```
[ERROR] Failures: 
[ERROR]   TestCustomizedViewAggregation.testCustomizedViewAggregation:389->validateAggregationSnapshot:233 expected:<true> but was:<false>
[ERROR]   TestEnableCompression.testEnableCompressionResource:116 » ThreadTimeout Method...
[ERROR]   TestDeleteJobFromJobQueue.testForceDeleteJobFromJobQueue:75 » Helix Failed to ...
[ERROR]   TestRebalanceRunningTask.testFixedTargetTaskAndEnabledRebalanceAndNodeAdded:330 expected:<true> but was:<false>
[INFO] 
[ERROR] Tests run: 1145, Failures: 4, Errors: 0, Skipped: 0

```
The failed 4 tests were run individually:

[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 52.745 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation (Optional)

- [ ] In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Code Quality

- [x] My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/HelixPropertyFactory.java [hunk 1]
```diff
@@ -47,17 +49,30 @@ public static HelixPropertyFactory getInstance() {
    * Clients may override these values.
    */
   public HelixManagerProperty getHelixManagerProperty(String zkAddress, String clusterName) {
-    ConfigAccessor configAccessor = new ConfigAccessor(zkAddress);
     CloudConfig cloudConfig;
-    // The try-catch logic is for backward compatibility reason only. Even if the cluster is not set
-    // up yet, constructing a new ZKHelixManager should not throw an exception
+    HelixZkClient zkClient = null;
```
Comment (dasahcc) [inline helix-core/src/main/java/org/apache/helix/HelixPropertyFactory.java:53]: Let's move this to the block, since it will be closed in finally block anyway.

File: helix-core/src/main/java/org/apache/helix/HelixPropertyFactory.java [hunk 2]
```diff
@@ -47,17 +49,30 @@ public static HelixPropertyFactory getInstance() {
...
     try {
-      cloudConfig =
-          configAccessor.getCloudConfig(clusterName) == null ? buildEmptyCloudConfig(clusterName)
-              : configAccessor.getCloudConfig(clusterName);
-    } catch (HelixException e) {
-      cloudConfig = buildEmptyCloudConfig(clusterName);
+      // This configAccessor is a dedicated zkclient because HelixManager is single realm
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/HelixPropertyFactory.java:55]: Let's mention another reason we want a dedicated client instead of shared client here is for the isolation level that we need.

**Comment by narendly** [comment]
This PR is ready to be merged, approved by @dasahcc 

Use dedicated ZkClient in getHelixManagerProperty

It's been observed that sometimes using a shared Zk connection could cause issues when we write in-memory tests that shut down ZK server and restart it. This is because with a shared Zkconnection, we may see the client's zxid be higher than that of the server, which is an invalid state in ZooKeeper. Since HelixManager is a single-realm dedicated concept, it is okay to use a dedicated zk connection to pull CloudConfig in getHelixManagerProperty() method. This will solve issues caused by zxid mismatches.
