### PR TITLE
Fix the IdealStateBuilder to set the correct instance group tag.

### LINKED ISSUE #1606: IdealStateBuilder ignores the input instance group tag (AKA NodeGroup)
### Describe the bug
The IdealStateBuilder tool will ignore the node group input and leave the corresponding field empty in the result IdealState.

### To Reproduce
Use IdealStateBuilder to create an IdealState with node group configured.

### Expected behavior
The node group should appear in the result IdealState.

### PR DESCRIPTION
**Pull request by jiajunwang**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1606 

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

This PR aims to simply fix the issue that IdealStateBuilder class ignores the input instance group tag.

### Tests

- [X] The following tests are written for this issue:

TestIdealStateBuilder

- [X] The following is the result of the "mvn test" command on the appropriate module:

Test is not stable, get all pass on 3rd try. Please refer to the CI test for the unstable tests.

[INFO] Tests run: 1256, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5,550.695 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1256, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/model/builder/IdealStateBuilder.java [hunk 1]
```diff
@@ -85,12 +87,13 @@
...
    */
   private int maxPartitionsPerNode;
+
   /**
    * Allocate the resource to nodes that are tagged with a specific "nodeGroup"
    * name. By default a resource will be allocated to all nodes registered to
    * the cluster.
    */
-  private String nodeGroup = "*";
+  private String nodeGroup = null;
```
Comment (pkuwm) [inline helix-core/src/main/java/org/apache/helix/model/builder/IdealStateBuilder.java:96]: Does it still apply to the java doc "By default a resource will be allocated to all nodes" - do we need to change the java doc?

Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/model/builder/IdealStateBuilder.java:96]: The original code is not fitting the comment. The reason why it is not failing is that the value is not passed.

Please also help to double-check the code. I think "*" will cause the resource to be assigned onto the node with "*" tag. I don't see any wildcard fitting logic in the rebalancer. null is the safest option.

**Review by dasahcc — APPROVED** [review]

**Review by alirezazamani — APPROVED** [review]

**Comment by kaisun2000** [comment]
https://github.com/apache/helix/actions/runs/478730540/workflow, some test failed? Is it related to this change?

**Comment by jiajunwang** [comment]
Approved by @alirezazamani and @dasahcc.
I will merge this PR since the existing test failure is in the master branch already. We will fix that issue separately.

**Comment by jiajunwang** [comment]
> https://github.com/apache/helix/actions/runs/478730540/workflow, some test failed? Is it related to this change?

No, I have tested without this PR. Same error.
In addition, as I search code, this change is not impacting any other tests except TestIdealStateBuilder in any way.
