### PR TITLE
Fix NullPointerException in TestBatchMessage.

### LINKED ISSUE #571: NPE in unit test TestBatchMessage
START TestBatchMessage_testBasic at Mon Nov 04 16:44:27 PST 2019
/TestBatchMessage_testBasic/INSTANCES/localhost_12918/MESSAGES has 1 messages
/TestBatchMessage_testBasic/INSTANCES/localhost_12918/MESSAGES has 3 messages
/TestBatchMessage_testBasic/INSTANCES/localhost_12918/MESSAGES has 2 messages
/TestBatchMessage_testBasic/INSTANCES/localhost_12918/MESSAGES has 1 messages
/TestBatchMessage_testBasic/INSTANCES/localhost_12918/MESSAGES has 2 messages
/TestBatchMessage_testBasic/INSTANCES/localhost_12918/MESSAGES has 1 messages
/TestBatchMessage_testBasic/INSTANCES/localhost_12918/MESSAGES has 0 messages
/TestBatchMessage_testBasic/INSTANCES/localhost_12918/MESSAGES has 1 messages
/TestBatchMessage_testBasic/INSTANCES/localhost_12918/MESSAGES has 0 messages
/TestBatchMessage_testBasic/INSTANCES/localhost_12918/MESSAGES has 1 messages
/TestBatchMessage_testBasic/INSTANCES/localhost_12918/MESSAGES has 0 messages
1891432 [HelixController-pipeline-task-TestBatchMessage_testBasic-(4de26d2e_TASK)] ERROR org.apache.helix.controller.GenericHelixController  - Cluster manager: control
ler_0 is not leader for TestBatchMessage_testBasic. Pipeline will not be invoked
1891510 [ZkClient-EventThread-30-localhost:2183] ERROR org.apache.helix.manager.zk.zookeeper.ZkClient  - Error handling event ZkEvent[Children of /TestBatchMessage_tes
tBasic/INSTANCES/localhost_12918/MESSAGES changed sent to org.apache.helix.integration.messaging.TestBatchMessage$TestZkChildListener@650233c6]
java.lang.NullPointerException
        at org.apache.helix.integration.messaging.TestBatchMessage$TestZkChildListener.handleChildChange(TestBatchMessage.java:52)
        at org.apache.helix.manager.zk.zookeeper.ZkClient$8.run(ZkClient.java:1040)
        at org.apache.helix.manager.zk.zookeeper.ZkEventThread.run(ZkEventThread.java:69)
END TestBatchMessage_testBasic at Mon Nov 04 16:44:28 PST 2019
END testBasic at Mon Nov 04 16:44:28 PST 2019, took: 562ms.

/TestBatchMessage_testParticipantIncompatibleWithBatchMsg/INSTANCES/localhost_12918/MESSAGES has 0 messages
1893238 [ZkClient-EventThread-30-localhost:2183] ERROR org.apache.helix.manager.zk.zookeeper.ZkClient  - Error handling event ZkEvent[Children of /TestBatchMessage_testParticipantIncompatibleWithBatchMsg/INSTANCES/localhost_12918/MESSAGES changed sent to org.apache.helix.integration.messaging.TestBatchMessage$TestZkChildListener@3e268b6]
java.lang.NullPointerException
        at org.apache.helix.integration.messaging.TestBatchMessage$TestZkChildListener.handleChildChange(TestBatchMessage.java:52)
        at org.apache.helix.manager.zk.zookeeper.ZkClient$8.run(ZkClient.java:1040)
        at org.apache.helix.manager.zk.zookeeper.ZkEventThread.run(ZkEventThread.java:69)
END TestBatchMessage_testParticipantIncompatibleWithBatchMsg at Mon Nov 04 16:44:30 PST 2019

### PR DESCRIPTION
**Pull request by pkuwm**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fix #571 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

NullPointerException in TestBatchMessage when currentChildren is null and currentChildren.size() is called.
Add a null check in handleChildChange().

### Tests

- [ ] The following tests are written for this issue:

(List the names of added unit/integration tests)

- [x] The following is the result of the "mvn test" command on the appropriate module:

[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   TestAlertingRebalancerFailure.testTagSetIncorrect:174->checkResourceBestPossibleCalFailureState:310 expected:<true> but was:<false>
[ERROR]   TestTaskPerformanceMetrics.testTaskPerformanceMetrics:118 expected:<true> but was:<false>
[INFO]
[ERROR] Tests run: 882, Failures: 2, Errors: 0, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  57:22 min
[INFO] Finished at: 2019-11-14T18:35:23-08:00

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Code Quality

- [x] My diff has been formatted using helix-style.xml

### CODE REVIEW

File: helix-core/src/test/java/org/apache/helix/integration/messaging/TestBatchMessage.java [hunk 1]
```diff
@@ -45,13 +45,16 @@
...
-    int _maxNbOfChilds = 0;
+    int _maxNumberOfChildren = 0;
 
     @Override
-    public void handleChildChange(String parentPath, List<String> currentChilds) throws Exception {
-      System.out.println(parentPath + " has " + currentChilds.size() + " messages");
-      if (currentChilds.size() > _maxNbOfChilds) {
-        _maxNbOfChilds = currentChilds.size();
+    public void handleChildChange(String parentPath, List<String> currentChildren) {
+      if (currentChildren == null) {
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/integration/messaging/TestBatchMessage.java]: Is this an issue in production code?

Comment (pkuwm) [reply helix-core/src/test/java/org/apache/helix/integration/messaging/TestBatchMessage.java]: Not sure. Haven't checked the prod logs.

**Comment by pkuwm** [comment]
This PR is ready to be merged, approved by @jiajunwang @narendly
Commit:
```
NullPointerException in TestBatchMessage when currentChildren is null and currentChildren.size() is called.
Changelist:
Add a null check in handleChildChange().
```
