### PR TITLE
Fix Regression on Flaky Tests in TestResourceAccessor

### LINKED ISSUE #958: Regression on Flaky Tests in TestResourceAccessor
Related to #932 .

The previous fix to the flaky tests might have impacted other tests. It may be caused by stopping the controllers. A better approach is to pause the clusters instead.

### PR DESCRIPTION
**Pull request by NealSun96**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #958

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

The previous fix to the flaky tests might have impacted other tests. It may be caused by stopping the controllers. A better approach is to pause the clusters instead.

### Tests

- [x] The following is the result of the "mvn test" command on the appropriate module:

```
[INFO] Tests run: 155, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 29.911 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 155, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34.510 s
[INFO] Finished at: 2020-04-20T12:02:05-07:00
[INFO] ------------------------------------------------------------------------
```

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- [x] My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-rest/src/test/java/org/apache/helix/rest/server/TestResourceAccessor.java [hunk 1]
```diff
@@ -657,19 +660,9 @@ private void createDummyMapping(String clusterName, String resourceName,
...
 
-  private void stopClustersControllers() {
-    for (ClusterControllerManager cm : _clusterControllerManagers) {
-      if (cm != null && cm.isConnected()) {
-        cm.syncStop();
-      }
-    }
+  private void enableCluster(String clusterName, boolean enable) {
+    HelixAdmin helixAdmin = new ZKHelixAdmin(_gZkClient);
+    helixAdmin.enableCluster(clusterName, enable);
```
Comment (narendly) [inline helix-rest/src/test/java/org/apache/helix/rest/server/TestResourceAccessor.java:665]: Why do you need to create a HelixAdmin object every time this is called?

Comment (narendly) [reply helix-rest/src/test/java/org/apache/helix/rest/server/TestResourceAccessor.java:665]: Also, don't we already have a HelixAdmin in the parent abstract class created with _gZkClient already?

Comment (pkuwm) [reply helix-rest/src/test/java/org/apache/helix/rest/server/TestResourceAccessor.java:665]: +1. I believe `_gSetupTool.getClusterManagementTool()` gives you helix admin and this function `enableCluster()`. So `_gSetupTool.getClusterManagementTool().enableCluster()` is one line you need. This private method may not be needed.

Comment (NealSun96) [reply helix-rest/src/test/java/org/apache/helix/rest/server/TestResourceAccessor.java]: Wasn't able to find HelixAdmin in the parent class, but @pkuwm is correct. Thank you for the pointers and updated accordingly!

**Comment by NealSun96** [comment]
This PR is ready to be merged, approved by @narendly  
Final commit message:
## Fix Regression on Flaky Tests in TestResourceAccessor ##
The previous fix to the flaky tests might have impacted other tests. It may be caused by stopping the controllers. A better approach is to pause the clusters instead.
