### PR TITLE
2212/ensure that create cluster button is visible [helix-front]

### LINKED ISSUE #2212: create cluster button is missing helix-front
### Describe the bug

There should be a pink + button for creating helix clusters from the UI, but it no longer shows up. This prevents us from creating clusters in the UI.

### To Reproduce

Visit a cluster page, and toggle the left sidebar. You will see the pink + button briefly render and then go missing. 

### Expected behavior

The pink + button renders and the create cluster menu item is visible inside it. As a Helix UI user, I am able to create a cluster.

### PR DESCRIPTION
**Pull request by micahstubbs**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fix #2212

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR ensures that the create cluster button is visible in the left sidebar in the cluster list view. This is done both by updating styles as well as by verifying that the current user is logged in after loading all clusters.

Screen Shot 2022-09-14 at 11 17 33 AM

Screen Shot 2022-09-14 at 11 19 22 AM

### Tests

- [x] The following tests are written for this issue:

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- 
### Code Quality

- My diff has been formatted using [Prettier](https://prettier.io)

### CODE REVIEW

File: helix-front/src/app/cluster/cluster-list/cluster-list.component.ts [hunk 1]
```diff
@@ -29,7 +28,6 @@ export class ClusterListComponent implements OnInit {
 
   ngOnInit() {
     this.loadClusters();
-    this.clusterService.can().subscribe((data) => (this.can = data));
```
Comment (micahstubbs) [inline helix-front/src/app/cluster/cluster-list/cluster-list.component.ts:32]: @somecodemonkey I'm honestly not sure what this method is supposed to do. It is not defined in https://github.com/apache/helix/blob/master/helix-front/src/app/cluster/shared/cluster.service.ts 

🤔

Comment (micahstubbs) [inline helix-front/src/app/cluster/cluster-list/cluster-list.component.ts:32]: This change removes the broken permissions check from cluster creation.

Comment (micahstubbs) [reply helix-front/src/app/cluster/cluster-list/cluster-list.component.ts:32]: Here is where this `.can()` permissions method is defined: 

https://github.com/apache/helix/blob/master/helix-front/src/app/core/helix.service.ts#L14

Comment (micahstubbs) [reply helix-front/src/app/cluster/cluster-list/cluster-list.component.ts:32]: I'm looking at this again and seeing if there is a way to fix the bug while preserving the permission check. 🤔

Comment (micahstubbs) [reply helix-front/src/app/cluster/cluster-list/cluster-list.component.ts:32]: Found it! A better solution is to call the login check method again after the clusters load.

**Comment by micahstubbs** [comment]
This PR is ready to be merged, approved by @somecodemonkey   
Final commit message:
## Ensure that create cluster button is visible [helix-front]  (#2212)
Verify that current user is logged in after loading all clusters
to ensure that create cluster button is visible in left sidebar
