### PR TITLE
MissingTopState when the leader comes back on the same host

### LINKED ISSUE #2521: MaxSinglePartitionTopStateHandoffDurationGauge doesn't seem to reset upon successful leadership handoff
### Describe the bug
Helix maintains the metrics, MaxSinglePartitionTopStateHandoffDuration. This metric is used to see what is the longest time for any partition to be without TopState. 
We handle this very well for any resource/partition with multiple replicas but we don't seem to handle if the partition has only 1 replica and minActiveReplica set to 0. 

In this particular case, there is only one replica and if the node on which this partition/replica was residing if that reboots, the metric will start reporting it is missing top state. Even after the node is back online, we continue to report that is missing top state. 

The reason is that we have special case where we check if the current node with top-state is different from previous node. This will not be true in the above mentioned scenario.

### To Reproduce
Create a resource / partition with just 1 replca and min-active-replica count to 0.  Once resource is LEADER, reboot the node on which the resource/part was online. You will see that the metrics gets triggered and never resets even after node is back.

### Expected behavior
It should clear when the node i back.

### PR DESCRIPTION
**Pull request by desaikomal**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:
Fixes #2521 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

We currently don't handle the case where if the user has only one replica and the leader partition comes back on the same host as there are no other replica.

(Write a concise description including what, why, how)

### Tests

- [x] The following tests are written for this issue:
Testing done:
Added a test scenario in the JSON config file where the partition is brought oneline on the same host and validated that the test passes.

TestTopStateHandoffMetrics::failed configuration has one additional test scenario added. 

- The following is the result of the "mvn test" command on the appropriate module:

(If CI test fails due to known issue, please specify the issue and test PR locally. Then copy & paste the result of "mvn test" to here.)
mvn test is in progress (it got interrupted, so will send it once completes)
[ERROR] Failures:
[ERROR]   TestNoThrottleDisabledPartitions.testDisablingTopStateReplicaByDisablingInstance:98 expected:<false> but was:<true>
[ERROR]   TestNoThrottleDisabledPartitions.testNoThrottleOnDisabledInstance:231->setupEnvironment:317->setupCluster:436 » ZkClient
[ERROR]   TestZkConnectionLost.testDisconnectWhenConnectionBreak:140 » ThreadTimeout Met...
[ERROR]   TestZkConnectionLost.testLostZkConnection:179 » Helix Workflow testLostZkConne...
[ERROR]   TestClusterMaintenanceMode.testMaintenanceHistory:412 expected:<EXIT> but was:<ENTER>
[ERROR]   TestRecurringJobQueue.testDeletingRecurrentQueueWithHistory:298 expected:<true> but was:<false>

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/controller/stages/TopStateHandoffReportStage.java [hunk 1]
```diff
@@ -218,6 +217,8 @@ private void reportTopStateExistence(ResourceControllerDataProvider cache, Curre
       // we observed an entire top state handoff process
       reportSingleTopStateHandoff(cache, lastTopStateInstance, currentTopStateInstance,
           resourceName, partition, clusterStatusMonitor, lastPipelineFinishTimestamp);
```
Comment (parakhnr) [inline helix-core/src/main/java/org/apache/helix/controller/stages/TopStateHandoffReportStage.java:219]: I feel like we should modify the if check to just use `if (lastTopStateInstance !=null)` and reuse the `reportSingleTopStateHandoff` function instead by getting rid of the if statement that returns on `topStateInstance == currentTopStateInstance` in `reportSingleTopStateHandoff` function.

File: helix-core/src/main/java/org/apache/helix/controller/stages/TopStateHandoffReportStage.java [hunk 2]
```diff
@@ -218,6 +217,8 @@ private void reportTopStateExistence(ResourceControllerDataProvider cache, Curre
       // we observed an entire top state handoff process
       reportSingleTopStateHandoff(cache, lastTopStateInstance, currentTopStateInstance,
```
Comment (parakhnr) [inline helix-core/src/main/java/org/apache/helix/controller/stages/TopStateHandoffReportStage.java:218]: I feel like we should modify the if check to just use `if (lastTopStateInstance !=null)` and reuse the `reportSingleTopStateHandoff` function for both usecases instead by getting rid of the if statement that returns on `topStateInstance == currentTopStateInstance` in `reportSingleTopStateHandoff` function.

Comment (rahulrane50) [reply helix-core/src/main/java/org/apache/helix/controller/stages/TopStateHandoffReportStage.java:218]: +1 Why do need two branches here? Even if we simply remove this if condition as well as first check in reportSingleTopStateHandoff about same instance then also it will automatically take care of this case right?

Comment (desaikomal) [reply helix-core/src/main/java/org/apache/helix/controller/stages/TopStateHandoffReportStage.java:218]: i can do that optimization but i had concern with this code: 
    // Make sure last top state instance has not bounced during cluster data cache refresh
    if (cache.getLiveInstances().containsKey(lastTopStateInstance)) {
      String lastTopStateSession =
          cache.getLiveInstances().get(lastTopStateInstance).getEphemeralOwner();
      // We need this null check as there are test cases creating incomplete current state
      if (cache.getCurrentState(lastTopStateInstance, lastTopStateSession).get(resourceName)
          != null) {
        startTime =
            cache.getCurrentState(lastTopStateInstance, lastTopStateSession).get(resourceName)
                .getStartTime(partition.getPartitionName());
        fromTopStateUserLatency =
            cache.getCurrentState(lastTopStateInstance, lastTopStateSession).get(resourceName)
                .getEndTime(partition.getPartitionName()) - startTime;
      }
    }

So i wanted to first make sure change works properly and then optimize it but code de-dup. i can combine the two into one change.

let me know what you would prefer. i prefer the current approach but i am ready to hear reviewers choice too.
thanks,

Comment (desaikomal) [reply helix-core/src/main/java/org/apache/helix/controller/stages/TopStateHandoffReportStage.java:217]: Resolving as i updated the conditions in the other method.

**Review by rahulrane50 — APPROVED** [review]
Thanks Komal! LGTM. I'm just wondering now why did they add this check (current top state instance not equals to last top state instance) in the first place? I would suggest to get @junkaixue opinion as well on this just to make sure we are reporting wrong for this very important metric.

**Comment by desaikomal** [comment]
Thanks @parakhnr and @rahulrane50 for reviewing the change. This PR is ready to be merged, approved by @rahulrane50

Commit message: If you have a single replica and that goes offline and comes back on the same host, we don't reset the counter. This fixes the behavior.
