### PR TITLE
Fix partitions double charged for pending message

### LINKED ISSUE #568: Double charging for existing pending message
In the IntermediateCalStage, Helix does a double charge for existing pending message. For example, when you have a message pending for the partition, it will be charged for pending ST first. Then when we do charge for recovery/load balance partitions, they will be charged again.

### PR DESCRIPTION
**Pull request by dasahcc**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:

Fixes #568 

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

Current Helix will charge the partitions with pending message twice due to not remove the partition from partitions need recovery/load balance set when they are charged for pending message.

This fix will fix the problem for recovery/load/ANY rebalance type charged for pending messages.

### Tests

- [X] The following tests are written for this issue:
Adding pending message piece for a partition.

- [X] The following is the result of the "mvn test" command on the appropriate module:

[ERROR] Failures: 
[ERROR]   TestPartitionMovementThrottle.testResourceThrottle:162->getMaxParallelTransitionCount:376 » ConcurrentModification
[ERROR]   TestTaskPerformanceMetrics.testTaskPerformanceMetrics:118 expected:<true> but was:<false>
[ERROR]   TestGetLastScheduledTaskExecInfo.testGetLastScheduledTaskExecInfo:73 expected:<COMPLETED> but was:<RUNNING>
[INFO] 
[ERROR] Tests run: 882, Failures: 3, Errors: 0, Skipped: 1

[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 77.865 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0

### Commits

- [X] My commits all reference appropriate Apache Helix GitHub issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Code Quality

- [X] My diff has been formatted using helix-style.xml

### CODE REVIEW

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestIntermediateStateCalcStage.java [hunk 1]
```diff
@@ -248,26 +255,28 @@ public void testWithClusterConfigChange() {
 
     IntermediateStateOutput output = event.getAttribute(AttributeName.INTERMEDIATE_STATE.name());
 
-    for (String resource : resourceSet) {
+    for (String resource : resources) {
       // Note Assert.assertEquals won't work. If "actual" is an empty map, it won't compare
       // anything.
-      Assert.assertTrue(output.getPartitionStateMap(resource).getStateMap()
-          .equals(expectedResult.getPartitionStateMap(resource).getStateMap()));
+      Assert.assertEquals(output.getPartitionStateMap(resource).getStateMap(), expectedResult.getPartitionStateMap(resource).getStateMap());
```
Comment (i3wangyi) [inline helix-core/src/test/java/org/apache/helix/controller/stages/TestIntermediateStateCalcStage.java]: This is my test script to verify that some partitions do get double-charged, but it seems after the fix, there's no special assertions to claim that these partitions are not in the output?

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestIntermediateStateCalcStage.java [hunk 2]
```diff
@@ -77,6 +80,11 @@ public void testNoStateMissing() {
           if (resource.endsWith("0")) {
             // Regular recovery balance
             currentStateOutput.setCurrentState(resource, partition, instanceName, "OFFLINE");
+            // add blocked state transition messages
```
Comment (i3wangyi) [inline helix-core/src/test/java/org/apache/helix/controller/stages/TestIntermediateStateCalcStage.java]: Could you add some comments about the expected results after adding these pending ST messages? Like partition 'p0' shouldn't be in the output

File: helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java [hunk 3]
```diff
@@ -487,10 +490,18 @@ private void chargePendingTransition(Resource resource, CurrentStateOutput curre
...
             // Only charge this instance if the partition is not disabled
             throttleController.chargeInstance(rebalanceType, instance);
             shouldChargePartition = true;
+            // Remove the partition marked as partition need recovery/load balance. Otherwise, they
+            // will be double charged when they already charged for pending messages.
+            // At the same time, we need to update the intermediate map since it was supposed to
+            // be updated when the recovery rebalance throttling piece.
+            cleanPartitionsAreCharged(partition, partitionsNeedRecovery, partitionsNeedLoadbalance,
+                rebalanceType);
+            intermediatePartitionStateMap
```
Comment (i3wangyi) [inline helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java]: bestPossiblePartitionStateMap and intermediatePartitionStateMap updates are addition to the bug fix, right? Why is it needed?

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestIntermediateStateCalcStage.java (hunk 1 above)
Comment (dasahcc) [reply helix-core/src/test/java/org/apache/helix/controller/stages/TestIntermediateStateCalcStage.java]: I am not sure whether you understand the scenario. Once the pending messages added to resource0 and the throttling set to 3. p0 and p1 will be charged for pending and only 1 quota leftover. Then for recovery throttle, p0 will take the quota and p1 will be throttled. So it is unexpected result.

With the fix, the expected result will match the computed result.

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestIntermediateStateCalcStage.java (hunk 2 above)
Comment (dasahcc) [reply helix-core/src/test/java/org/apache/helix/controller/stages/TestIntermediateStateCalcStage.java]: I think you do not understand the expect result. If they are throttled, their final mapping should be their current states.

File: helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java (hunk 3 above)
Comment (dasahcc) [reply helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java]: This is used for assignment. Intermediate assign should be null at first beginning. It will be filled with either BestPossible or CurrentState when it has been throttled or not.

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestIntermediateStateCalcStage.java (hunk 1 above)
Comment (i3wangyi) [reply helix-core/src/test/java/org/apache/helix/controller/stages/TestIntermediateStateCalcStage.java]: My observations of the test code are that in this final Assertion stage, other than the format change, the content doesn't change at all. It shouldn't be the case because you modified the behavior of adding the pending ST messages, right? Something or some comments need to be here. Otherwise, without adding or adding the ST messages, the test script stays same?
If I missed something, please let me know.

File: helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java (hunk 3 above)
Comment (i3wangyi) [reply helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java]: Or maybe put it in another question: what if we don't set the intermediatePartitionStateMap after the fix, what's wrong with it? Or shall we add the update logic if we don't have the fix?

File: helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java [hunk 4]
```diff
@@ -945,4 +956,27 @@ private int getIdealStateMatched(Partition partition) {
...
+  private void cleanPartitionsAreCharged(Partition partition, Set<Partition> partitionsNeedRecovery,
+      Set<Partition> partitionsNeedLoadbalance, RebalanceType rebalanceType) {
+    switch (rebalanceType) {
+    case RECOVERY_BALANCE:
+      partitionsNeedRecovery.remove(partition);
+      break;
+    case LOAD_BALANCE:
+      partitionsNeedLoadbalance.remove(partition);
+      break;
+    case ANY:
```
[the remark this answers is not in the document]
Comment (dasahcc) [reply helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java]: Good catch!

File: helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java (hunk 3 above)
Comment (narendly) [inline helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java]: I think we could tweak the structure to minimize confusion in the future. Here's a suggestion:

- First, please use this for the inline comment:

// If there is a pending state transition for the partition, that means that an assignment has already been made and the state transition message has already been sent out for the partition in a previous pipeline run. We must honor this and reflect it by charging for the pending state transition message.
// Since the assignment has already been made for the pending message, we do a special treatment for it by setting the best possible state directly in intermediatePartitionStateMap so that the pending message won't be double-assigned or double-charged in recovery or load balance.

- And please merge the two lines of logic by creating a method (instead of cleanPartitionsAreCharged):

```
  /**
   * Pretreat a partition with a pending message so that the partition will not be double-charged or double-assigned during recovery and load balance.
   * @param partition
   * @param partitionsNeedRecovery
   * @param partitionsNeedLoadbalance
   * @param rebalanceType
   */
  private void preAssignPendingTransitions(Partition partition, Set<Partition> partitionsNeedRecovery,
      Set<Partition> partitionsNeedLoadbalance, RebalanceType rebalanceType, PartitionStateMap bestPossiblePartitionStateMap,
      PartitionStateMap intermediatePartitionStateMap) {
    // Pass the best possible state directly into intermediatePartitionStateMap
    // This is safe to do so because we already have a pending transition for this partition, implying that the assignment has been made in previous pipeline
    intermediatePartitionStateMap.setState(partition, bestPossiblePartitionStateMap.getPartitionMap(partition));
    // Remove the partition's name from the set of partition (names) that need to be charged and assigned to prevent double-processing
    switch (rebalanceType) {
    case RECOVERY_BALANCE:
      partitionsNeedRecovery.remove(partition);
      break;
    case LOAD_BALANCE:
      partitionsNeedLoadbalance.remove(partition);
      break;
    }
  }
```

I think this way we make it 100% clear what our intentions are and why we're making this change.

Comment (dasahcc) [reply helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java]: Good comments and craftmanship, Hunter!

Comment (dasahcc) [reply helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java]: Just make the name handlePendingStateTransitionsForThrottling to make it clear. Pretreat sounds more like a hacky way.

Comment (narendly) [reply helix-core/src/main/java/org/apache/helix/controller/stages/IntermediateStateCalcStage.java]: @dasahcc Sure. I think that name makes sense.

**Comment by dasahcc** [comment]
This PR is ready to be merged, approved by @i3wangyi @narendly @jiajunwang
