### PR TITLE
Fix issue when client only sets ANY at cluster level throttle config

### LINKED ISSUE #332: Issue when client ONLY sets cluster level ANY throttle config
The current implementation has a loophole when 
1. When client **ONLY** sets cluster level ANY throttle config (no specific type throttle)
2. The config won't be respected when charging load_rebalance or recovery_rebalance types

The root cause is the implementation relies on the counters in the hashmap, where each type including ANY is of different entry.

### PR DESCRIPTION
**Pull request by i3wangyi**
**Issues**
(fixes #332 Issue when client ONLY sets cluster level ANY throttle config )

**Description**
The fix will decrement the quota from ANY when any throttle is applied and charged. 

**Tests**
Added unit test - TestStateTransitionThrottleController 

**mvn test**
Shut down zookeeper at port 2183 in thread main
[ERROR] Tests run: 837, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 3,989.564 s <<< FAILURE! - in TestSuite
[ERROR] testJobQueueAutoCleanUp(org.apache.helix.integration.task.TestJobQueueCleanUp)  Time elapsed: 300.016 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testJobQueueAutoCleanUp() didn't finish within the time-out 300000

[ERROR] testLostZkConnection(org.apache.helix.integration.TestZkConnectionLost)  Time elapsed: 84.992 s  <<< FAILURE!
org.apache.helix.HelixException: Workflow "testLostZkConnection_20190716T231830" context is empty or not in states: "[COMPLETED]", current state: "IN_PROGRESS"
	at org.apache.helix.integration.TestZkConnectionLost.testLostZkConnection(TestZkConnectionLost.java:140)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestZkConnectionLost.testLostZkConnection:140 » Helix Workflow "testLostZkConn...
[ERROR]   TestJobQueueCleanUp.testJobQueueAutoCleanUp » ThreadTimeout Method org.testng....
[INFO] 
[ERROR] Tests run: 837, Failures: 2, Errors: 0, Skipped: 0
However, the 2 failed tests pass individually when running in IDE

Code Quality
 My diff has been formatted using helix-style.xml

### CODE REVIEW

**Comment by i3wangyi** [comment]
Add the mvn test result.

```
Shut down zookeeper at port 2183 in thread main
[ERROR] Tests run: 837, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 3,989.564 s <<< FAILURE! - in TestSuite
[ERROR] testJobQueueAutoCleanUp(org.apache.helix.integration.task.TestJobQueueCleanUp)  Time elapsed: 300.016 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testJobQueueAutoCleanUp() didn't finish within the time-out 300000

[ERROR] testLostZkConnection(org.apache.helix.integration.TestZkConnectionLost)  Time elapsed: 84.992 s  <<< FAILURE!
org.apache.helix.HelixException: Workflow "testLostZkConnection_20190716T231830" context is empty or not in states: "[COMPLETED]", current state: "IN_PROGRESS"
	at org.apache.helix.integration.TestZkConnectionLost.testLostZkConnection(TestZkConnectionLost.java:140)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestZkConnectionLost.testLostZkConnection:140 » Helix Workflow "testLostZkConn...
[ERROR]   TestJobQueueCleanUp.testJobQueueAutoCleanUp » ThreadTimeout Method org.testng....
[INFO] 
[ERROR] Tests run: 837, Failures: 2, Errors: 0, Skipped: 0
```

However, the 2 failed tests **pass individually when running in IDE**

**Comment by i3wangyi** [comment]
The latest commit added the integration test. The test verifies at most 1 ST occurs at a time on any instance when cluster level throttle is set to ANY, quota = 1.

File: helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java [hunk 1]
```diff
@@ -211,8 +218,54 @@ public void testANYtypeThrottle() throws InterruptedException {
...
+    DelayedTransition.setDelay(20);
+    DelayedTransition.enableThrottleRecord();
+
+    List<MockParticipantManager> newNodes = Arrays.asList(_participants).subList(NODE_NR - 3, NODE_NR);
+    newNodes.forEach(MockParticipantManager::syncStart);
+    newNodes.forEach(node -> {
+      try {
+        Assert.assertTrue(TestHelper.verify(
+            () -> getMaxParallelTransitionCount(DelayedTransition.getInstancePatitionTransitionTimes(), node.getInstanceName()) <= 1, 1000 * 2));
+      } catch (Exception e) {
```
Comment (pkuwm) [inline helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java]: Would this exception be more specific? What type of exception would it throw?

Comment (i3wangyi) [reply helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java]: It is a generic exception (mostly timeout) thrown from the `verify` method in TestHelper. I think it's fine putting generic here since the class is only used for testing only, and we don't except the exception even thrown.

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestStateTransitionThrottleController.java [hunk 2]
```diff
@@ -0,0 +1,182 @@
...
+import com.google.common.collect.ImmutableSet;
+import java.util.Arrays;
+import java.util.List;
+import java.util.Set;
+import org.apache.helix.api.config.StateTransitionThrottleConfig;
+import org.apache.helix.model.ClusterConfig;
+import org.testng.Assert;
+import org.testng.annotations.Test;
+
+
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/stages/TestStateTransitionThrottleController.java]: Have the files been properly formatted according to helix-style?

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestStateTransitionThrottleController.java [hunk 3]
```diff
@@ -0,0 +1,182 @@
...
+    Set<String> resources = ImmutableSet.of(resource);
+    Set<String> liveInstances = ImmutableSet.of(instance);
+
+    // consume from instance level
+    StateTransitionThrottleController controller =
+        new StateTransitionThrottleController(resources, clusterConfig, liveInstances);
+    Assert.assertTrue(controller.isThrottleEnabled());
+
+    controller.chargeCluster(StateTransitionThrottleConfig.RebalanceType.ANY);
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/stages/TestStateTransitionThrottleController.java]: Can you make the following 3 blocks more concise? Too much repeated code.

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestStateTransitionThrottleController.java [hunk 4]
```diff
@@ -0,0 +1,182 @@
...
+import org.apache.helix.api.config.StateTransitionThrottleConfig;
+import org.apache.helix.model.ClusterConfig;
+import org.testng.Assert;
+import org.testng.annotations.Test;
+
+
+
+public class TestStateTransitionThrottleController {
+
+  @Test(description = "Only config cluster of ANY type, charge cluster")
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/stages/TestStateTransitionThrottleController.java]: Revise your descriptions so that they are easier to understand?

File: helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java [hunk 5]
```diff
@@ -42,12 +45,17 @@
...
+import org.apache.helix.tools.ClusterVerifiers.ClusterLiveNodesVerifier;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 import org.testng.Assert;
 import org.testng.annotations.AfterMethod;
 import org.testng.annotations.BeforeClass;
 import org.testng.annotations.Test;
 
 public class TestPartitionMovementThrottle extends ZkStandAloneCMTestBase {
+  private static final Logger LOGGER = LoggerFactory.getLogger(TestPartitionMovementThrottle.class);
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java]: Let's not log in the tests. If you need to debug, use print statements in your local environment.

And let us use LOG for the logger if you need to use it in other parts of the codebase.

File: helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java [hunk 6]
```diff
@@ -279,13 +332,15 @@ public void testResourceThrottleWithDelayRebalancer() {
...
     for (String db : _dbs) {
-      validateThrottle(DelayedTransition.getResourcePatitionTransitionTimes(), db, 2);
+      int maxInParallel = getMaxParallelTransitionCount(DelayedTransition.getResourcePatitionTransitionTimes(), db);
+      System.out.println(
+          "MaxInParallel: " + maxInParallel + " maxPendingTransition: " + 2);
+      Assert.assertTrue(maxInParallel <= 2, "Throttle condition does not meet for " + db);
     }
   }
 
-  private void validateThrottle(
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java]: Is there a strong reason we're modifying this method?

File: helix-core/src/test/java/org/apache/helix/integration/common/ZkStandAloneCMTestBase.java [hunk 7]
```diff
@@ -28,8 +28,6 @@
 import org.apache.helix.integration.manager.MockParticipantManager;
 import org.apache.helix.tools.ClusterVerifiers.BestPossibleExternalViewVerifier;
 import org.apache.helix.tools.ClusterVerifiers.ZkHelixClusterVerifier;
-import org.slf4j.Logger;
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/integration/common/ZkStandAloneCMTestBase.java]: Good that you are removing redundant imports, but let us have a separate PR for this type of changes. Fine for this PR.

**Comment by narendly** [comment]
Some concerns:

1. What would help others see that you aren't breaking any features is to keep existing tests the same (not modify any existing tests - adding new test cases is encouraged, however). Could we minimize changes to existing tests?

2. Do we have the test result?

File: helix-core/src/main/java/org/apache/helix/controller/stages/StateTransitionThrottleController.java [hunk 8]
```diff
@@ -208,13 +210,20 @@ protected void chargeResource(StateTransitionThrottleConfig.RebalanceType rebala
...
+  }
+
+  private void charge(StateTransitionThrottleConfig.RebalanceType rebalanceType,
+      Map<StateTransitionThrottleConfig.RebalanceType, Long> quota) {
+    if (StateTransitionThrottleConfig.RebalanceType.NONE.equals(rebalanceType)) {
+      logger.error("Wrong rebalance type NONE as parameter");
+      return;
+    }
+    // if ANY type is present, decrement one else do nothing
+    quota.computeIfPresent(StateTransitionThrottleConfig.RebalanceType.ANY, (key, val) -> Math.max(0, val - 1));
```
[the remark this answers is not in the document]
Comment (i3wangyi) [reply helix-core/src/main/java/org/apache/helix/controller/stages/StateTransitionThrottleController.java]: The names are taken by method parameters. They're more important and names of (key, val) should be fine under simple logics for people familiar with the method.

File: helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java (hunk 6 above)
Comment (i3wangyi) [reply helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java]: Yes. The TestHelper.verify method expects an interface with boolean return value. The original method returns void. As you can see, I just pull out the part where it verifies `maxParallelCount <= input `which makes more sense and visible

File: helix-core/src/test/java/org/apache/helix/integration/common/ZkStandAloneCMTestBase.java (hunk 7 above)
Comment (i3wangyi) [reply helix-core/src/test/java/org/apache/helix/integration/common/ZkStandAloneCMTestBase.java]: Sorry I guess these are just auto-done by IDE

**Comment by i3wangyi** [comment]
> Some concerns:
> 
> 1. What would help others see that you aren't breaking any features is to keep existing tests the same (not modify any existing tests - adding new test cases is encouraged, however). Could we minimize changes to existing tests?
> 2. Do we have the test result?

Like I've replied inline, if you look a little careful, I just make the `validate` method more visible and didn't change any verification methods. I need it cause TestHelper expects a boolean returned interface. 

The test result is in the second comment and I've just updated it.

File: helix-core/src/main/java/org/apache/helix/controller/stages/StateTransitionThrottleController.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (narendly) [reply helix-core/src/main/java/org/apache/helix/controller/stages/StateTransitionThrottleController.java]: Sorry, I don't quite understand. Does `(rebalanceType, quota) -> Math.max(0, quota - 1)` not work? Are you saying it's not important to make code self-descriptive? The whole point is to make it so that it's easier to understand for people who are not familiar with what we're doing here?

File: helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java (hunk 6 above)
Comment (narendly) [reply helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java]: @i3wangyi You make a great point. Thanks for clarifying and I believe this is the correct thing to do.

File: helix-core/src/main/java/org/apache/helix/controller/stages/StateTransitionThrottleController.java [hunk 9]
```diff
@@ -99,6 +99,21 @@ public StateTransitionThrottleController(Set<String> resources, ClusterConfig cl
     }
   }
 
+  // The getter methods are used for debugging and testing purpose
```
Comment (narendly) [inline helix-core/src/main/java/org/apache/helix/controller/stages/StateTransitionThrottleController.java]: I am not 100% comfortable with adding methods just for this purpose. Here's a trick you can do (I have done this in some tests):

Instead of adding methods (that shouldn't otherwise be used other than testing purposes), create a child class (for example, `MockStateTranisitonThrottleController`) that extends this class and just add these test/debug methods. That way, in your unit tests, you could use the mock class and still utilize these methods that expose internal variables, rather than adding methods directly to the main class.

Do you think that would work?

File: helix-core/src/main/java/org/apache/helix/controller/stages/StateTransitionThrottleController.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (i3wangyi) [reply helix-core/src/main/java/org/apache/helix/controller/stages/StateTransitionThrottleController.java]: Look at the method parameter, these names are already taken

File: helix-core/src/main/java/org/apache/helix/controller/stages/StateTransitionThrottleController.java (hunk 9 above)
Comment (i3wangyi) [reply helix-core/src/main/java/org/apache/helix/controller/stages/StateTransitionThrottleController.java]: In addition to the subclass, you also need to make the fields protected otherwise they won't be accessible from subclass either. Making it protected doesn't make things better versus package-private method. Do you know why we need to have getMethods instead of directly accessing the internal variables? Because you could implement get methods in a more self defensive manner but `protected` just exposes the private field

File: helix-core/src/main/java/org/apache/helix/controller/stages/StateTransitionThrottleController.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (narendly) [reply helix-core/src/main/java/org/apache/helix/controller/stages/StateTransitionThrottleController.java]: I see what you were saying earlier. You could do `(type, quotaCount)` or something similar. Point is to make the code a little more readable :)

File: helix-core/src/main/java/org/apache/helix/controller/stages/StateTransitionThrottleController.java (hunk 9 above)
Comment (narendly) [reply helix-core/src/main/java/org/apache/helix/controller/stages/StateTransitionThrottleController.java]: Yes, you would need to make the relevant fields `protected`. That was implied. `protected` should be good enough as long as we don't make it `public`. The point here is to avoid adding methods that aren't strictly part of the class logic :)

File: helix-core/src/main/java/org/apache/helix/controller/stages/StateTransitionThrottleController.java [hunk 10]
```diff
@@ -208,13 +195,20 @@ protected void chargeResource(StateTransitionThrottleConfig.RebalanceType rebala
...
+  }
+
+  private void charge(StateTransitionThrottleConfig.RebalanceType rebalanceType,
+      Map<StateTransitionThrottleConfig.RebalanceType, Long> quota) {
+    if (StateTransitionThrottleConfig.RebalanceType.NONE.equals(rebalanceType)) {
+      logger.error("Wrong rebalance type NONE as parameter");
+      return;
+    }
+    // if ANY type is present, decrement one else do nothing
+    quota.computeIfPresent(StateTransitionThrottleConfig.RebalanceType.ANY, (type, quotaNumber) -> Math.max(0, quotaNumber - 1));
```
Comment (narendly) [inline helix-core/src/main/java/org/apache/helix/controller/stages/StateTransitionThrottleController.java]: Minor: Did you format this?

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestStateTransitionThrottleController.java [hunk 11]
```diff
@@ -0,0 +1,193 @@
...
+    Assert.assertEquals(controller.getResourceLevelQuota(ANY, RESOURCE), anyResourceLevelQuota - 1);
+    controller.chargeResource(RECOVERY_BALANCE, RESOURCE);
+    Assert.assertEquals(controller.getResourceLevelQuota(RECOVERY_BALANCE, RESOURCE),
+        recoveryResourceLevelQuota - 1);
+    controller.chargeResource(LOAD_BALANCE, RESOURCE);
+    Assert.assertEquals(controller.getResourceLevelQuota(LOAD_BALANCE, RESOURCE),
+        loadResourceLevelQuota - 1);
+  }
+
+  private static class StateTransitionThrottleControllerAccessor
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/controller/stages/TestStateTransitionThrottleController.java]: The convention is to prepend "Mock" -> MockStateTransitionThrottleControllerAccessor in Helix's codebase.

But I'm not too particular about the naming of the class. But I think you should add a block comment here why you have this class. Just saying that you are extending it to expose some internals for testing is fine?

File: helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java [hunk 12]
```diff
@@ -149,7 +156,7 @@ public void testResourceThrottle() throws Exception {
       // there are recovery or error partitions present, maxPendingTransition below is adjusted from
       // 2 to 5 because BOTH recovery balance and load balance could happen in the same pipeline
       // iteration
-      validateThrottle(DelayedTransition.getResourcePatitionTransitionTimes(), db, 5);
+      Assert.assertTrue(getMaxParallelTransitionCount(DelayedTransition.getResourcePatitionTransitionTimes(), db) <= 5);
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java]: This line looks pretty long. Did you format?

File: helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java [hunk 13]
```diff
@@ -179,8 +186,7 @@ public void testPartitionRecoveryRebalanceThrottle() throws InterruptedException
     Thread.sleep(2000);
 
     for (int i = 0; i < NODE_NR; i++) {
-      validateThrottle(DelayedTransition.getInstancePatitionTransitionTimes(),
-          _participants[i].getInstanceName(), 2);
+      Assert.assertTrue(getMaxParallelTransitionCount(DelayedTransition.getInstancePatitionTransitionTimes(), _participants[i].getInstanceName()) <= 2);
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java]: Format?

File: helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java [hunk 14]
```diff
@@ -211,8 +217,54 @@ public void testANYtypeThrottle() throws InterruptedException {
     Thread.sleep(2000L);
 
     for (int i = 0; i < NODE_NR; i++) {
-      validateThrottle(DelayedTransition.getInstancePatitionTransitionTimes(),
-          _participants[i].getInstanceName(), 1);
+      Assert.assertTrue(getMaxParallelTransitionCount(DelayedTransition.getInstancePatitionTransitionTimes(), _participants[i].getInstanceName()) <= 1);
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java]: Format?

File: helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java [hunk 15]
```diff
@@ -211,8 +217,54 @@ public void testANYtypeThrottle() throws InterruptedException {
...
+      }
+    });
+
+    ClusterLiveNodesVerifier clusterLiveNodesVerifier = new ClusterLiveNodesVerifier(
+        _gZkClient, CLUSTER_NAME, Lists.transform(Arrays.asList(_participants), MockParticipantManager::getInstanceName));
+    Assert.assertTrue(clusterLiveNodesVerifier.verifyByZkCallback(1000));
+    Assert.assertTrue(_clusterVerifier.verifyByPolling());
+
+    for (int i = 0; i < NODE_NR; i++) {
+      _participants[i].syncStop();
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java]: Just be careful to check that _participants[i] != null and _participants[i].isConnected().
If you call syncStop() twice, I think the program hangs. So make sure all of these Participants are running before calling syncStop() on all of them.

Also please add a TestHelper.verify() with the check for LiveInstances to make sure that the number of LiveInstance ZNodes is 0.

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestStateTransitionThrottleController.java (hunk 11 above)
Comment (i3wangyi) [reply helix-core/src/test/java/org/apache/helix/controller/stages/TestStateTransitionThrottleController.java]: Added the comment. "Mock" doesn't suit the use case here because it mainly refers to "mocking the class and mutate some behaviors at will"

File: helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java (hunk 15 above)
Comment (i3wangyi) [reply helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java]: Sounds good. Added the verifier in the @aftermethod so every test needs to check if the cleanup work is finished.

**Comment by i3wangyi** [comment]
The PR is ready to merge into master, approved by @narendly
