### PR TITLE
TASK: Fix forceDelete for jobs in JobQueue

### LINKED ISSUE #445: TASK: Fix forceDelete for jobs in JobQueue
We observed that the force delete functionality doesn't really work when the job is running, saying that the job is currently running. Force delete should go through regardless of the current job status.

### PR DESCRIPTION
**Pull request by narendly**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #445 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

We observed that the force delete functionality doesn't really work when the job is running, saying that the job is currently running. Force delete should go through regardless of the current job status.
Changelist:
1. Change the semantics in deleteJobFromQueue
2. Add an integration test: TestDeleteJobFromJobQueue

### Tests

- [x] The following tests are written for this issue:

TestDeleteJobFromJobQueue

- [x] The following is the result of the "mvn test" command on the appropriate module:

[ERROR] Tests run: 850, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3,198.931 s <<< FAILURE! - in TestSuite
[ERROR] testNoDoubleAssign(org.apache.helix.integration.task.TestNoDoubleAssign)  Time elapsed: 14.736 s  <<< FAILURE!
java.lang.AssertionError: expected:<false> but was:<true>
	at org.apache.helix.integration.task.TestNoDoubleAssign.testNoDoubleAssign(TestNoDoubleAssign.java:119)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestNoDoubleAssign.testNoDoubleAssign:119 expected:<false> but was:<true>
[INFO] 
[ERROR] Tests run: 850, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  53:23 min
[INFO] Finished at: 2019-09-03T19:29:08-07:00
[INFO] ------------------------------------------------------------------------

$ mvn test -Dtest=TestNoDoubleAssign

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 24.569 s - in org.apache.helix.integration.task.TestNoDoubleAssign
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- [x] My diff has been formatted using helix-style.xml

### CODE REVIEW

File: helix-core/src/test/java/org/apache/helix/integration/task/TestDeleteJobFromJobQueue.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+    String jobQueueName = TestHelper.getTestMethodName();
+
+    // Create two jobs: job1 will complete fast, and job2 will be stuck in progress. The idea is to
+    // force-delete a stuck job (job2).
+    JobConfig.Builder jobBuilder = JobConfig.Builder.fromMap(WorkflowGenerator.DEFAULT_JOB_CONFIG)
+        .setMaxAttemptsPerTask(1).setWorkflow(jobQueueName)
+        .setJobCommandConfigMap(ImmutableMap.of(MockTask.JOB_DELAY, "10"));
+    JobConfig.Builder jobBuilder2 = JobConfig.Builder.fromMap(WorkflowGenerator.DEFAULT_JOB_CONFIG)
+        .setMaxAttemptsPerTask(1).setWorkflow(jobQueueName)
+        .setJobCommandConfigMap(ImmutableMap.of(MockTask.JOB_DELAY, "100000")).setTimeout(100000);
```
Comment (alirezazamani) [inline helix-core/src/test/java/org/apache/helix/integration/task/TestDeleteJobFromJobQueue.java]: Don't we need setTimeoutPerTask in this case? DEFAULT_JOB_CONFIG has 10s for task timeout.

File: helix-core/src/main/java/org/apache/helix/task/TaskDriver.java [hunk 2]
```diff
@@ -262,32 +262,32 @@ public void deleteJob(final String queue, final String job, boolean forceDelete)
...
     }
 
-    if (!workflowCfg.isJobQueue()) {
-      throw new IllegalArgumentException(queue + " is not a queue!");
+    if (jobQueueConfig == null) {
+      throw new IllegalArgumentException(
+          String.format("JobQueue %s's config is not found!", queue));
+    }
+
+    if (!jobQueueConfig.isJobQueue()) {
```
Comment (alirezazamani) [inline helix-core/src/main/java/org/apache/helix/task/TaskDriver.java]: I think it is better to do this check at the beginning of the function?

File: helix-core/src/main/java/org/apache/helix/task/TaskDriver.java [hunk 3]
```diff
@@ -262,32 +262,32 @@ public void deleteJob(final String queue, final String job, boolean forceDelete)
...
+      if (!TaskUtil.removeJob(_accessor, _propertyStore, job)) {
+        LOG.info("Failed to delete job: {} from queue: {}", job, queue);
+        throw new HelixException("Failed to delete job: " + job + " from queue: " + queue);
       }
       return;
     }
 
-    if (!workflowCfg.isJobQueue()) {
-      throw new IllegalArgumentException(queue + " is not a queue!");
+    if (jobQueueConfig == null) {
```
Comment (alirezazamani) [inline helix-core/src/main/java/org/apache/helix/task/TaskDriver.java]: I think it is better to do this check at the beginning of the function?

Comment (narendly) [reply helix-core/src/main/java/org/apache/helix/task/TaskDriver.java]: We want to do this check after we do force delete. For example, your queue might have been removed but for some reason the job ZNodes were not. In that case, you still want to be able to delete job ZNodes.

File: helix-core/src/main/java/org/apache/helix/task/TaskDriver.java (hunk 2 above)
Comment (narendly) [reply helix-core/src/main/java/org/apache/helix/task/TaskDriver.java]: I replied above.

File: helix-core/src/test/java/org/apache/helix/integration/task/TestDeleteJobFromJobQueue.java [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+    _numPartitions = 1;
+    super.beforeClass();
+  }
+
+  @Test
+  public void testForceDeleteJobFromJobQueue() throws InterruptedException {
+    String jobQueueName = TestHelper.getTestMethodName();
+
+    // Create two jobs: job1 will complete fast, and job2 will be stuck in progress. The idea is to
+    // force-delete a stuck job (job2).
```
[the remark this answers is not in the document]
Comment (narendly) [reply helix-core/src/test/java/org/apache/helix/integration/task/TestDeleteJobFromJobQueue.java]: Added.

File: helix-core/src/test/java/org/apache/helix/integration/task/TestDeleteJobFromJobQueue.java (hunk 1 above)
Comment (narendly) [reply helix-core/src/test/java/org/apache/helix/integration/task/TestDeleteJobFromJobQueue.java]: No need. This test should complete before 10 seconds have elapsed.

File: helix-core/src/test/java/org/apache/helix/integration/task/TestDeleteJobFromJobQueue.java [hunk 5]
```diff
@@ -0,0 +1,75 @@
...
+
+    JobQueue.Builder jobQueue = TaskTestUtil.buildJobQueue(jobQueueName);
+    jobQueue.enqueueJob("job1", jobBuilder);
+    jobQueue.enqueueJob("job2", jobBuilder2);
+    _driver.start(jobQueue.build());
+    _driver.pollForJobState(jobQueueName, TaskUtil.getNamespacedJobName(jobQueueName, "job2"),
+        TaskState.IN_PROGRESS);
+
+    try {
+      _driver.deleteJob(jobQueueName, "job2");
```
[the remark this answers is not in the document]
Comment (narendly) [reply helix-core/src/test/java/org/apache/helix/integration/task/TestDeleteJobFromJobQueue.java]: That is what this try-catch block is doing.

File: helix-core/src/test/java/org/apache/helix/integration/task/TestDeleteJobFromJobQueue.java [hunk 6]
```diff
@@ -0,0 +1,75 @@
...
+    } catch (IllegalStateException e) {
+      // Expect IllegalStateException because job2 is still in progress
+    }
+
```
[the remark this answers is not in the document]
Comment (narendly) [reply helix-core/src/test/java/org/apache/helix/integration/task/TestDeleteJobFromJobQueue.java]: Good comment. Added the checks :)

**Comment by narendly** [comment]
This PR is ready to be merged, approved by @alirezazamani @dasahcc .
