### PR TITLE
Replace deprecated verifier with new set of Verifiers

### LINKED ISSUE #2485: TestDistributedControllerManager is using Deprecated ClusterStateVerifier
### Describe the bug
We are using the deprecated ClusterStateVerifier tool in the test TestDistributedControllerManager. The test is valid but needs to use the newer replacement class, BestPossibleExternalViewVerifier.

### To Reproduce
Here is the link to the code:
https://github.com/apache/helix/blob/master/helix-core/src/test/java/org/apache/helix/integration/manager/TestDistributedControllerManager.java
and here is the verifier class which has the comment that it has been deprecated:

/**
 * This class is deprecated, please use dedicated verifier classes, such as
 * BestPossibleExternalViewVerifier, etc, in tools.ClusterVerifiers.
 */
@Deprecated
public class ClusterStateVerifier {

Here is the link to the code:
https://github.com/apache/helix/blob/master/helix-core/src/main/java/org/apache/helix/tools/ClusterStateVerifier.java#L79

### PR DESCRIPTION
**Pull request by desaikomal**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:
Fixes #2485 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
While debugging the failure for the test case in DistributedController test case, realized we are using deprecated verifier. So let us first use the right verifier and see if it helps with resolving the temporary failures. These are all integration tests which depends on ZK timing and so not sure if just replacing correct verifier will help. But first order problem is to use right code.

### Tests

- [] The following tests are written for this issue:

(List the names of added unit/integration tests)

- The following is the result of the "mvn test" command on the appropriate module:
I created a branch and ran the test 4 times to make sure that there is no regression with using different verifier.
Here is the link to the branch with testing:
https://github.com/desaikomal/helix/pull/2
- failure were in different test cases.

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Review by parakhnr — APPROVED** [review]

File: helix-core/src/test/java/org/apache/helix/integration/manager/TestDistributedControllerManager.java [hunk 1]
```diff
@@ -71,18 +72,18 @@ public void simpleIntegrationTest() throws Exception {
...
-    boolean result = ClusterStateVerifier
-        .verifyByZkCallback(new BestPossAndExtViewZkVerifier(ZK_ADDR, clusterName));
+    boolean result = verifier.verifyByZkCallback();
     Assert.assertTrue(result);
 
     // disconnect first distributed-controller, and verify second takes leadership
     distributedControllers[0].disconnect();
 
     // verify leader changes to localhost_12919
     Thread.sleep(100);
```
[the remark this answers is not in the document]
Comment (desaikomal) [reply helix-core/src/test/java/org/apache/helix/integration/manager/TestDistributedControllerManager.java]: @parakhnr - can you please review one more time?

File: helix-core/src/test/java/org/apache/helix/integration/manager/TestDistributedControllerManager.java [hunk 2]
```diff
@@ -82,8 +82,9 @@ public void simpleIntegrationTest() throws Exception {
     distributedControllers[0].disconnect();
 
     // verify leader changes to localhost_12919
-    Thread.sleep(100);
-    result = verifier.verifyByZkCallback();
+    result = TestHelper.verify(() -> {
+      return verifier.verifyByZkCallback();
+    }, 100);
```
Comment (parakhnr) [inline helix-core/src/test/java/org/apache/helix/integration/manager/TestDistributedControllerManager.java:87]: Actually 100, won't help much, the verify method does the following:
1. Record startTime = currentTime
2. Invoke verifier.verifyByZkCallback()
    2.1 Wait for max 30 seconds(default timeout) for the state to be verified
3.  If currentTime - startTime > 100 repeat 1.

So I think we need to have time out > (30 seconds + some buffer) if we want the verification to be retried. If we don't want the verification to be retried(which is the current implementation), then we need to use `verifier.verifyByZkCallback(30seconds default timeout + 100 milliseconds)` instead of `verifier.verifyByZkCallback()`. 

Apologies for the previous comment as I didn't read through the `TestHelper.verify` method code.

Comment (desaikomal) [reply helix-core/src/test/java/org/apache/helix/integration/manager/TestDistributedControllerManager.java:87]: I think, i don't need it re=tried as earlier code just did sleep and moved on. 
This is also the reason, I like to stick to the scope of the change to be what I set out with.

Comment (parakhnr) [reply helix-core/src/test/java/org/apache/helix/integration/manager/TestDistributedControllerManager.java:87]: Ok. Lets stick to original one or use callback with timeout that has 30 seconds + 100 milliseconds set.

**Review by parakhnr — APPROVED** [review]

**Review by qqu0127 — APPROVED** [review]

**Comment by desaikomal** [comment]
Thanks @qqu0127 and @parakhnr for review. This change has been approved by @parakhnr and @qqu0127.
Commit message: Replace the deprecated verifier with new set of verifiers.
