### PR TITLE
Return "name" field as VM name in Azure environment

### LINKED ISSUE #1339: Return "name" field in AIMS response as vm name in Azure cloud environment
### Describe the bug
When Helix uses auto registration feature to get VM metadata information from Azure, the name of that VM is in "name" field rather than "vmId" field. "vmId" is more like a serial number, and won't provide much information for users. Details in this page: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service

### To Reproduce
Currently code returns vmId as instance name.

### Expected behavior
Return "name" field instead.

### PR DESCRIPTION
**Pull request by zhangmeng916**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:

Fix #1339 

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

When Helix uses auto registration feature to get VM metadata information from Azure, the name of that VM is in "name" field rather than "vmId" field. "vmId" is more like a serial number, and won't provide much information for users. Details in this page: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service
This PR fixed this issue and also some other minor typos

### Tests

- [X] The following is the result of the "mvn test" command on the appropriate module:
[WARNING] Tests run: 1200, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 4,361.725 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[WARNING] Tests run: 1200, Failures: 0, Errors: 0, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:12 h
[INFO] Finished at: 2020-09-02T22:59:41-07:00

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/cloud/azure/AzureCloudInstanceInformationProcessor.java [hunk 1]
```diff
@@ -49,14 +49,14 @@
   private final CloseableHttpClient _closeableHttpClient;
   private final HelixCloudProperty _helixCloudProperty;
   private final String COMPUTE = "compute";
-  private final String INSTANCE_NAME = "vmId";
+  private final String INSTANCE_NAME = "name";
```
Comment (pkuwm) [inline helix-core/src/main/java/org/apache/helix/cloud/azure/AzureCloudInstanceInformationProcessor.java:52]: If they are constants, they should be `static final`?

**Review by pkuwm — APPROVED** [review]

**Comment by zhangmeng916** [comment]
This PR is ready to be merged, approved by @pkuwm 
Final commit message:
Return "name" field as VM name in Azure cloud environment
