### PR TITLE
Change participant message monitor to use dynamic metric

### LINKED ISSUE #1683: Convert legacy static monitors to use dynamic metrics
### Describe the bug
There are some legacy code in metrics component that use static monitor to report interested metrics. As we know, those static metrics are hard to maintain and cause a lot of boilerplate code. We should convert them to use our dynamic metric framework so that our code base is clean and concise.

### To Reproduce
Check Helix code base for static monitors. 

### Expected behavior
After conversion, all metrics should work the same as before.

### PR DESCRIPTION
**Pull request by zhangmeng916**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:
Fixed #1683 

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:
ParticipantMessageMonitor used a static metric implementation. To uniform our metrics in Helix-core, we would like to convert all static metrics to dynamic metric framework. The PR serves as an example for this cleanup work. 

### Tests
helix-core
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   TestResourceChangeDetector.testResetSnapshots:453 expected:<0> but was:<1>
[ERROR]   TestPauseSignal.testPauseSignal:106 expected:<true> but was:<false>
[INFO]
[ERROR] Tests run: 1264, Failures: 2, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:35 h
[INFO] Finished at: 2021-03-24T13:38:47-07:00

(If CI test fails due to known issue, please specify the issue and test PR locally. Then copy & paste the result of "mvn test" to here.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ParticipantMessageMonitor.java [hunk 1]
```diff
@@ -19,86 +19,93 @@
...
+  private SimpleDynamicMetric<Long> _pendingMessages;
+
   /**
    * The current processed state of the message
    */
   public enum ProcessedMessageState {
-    DISCARDED,
-    FAILED,
-    COMPLETED
+    DISCARDED, FAILED, COMPLETED
```
Comment (dasahcc) [inline helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ParticipantMessageMonitor.java:49]: NIT: I think our formatter has problem. Let manually fix this first.

File: metrics-common/src/main/java/org/apache/helix/monitoring/mbeans/dynamicMBeans/DynamicMBeanProvider.java [hunk 2]
```diff
@@ -227,6 +227,14 @@ protected void incrementSimpleDynamicMetric(SimpleDynamicMetric<Long> metric, lo
     metric.updateValue(metric.getValue() + value);
   }
 
+  /**
+   * NOTE: This method is not thread-safe nor atomic.
+   * Decrement the value of a given SimpleDynamicMetric with input value.
+   */
+  protected void decrementSimpleDynamicMetric(SimpleDynamicMetric<Long> metric, long value) {
```
Comment (dasahcc) [inline metrics-common/src/main/java/org/apache/helix/monitoring/mbeans/dynamicMBeans/DynamicMBeanProvider.java:234]: NIT: Is this necessary? We can increase with negative value so minimize the APIs.

File: helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ParticipantMessageMonitor.java (hunk 1 above)
Comment (zhangmeng916) [reply helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ParticipantMessageMonitor.java:49]: Yeah, seems caused by formatter. Changed back.

**Review by dasahcc — APPROVED** [review]

**Comment by zhangmeng916** [comment]
This PR is ready to be merged. Approved by @dasahcc 
Final commit message: "Change participant message monitor to use dynamic metric"
