### PR TITLE
Fix flaky test testGetChildrenOnLargeNumChildren

### LINKED ISSUE #1193: Flaky test testGetChildrenOnLargeNumChildren
The test uses reflection to change `ClientCnxn.packetLen`. It runs successfully until the commit where it is added. And after later commits are added, the test becomes flaky. Because `ClientCnxn.packetLen` value is not changed in zookeeper object that zkClient uses.

To fix it and make it simple, replace reflection with the naive way: create 110K children. To save the creation time, use zk transaction api to batch the znodes creation. Now the creation time is reduced from 170s to 4s.

### PR DESCRIPTION
**Pull request by pkuwm**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1193 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

The test testGetChildrenOnLargeNumChildren becomes flaky after more commits are checked in.

### Tests

- [ ] The following tests are written for this issue:

(List the names of added unit/integration tests)

- [x] The following is the result of the "mvn test" command on the appropriate module:

```
zookeeper-api

[INFO] Tests run: 38, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 62.807 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 38, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:07 min
[INFO] Finished at: 2020-07-30T17:10:34-07:00
[INFO] ------------------------------------------------------------------------
```

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation (Optional)

- [ ] In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Code Quality

- [x] My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java [hunk 1]
```diff
@@ -868,59 +864,38 @@ public void testAsyncWriteOperations() {
...
-      childrenLimitField.set(null, originChildrenLimit);
-      childrenLimitField.setAccessible(isChildrenLimitAccessible);
-
-      modifiersField.setAccessible(isModifierAccessible);
+      _zkClient.close();
+      _zkClient = new ZkClient(ZkTestBase.ZK_ADDR);
 
       Assert.assertTrue(TestHelper.verify(() -> {
-        _zkClient.deleteRecursively(path);
+        _zkClient.delete(path);
```
Comment (kaisun2000) [inline zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:898]: can we delete parent path here without child node deleted?

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java [hunk 2]
```diff
@@ -868,59 +864,38 @@ public void testAsyncWriteOperations() {
    * Tests getChildren() when there are an excessive number of children and connection loss happens,
    * the operation should terminate and exit retry loop.
    */
-  @Test
+  @Test(timeOut = 30L)
```
Comment (kaisun2000) [inline zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:867]: why do we need this? is it 30sec?

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java [hunk 3]
```diff
@@ -119,19 +115,6 @@
   // ZkEventThread. Otherwise the retry request might block the normal event processing.
   protected final ZkAsyncRetryThread _asyncCallRetryThread;
 
-  static {
```
Comment (kaisun2000) [inline zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:122]: what is the difference of using this static block vs initalization at declaration?

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 1 above)
Comment (pkuwm) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:898]: No, we cannot because there would be node not empty exception.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 2 above)
Comment (pkuwm) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: `30 * 1000L ms`.

A good practice would be: if the test relies on an external system(zk here), it'd be good to have a timeout. Otherwise, if the connection hangs, the test also hangs. Eg., if the operation `multi()` hangs since it is sync, it hangs there forever?

Timeout makes the test process continue for other tests.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java (hunk 3 above)
Comment (pkuwm) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:122]: If you read the comment: // Set it here for unit test to use reflection to change value	
    // because compilers optimize constants by replacing them inline.

Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:122]: I see.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 2 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: Another thing is that in these 4 secs, is it possible another test would time out the session of _zkClient. Shall we use a dedicated ZkClient by creating one and later close it.

Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: also for safety, make it 60secs?

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 1 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:898]: My concern is this:

if using deleteRecursively(), it won't work because list all the children znode name would cause "marshalling" error as what happened in GCN, right?

if using delete as you do here, I think it would throw another exception as not empty. So this does not work here. Or am I missing something?

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java [hunk 4]
```diff
@@ -868,59 +864,38 @@ public void testAsyncWriteOperations() {
...
-    String path = "/" + TestHelper.getTestMethodName();
-    // Create 5 children to make packet length of children exceed 150 bytes
+    // Create 110K children to make packet length of children exceed 4 MB
     // and cause connection loss for getChildren() operation
-    for (int i = 0; i < 5; i++) {
-      _zkClient.createPersistent(path + "/" + UUID.randomUUID().toString(), true);
+    String path = "/" + TestHelper.getTestMethodName();
+    int toCreateChildrenCount = 110;
+
+    _zkClient.createPersistent(path);
```
Comment (kaisun2000) [inline zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:874]: How about let us construct a new zkclient here. Is it possible _zkClient would be session timeout by another test or thread?

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java [hunk 5]
```diff
@@ -868,59 +864,38 @@ public void testAsyncWriteOperations() {
    * Tests getChildren() when there are an excessive number of children and connection loss happens,
    * the operation should terminate and exit retry loop.
    */
-  @Test
+  @Test(timeOut = 30 * 1000L)
```
Comment (kaisun2000) [inline zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:867]: 60 secs?

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 2 above)
Comment (pkuwm) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: This _zkClient is created within this class. While this test is running, there is no other thread referencing this _zkClient to close it.

I considered using another zkClient. But it just adds one more connection to so for this case there will be two connections at the same time. I believe reuse this one is good enough.

I ran it in my laptop as well, 30s is good enough. If it's more than 30s, something is wrong and it should timeout to fail.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 4 above)
Comment (pkuwm) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:874]: Replied above. Won't be closed by another thread. It is created in this class, not from a base class.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 1 above)
Comment (pkuwm) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: delete() returns boolean. Should handle `ZkException` here as I've removed deleteRecursively().

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 2 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: You laptop runs on SSD. Desktop or TMC machines can be slower. Leave some room for error is safe here IMO.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 1 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: So in this case, it would always throw exception, right? 

Then why bother. Just leave the znode there anyway.

Comment (pkuwm) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: As a good practice, a unit test should cleanup itself and avoid other tests.
It won't always close. If you carefully understand the code, you'll find the tips of using ephemeral nodes and closing the zkClient to delete the ephemeral nodes for cleanup.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 2 above)
Comment (pkuwm) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: 30s has already good room for this test. In my tests, it completes in ~5s. If it really exceeds 30s, maybe 60s don't even help.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 1 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: My question is that is this exception always thrown? I believe it would always be thrown. Can you verify?

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 2 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: Can you the whole test under helix in desktop to make sure this 30s is safe?

Comment (pkuwm) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: I did zookeeper-api in both desktop and laptop. Is this what you meant?

Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: No, run all test from helix. That is what TMC is doing I guess. This is to simulate that test environment. We don't want that you fix this one but later it turned out this test still not working over there. Note the cost over there is way higher than changing it here. 

In fact, I noticed in our test, there are failed test due to Timed out from time to time. I don't think it is a good idea to add a time out here. 

By the way, can you re-open this comment thread.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 1 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: Can we also re-open this comment thread?

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 2 above)
Comment (pkuwm) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: I actually didn't resolve this thread... I intended to keep it open for discussion.

Running all helix tests is not necessary. This is a separate module. Even running in the test machine, tests in different modules are independent.

Timeout is good practice. Just an example. https://github.com/apache/zookeeper/blob/fe940cdd8fb23ba09684cefb73233d570f4a20fa/zookeeper-server/src/test/java/org/apache/zookeeper/server/ZooKeeperServerMainTest.java#L165

How could you ensure 60s would not timeout then? Then how about 10 minutes, 1 hour?

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 1 above)
Comment (pkuwm) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: What do you mean by `always thrown`?

Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: `String path = "/" + TestHelper.getTestMethodName()` is path.

Now at the time this line of code `_zkClient.delete(path);` , there are a lot of znode underlying this `path`. So the delete should always fail, right?  Or am I understanding this wrong?

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 2 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: Yes, then remove this timeout. The test has a default timeout 300sec. In my opinion, relying on 300sec default is much safer. Testing under your own laptop may not fit a lot other environment.

See this:

[ERROR] testLostZkConnection(org.apache.helix.integration.TestZkConnectionLost) Time elapsed: 300.015 s <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testLostZkConnection() didn't finish within the time-out 300000

Comment (pkuwm) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: Please let me remind you that the default timeout 300sec is set only for helix-core's tests, not in zookeeper-api.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 1 above)
Comment (pkuwm) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: @kaisun2000 I've replied you: they are ephemeral znodes.
> It won't always throw exception. If you carefully understand the code, you'll find the tips of using ephemeral nodes and closing the zkClient to delete the ephemeral nodes for cleanup. The exception handling here is just in case zk server doesn't remove ephemeral nodes yet.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java [hunk 6]
```diff
@@ -868,60 +864,41 @@ public void testAsyncWriteOperations() {
...
-    for (int i = 0; i < 5; i++) {
-      _zkClient.createPersistent(path + "/" + UUID.randomUUID().toString(), true);
+    String path = "/" + TestHelper.getTestMethodName();
+
+    _zkClient.createPersistent(path);
+
+    for (int i = 0; i < 110; i++) {
+      List<Op> ops = new ArrayList<>(1000);
+      for (int j = 0; j < 1000; j++) {
+        String child = path + "/" + UUID.randomUUID().toString();
```
Comment (narendly) [inline zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:878]: Nit: childPath

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java [hunk 7]
```diff
@@ -868,60 +864,41 @@ public void testAsyncWriteOperations() {
...
+        ops.add(Op.create(child, new byte[0], ZooDefs.Ids.OPEN_ACL_UNSAFE, CreateMode.EPHEMERAL));
+      }
+      // Reduce total creation time by batch creating znodes
+      _zkClient.multi(ops);
     }
 
     try {
       _zkClient.getChildren(path);
-      Assert.fail("Should not successfully get children.");
+      Assert.fail("Should not successfully get children because of connection loss.");
```
Comment (narendly) [inline zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:887]: Nit: let's say this a little more clearly:

Something on the lines of "Should fail because listing 110K znodes with UUID names should cause packet length exceeded error, causing a connection loss."

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java [hunk 8]
```diff
@@ -868,60 +864,41 @@ public void testAsyncWriteOperations() {
...
-
-      modifiersField.setAccessible(isModifierAccessible);
+      _zkClient.close();
+      _zkClient = new ZkClient(ZkTestBase.ZK_ADDR);
 
       Assert.assertTrue(TestHelper.verify(() -> {
-        _zkClient.deleteRecursively(path);
-        return !_zkClient.exists(path);
+        try {
+          return _zkClient.delete(path);
```
Comment (narendly) [inline zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:898]: Shouldn't you delete recursively? Wouldn't this fail because of children nodes?

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 1 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: I see. Did not notice this ephemeral node. So closing the _zkClient delete the nodes. The second delete is just to delete the parent path. This looks good.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 8 above)
Comment (pkuwm) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:898]: They are ephemeral nodes and closing the zkClient deletes the ephemeral nodes for cleanup.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 2 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: where is the place to config the 300secs. Shall we just configure the same in zooscalability-api?

**Comment by kaisun2000** [comment]
Other than timeout which may not be conservative enough, it looks good. The idea of using transaction and ephemeral node is brilliant.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 2 above)
Comment (pkuwm) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: It is in test config file: `testng.xml`

Configuring the timeout for test suit for zookeeper-api is out of scope of this PR. If we want to do that, I would prefer to do it in another PR.

**Comment by pkuwm** [comment]
This PR is ready to be merged, approved by @kaisun2000 
```
testGetChildrenOnLargeNumChildren becomes flaky after more commits are checked in because of reflection doesn't work as expected. This commit fixes it by replacing reflection with creating 110K children for the test.
```

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 8 above)
Comment (narendly) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:903]: I think this is fine for testing purposes, but here are some scenarios we can think about:

1. doesn't the packet len error cause the session to be terminated? Or does your fix change that behavior? In this case if my assumption is true, the client that created the ephemeral nodes will lose its session and the ephemerals tied to the session will be gone anyway, so the nodes will be gone before zkclient.close()?

2. this is a rare scenario, but sometimes we observe in-memory local clients lose connection for some unknown reason. What impact would that have on the test?

If we really wanted to be right and thorough, I would write persistent nodes, and check that the numChildren field comes out to 110K from Stats with an Assert statement, and then do the explicit deletion at the end. This would guard against any potential client-side glitches and failures.
