### PR TITLE
Fix test testDropInstance

### LINKED ISSUE #1051: testDropInstance: java.lang.UnsupportedOperationException: Create ephemeral nodes using SharedZkClient
Unit tests fail because ZkBaseDataAccessor is created using a shared zkclient but the ZkBaseDataAccessor is used to create a live instance. But shared zkclient  doesn't support creating a live instance.

```
START testDropInstance at Sun May 31 04:28:16 PDT 2020
START TestClusterSetup_testDropInstance at Sun May 31 04:28:16 PDT 2020
5689089 [TestNGInvoker-testDropInstance()] ERROR org.apache.helix.manager.zk.ZkBaseDataAccessor  - Exception while creating path: /TestClusterSetup_testDropInstance/LI
VEINSTANCES/localhost_12918
java.lang.UnsupportedOperationException: Create ephemeral nodes using SharedZkClient is not supported.
        at org.apache.helix.zookeeper.impl.factory.SharedZkClientFactory$InnerSharedZkClient.create(SharedZkClientFactory.java:198)
        at org.apache.helix.zookeeper.zkclient.ZkClient.create(ZkClient.java:604)
        at org.apache.helix.manager.zk.ZkBaseDataAccessor.doCreate(ZkBaseDataAccessor.java:273)
        at org.apache.helix.manager.zk.ZkBaseDataAccessor.doSet(ZkBaseDataAccessor.java:354)
        at org.apache.helix.manager.zk.ZkBaseDataAccessor.set(ZkBaseDataAccessor.java:322)
        at org.apache.helix.manager.zk.ZkBaseDataAccessor.set(ZkBaseDataAccessor.java:314)
        at org.apache.helix.manager.zk.ZKHelixDataAccessor.setProperty(ZKHelixDataAccessor.java:169)
        at org.apache.helix.tools.TestClusterSetup.testDropInstance(TestClusterSetup.java:365)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
        at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
        at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by pkuwm**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1051 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Test testDropInstance doesn't assert expected exception and ignores the unexpected behavior. ZkBaseDataAccessor is created using a shared zkclient to create a live instance. The creation fails because shared zkclient doesn't support creating a live instance.

This PR addresses this problem by creating a dedicated zkclient in ZkBaseDataAccessor to create a live instance.

### Tests

- [ ] The following tests are written for this issue:

N/A

- [x] The following is the result of the "mvn test" command on the appropriate module:

There is no main code change, so just run this test class including testDropInstance. No more error message.

```
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 41.596 s - in org.apache.helix.tools.TestClusterSetup
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  47.458 s
[INFO] Finished at: 2020-06-02T19:54:34-07:00
[INFO] ------------------------------------------------------------------------
```

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation (Optional)

- [ ] In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Code Quality

- [x] My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/test/java/org/apache/helix/tools/TestClusterSetup.java [hunk 1]
```diff
@@ -356,51 +360,57 @@ public void testDropInstance() throws Exception {
...
+          new String[]{"--zkSvr", ZK_ADDR, "--dropNode", clusterName, instanceAddress});
+
+      Assert.assertNull(accessor.getProperty(keyBuilder.instanceConfig(instanceName)),
+          "Instance config should be dropped");
+      Assert.assertFalse(_gZkClient.exists(PropertyPathBuilder.instance(clusterName, instanceName)),
+          "Instance/host should be dropped");
+    } finally {
+      // Have to close the dedicated zkclient in accessor to avoid zkclient leakage.
+      accessor.getBaseDataAccessor().close();
+      TestHelper.dropCluster(clusterName, _gZkClient);
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/tools/TestClusterSetup.java:412]: Nit: usually a good idea to add a TestHelper.verify() to make sure the cluster has been dropped. This is recommended.

Comment (pkuwm) [reply helix-core/src/test/java/org/apache/helix/tools/TestClusterSetup.java:412]: Verified and updated.

**Comment by pkuwm** [comment]
This PR is ready to be merged, approved by @narendly 

```
Test testDropInstance doesn't assert expected HelixException, so when a live instance is not created, the test still passes. The reason is the test uses a sharedZkClient to create a live instance but fails.

This PR addresses this issue by creating a dedicated zkclient in ZkBaseDataAccessor to create a live instance.
```

File: helix-core/src/test/java/org/apache/helix/tools/TestClusterSetup.java [hunk 2]
```diff
@@ -356,51 +360,65 @@ public void testDropInstance() throws Exception {
         "MasterSlave", true); // do rebalance
 
     // add fake liveInstance
-    ZKHelixDataAccessor accessor =
-        new ZKHelixDataAccessor(clusterName, new ZkBaseDataAccessor<ZNRecord>(ZK_ADDR));
```
Comment (lei-xia) [inline helix-core/src/test/java/org/apache/helix/tools/TestClusterSetup.java:360]: Does this mean if user constructs a ZKHelixDataAccessor with a ZK-ADDR, they can create an ephemeral node before, but not anymore after they bump to 1.0.0?

Comment (pkuwm) [reply helix-core/src/test/java/org/apache/helix/tools/TestClusterSetup.java:360]: @lei-xia No, it doesn't. Before 1.0.0,  a ZKHelixDataAccessor with a ZK-ADDR is not able create an ephemeral node. It is also by default using a shared zkclient internally. The only difference is the type of exceptions: before 1.0.0, `HelixException` is thrown from sharedZkClient, while in 1.0.0, `UnsupportedOperationException` is thrown.

The root cause for this test is, even though a live instance(ephemeral node) is not created by the ZKHelixDataAccessor with a ZK-ADDR, the test still passes, because the test doesn't catch or verify the correct result.
