### PR TITLE
Fix adding a task to a job after deleting old tasks

### LINKED ISSUE #1874: Adding new task would be successful if there is gap in pIds
### Describe the bug
If some of the tasks from an IN_PROGRESS job have been removed before, new tasks cannot be added to the job because newly added tasks would have same pId to some of the existing tasks.

### To Reproduce
Assume a job has n tasks (pID = [0,n-1]). Remove one of the tasks with pId != n-1. After that new tasks cannot be added.

### Expected behavior
If there is a gap in the pIds, the new task should be added as the missing pId

### PR DESCRIPTION
**Pull request by alirezazamani**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:
Fixes #1874 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

In this PR, the issue of dynamically adding a task to a job which some of its tasks has been deleted before is being addressed.

### Tests

- [x] The following tests are written for this issue:
TestAddDeleteTask.testDeleteMiddleTaskAndAdd

- [x] The following is the result of the "mvn test" command on the appropriate module:
Helix-core:
```
[INFO] Tests run: 1284, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5,522.236 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1284, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.6:report (generate-code-coverage-report) @ helix-core ---
[INFO] Loading execution data file /home/anajari/my_repos/helix/helix-core/target/jacoco.exec
[INFO] Analyzed bundle 'Apache Helix :: Core' with 909 classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:32 h
[INFO] Finished at: 2021-09-16T08:47:28-07:00
[INFO] ------------------------------------------------------------------------
```
Helix-rest:
```
[INFO] Tests run: 179, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 126.955 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 179, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.6:report (generate-code-coverage-report) @ helix-rest ---
[INFO] Loading execution data file /home/anajari/my_repos/helix/helix-rest/target/jacoco.exec
[INFO] Analyzed bundle 'Apache Helix :: Restful Interface' with 79 classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:14 min
[INFO] Finished at: 2021-09-16T09:38:30-07:00
[INFO] ------------------------------------------------------------------------
```

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/task/ThreadCountBasedTaskAssignmentCalculator.java [hunk 1]
```diff
@@ -65,10 +66,26 @@ public ThreadCountBasedTaskAssignmentCalculator(TaskAssigner taskAssigner,
...
-      int nextPartition = jobCtx.getPartitionSet().size();
       if (!taskIdMap.containsKey(taskId)) {
+        int nextPartition = jobCtx.getPartitionSet().size();
+        if (missingPartitions.size()!=0) {
+          nextPartition = missingPartitions.iterator().next();
+          missingPartitions.remove(nextPartition);
+        }
         jobCtx.setTaskIdForPartition(nextPartition, taskId);
       }
     }
```
Comment (NealSun96) [inline helix-core/src/main/java/org/apache/helix/task/ThreadCountBasedTaskAssignmentCalculator.java:91]: Is this function exactly the same as the previous one? Is there a way we can combine them and not repeat?

File: helix-core/src/main/java/org/apache/helix/task/ThreadCountBasedTaskAssignmentCalculator.java [hunk 2]
```diff
@@ -65,10 +66,26 @@ public ThreadCountBasedTaskAssignmentCalculator(TaskAssigner taskAssigner,
...
+        }
+      }
+    }
     for (TaskConfig taskCfg : taskMap.values()) {
       String taskId = taskCfg.getId();
-      int nextPartition = jobCtx.getPartitionSet().size();
       if (!taskIdMap.containsKey(taskId)) {
+        int nextPartition = jobCtx.getPartitionSet().size();
+        if (missingPartitions.size()!=0) {
+          nextPartition = missingPartitions.iterator().next();
```
Comment (NealSun96) [inline helix-core/src/main/java/org/apache/helix/task/ThreadCountBasedTaskAssignmentCalculator.java:86]: Is it better to instead start with "the largest partitionID in jobCtx", and simply +1 every iteration? The fill-the-gaps approach seems unnecessarily complicated, if I'm not missing anything.

**Review by NealSun96 — CHANGES_REQUESTED** [review]

File: helix-core/src/main/java/org/apache/helix/task/ThreadCountBasedTaskAssignmentCalculator.java (hunk 1 above)
Comment (alirezazamani) [reply helix-core/src/main/java/org/apache/helix/task/ThreadCountBasedTaskAssignmentCalculator.java:91]: I thought about it actually. It was already duplicated. I think we keep a generic one for backward compatibility.

File: helix-core/src/main/java/org/apache/helix/task/ThreadCountBasedTaskAssignmentCalculator.java (hunk 2 above)
Comment (alirezazamani) [reply helix-core/src/main/java/org/apache/helix/task/ThreadCountBasedTaskAssignmentCalculator.java:86]: So the issue here is:
Let's assume we have these tasks [0,1,2,3,4]
Now the user deletes task 3 and we will have [0,1,2,4]
Now if the new task is being added, the size is 4 and the new pId will be 4 instead of 3. Hence the task would be be on context as we have a collision.
That is why we need to find the missing tasks.

Comment (junkaixue) [reply helix-core/src/main/java/org/apache/helix/task/ThreadCountBasedTaskAssignmentCalculator.java:86]: I have concerns for you are using missing partitions. Let's say user removed 3 as you mentioned, the job is not fully cancelled and still in running stage. If they add another task and you reuse missing partition 3 as the job id. Will that maps to existing non-cancelled task and make the system in a wired state?

Comment (alirezazamani) [reply helix-core/src/main/java/org/apache/helix/task/ThreadCountBasedTaskAssignmentCalculator.java:86]: That would not be the case. The design of the delete is to remove the task from context after it has been dropped completely and the current state is gone. It means after the cancellation we will remove context. In this case, it is safe to add a new tass with ID=3.

File: helix-core/src/main/java/org/apache/helix/task/ThreadCountBasedTaskAssignmentCalculator.java [hunk 3]
```diff
@@ -65,10 +66,26 @@ public ThreadCountBasedTaskAssignmentCalculator(TaskAssigner taskAssigner,
       Map<String, IdealState> idealStateMap) {
     Map<String, TaskConfig> taskMap = jobCfg.getTaskConfigMap();
     Map<String, Integer> taskIdMap = jobCtx.getTaskIdPartitionMap();
+    // Check if a gap exists in the context due to previouslys
```
Comment (junkaixue) [inline helix-core/src/main/java/org/apache/helix/task/ThreadCountBasedTaskAssignmentCalculator.java:69]: The function is exactly same as what we have in GenericTaskTaskAssignmentCalculator. Can we have two function wrapped in TaskAssignmentCalculator. So these two calculator just call it?

**Review by junkaixue — APPROVED** [review]
Overall, lgtm. Please address the previous comment.

File: helix-core/src/main/java/org/apache/helix/task/ThreadCountBasedTaskAssignmentCalculator.java (hunk 3 above)
Comment (alirezazamani) [reply helix-core/src/main/java/org/apache/helix/task/ThreadCountBasedTaskAssignmentCalculator.java]: Done.

**Comment by alirezazamani** [comment]
This PR is ready to be merged.

Final commit message:
Fix adding a task to a job after deleting old tasks

In this commit, the issue of dynamically adding a task to a job
in which some of its tasks have been deleted before is being
addressed.

File: helix-core/src/main/java/org/apache/helix/task/TaskAssignmentCalculator.java [hunk 4]
```diff
@@ -121,4 +122,39 @@ public static String getQuotaType(WorkflowConfig workflowConfig, JobConfig jobCo
...
+   * Get all the partitions/tasks that belong to the non-targeted job.
+   * @param jobCfg the task configuration
+   * @param jobCtx the task context
+   * @return set of partition numbers
+   */
+  public Set<Integer> getAllTaskPartitionsDefault(JobConfig jobCfg, JobContext jobCtx) {
+    Map<String, TaskConfig> taskMap = jobCfg.getTaskConfigMap();
+    Map<String, Integer> taskIdMap = jobCtx.getTaskIdPartitionMap();
+    // Check if a gap exists in the context due to previouslys
+    // removed tasks. If yes, the missing pIDs should be considered
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/task/TaskAssignmentCalculator.java:136]: This might cause problems if we want to debug for what happened to a removed task from the log. Ideally, we should avoid any overlap even with the removed task Id. However, I also understand that even we pick up the current max Id, there is no guarantee the next number has not been used before.
Let's keep the design.

One question, though, can we just use the task Id to replace task Partition Id completely? That will resolve all the problems, right?
