### PR TITLE
#334 Fix invoke rebalance by "touching" IdealState/ResourceConfig

### LINKED ISSUE #334: Invoke rebalance by "touching" IdealState/ResourceConfig
Current HelixDataAccesor updateProperty uses ZNRecordUpdater. It's merge logic just simply adding all elements when do a merge for ZNRecord. That could cause lot of duplication of listFields.
This impact the invokeRebalanceForResourceConfig. The fix will be implementing a customized updater.
  "id" : "Test",
  "simpleFields" : {
  },
  "mapFields" : {
  },
  "listFields" : {
    "0" : [ "1", "2", "3", "1", "2", "3", "1", "2", "3", "1", "2", "3", "1", "2", "3", "1", "2", "3", "1", "2", "3", "1", "2", "3" ]
  }
}

### PR DESCRIPTION
**Pull request by dasahcc**
**Issues**
(fixes #334   )

**Description**
Current HelixDataAccesor updateProperty uses ZNRecordUpdater. It's merge logic just simply adding all elements when do a merge for ZNRecord. That could cause lot of duplication of listFields.
This impact the invokeRebalanceForResourceConfig. The fix will be implementing a customized updater.

In this commit:
1. Fix invoke rebalance with customized updater.
2. Add comments for ZNRecord merge.
3. Add checks in TaskUtil to only trigger Workflow Config "touch" when purge job.
4. Add a test for RebalanceScheduler.

**Tests**
[INFO] Tests run: 835, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3,574.077 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 835, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 59:39 min
[INFO] Finished at: 2019-07-16T17:02:26-07:00
[INFO] Final Memory: 30M/1134M
[INFO] ------------------------------------------------------------------------

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/task/TaskUtil.java [hunk 1]
```diff
@@ -1021,11 +1021,21 @@ public static void purgeExpiredJobs(String workflow, WorkflowConfig workflowConf
...
-                resourceConfigs.get(0));
+            // Only touch workflow configs to minimize the risk of messing up regular resource config
+            // Also if there is no workflow configs, it is not necessary to trigger a rebalance for that.
+            for (ResourceConfig resourceConfig : resourceConfigs) {
+              try {
+                WorkflowConfig config = WorkflowConfig.fromHelixProperty(resourceConfig);
+                RebalanceScheduler.invokeRebalanceForResourceConfig(manager.getHelixDataAccessor(),
+                    config.getWorkflowId());
+                break;
+              } catch (IllegalArgumentException ex) {
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/task/TaskUtil.java]: Can we have a better way to check the config type?
If there is a WorkflowConfig with an illegal argument, this logic won't be able to tell the difference.

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/util/RebalanceScheduler.java [hunk 2]
```diff
@@ -138,7 +140,7 @@ public static void invokeRebalance(HelixDataAccessor accessor, String resource)
     PropertyKey key = accessor.keyBuilder().idealStates(resource);
     IdealState is = accessor.getProperty(key);
     if (is != null) {
-      if (!accessor.updateProperty(key, is)) {
+      if (!accessor.updateProperty(key, znRecord -> znRecord, is)) {
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/util/RebalanceScheduler.java]: I guess this might be hard for those who are not familiar with the accessor to understand. Please either comment with some detail, such as version based update, or just create a new call "idleUpdateProperty" or so.

Comment (dasahcc) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/util/RebalanceScheduler.java]: Prefer to leave a comment instead of having the complete class. Then that would be meaningless of using Java 8.

Comment (lei-xia) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/util/RebalanceScheduler.java]: +1 to have a comment, otherwise it could be confusing here.

File: helix-core/src/main/java/org/apache/helix/task/TaskUtil.java [hunk 3]
```diff
@@ -1021,11 +1021,21 @@ public static void purgeExpiredJobs(String workflow, WorkflowConfig workflowConf
           // concurrent write issue. It is possible that jobs got purged but there is no event to
           // trigger the pipeline to clean context.
           HelixDataAccessor accessor = manager.getHelixDataAccessor();
-          List<String> resourceConfigs =
-              accessor.getChildNames(accessor.keyBuilder().resourceConfigs());
+          List<ResourceConfig> resourceConfigs =
```
Comment (lei-xia) [inline helix-core/src/main/java/org/apache/helix/task/TaskUtil.java]: getChildNames is a single ZK call, but getChildValues are fetching the contents of all resource configs. If the volume of resource config is large, the performance impact (latency of this call + additional traffic to ZK) is no-ignorable.  Is that possible to have other way to do this? Or as my thinking, do we really need this touch at all?

File: helix-core/src/test/java/org/apache/helix/util/TestRebalanceScheduler.java [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+import org.apache.helix.common.ZkTestBase;
+import org.apache.helix.controller.rebalancer.util.RebalanceScheduler;
+import org.apache.helix.model.IdealState;
+import org.apache.helix.model.MasterSlaveSMD;
+import org.apache.helix.model.ResourceConfig;
+import org.testng.Assert;
+import org.testng.annotations.BeforeClass;
+import org.testng.annotations.Test;
+
+public class TestRebalanceScheduler extends ZkTestBase {
```
Comment (lei-xia) [inline helix-core/src/test/java/org/apache/helix/util/TestRebalanceScheduler.java]: will this test fail with old code?

Comment (dasahcc) [reply helix-core/src/test/java/org/apache/helix/util/TestRebalanceScheduler.java]: Yes, it failed with old updateProperty! That's why I was trying to fix the equals in ResourceConfig.

File: helix-core/src/main/java/org/apache/helix/task/TaskUtil.java (hunk 3 above)
Comment (dasahcc) [reply helix-core/src/main/java/org/apache/helix/task/TaskUtil.java]: It will impact the traffic, but it should not impact the latency of pipeline since this is in the asynchronized thread. I think we can revisit it when we are trying to get rid of all "touches".

File: helix-core/src/test/java/org/apache/helix/util/TestRebalanceScheduler.java [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+  public void beforeClass() throws Exception {
+    _gSetupTool.addCluster(CLUSTER_NAME, true);
+    _manager = HelixManagerFactory
+        .getZKHelixManager(CLUSTER_NAME, "Test", InstanceType.ADMINISTRATOR, ZK_ADDR);
+    _manager.connect();
+    _configAccessor = new ConfigAccessor(_gZkClient);
+  }
+
+  @Test
+  public void testInvokeRebalanceAndInvokeRebalanceForResource() {
```
Comment (lei-xia) [inline helix-core/src/test/java/org/apache/helix/util/TestRebalanceScheduler.java]: In your test, can you also validate the record has actually been changed, i.e, the version of znode is increased?

File: helix-core/src/main/java/org/apache/helix/task/TaskUtil.java (hunk 3 above)
Comment (lei-xia) [reply helix-core/src/main/java/org/apache/helix/task/TaskUtil.java]: Since you are getting rid of all "touches" anyway, other option is to keep the code as it is now without changing anything.  How do you think?

File: helix-core/src/test/java/org/apache/helix/util/TestRebalanceScheduler.java (hunk 5 above)
Comment (dasahcc) [reply helix-core/src/test/java/org/apache/helix/util/TestRebalanceScheduler.java]: Add version compare
