### PR TITLE
Fix TestZkConnectionLost

### LINKED ISSUE #1768: [Failed CI Test] testLostZkConnection(org.apache.helix.integration.TestZkConnectionLost)
This issue is created for tracking unstable test: testLostZkConnection(org.apache.helix.integration.TestZkConnectionLost)

### PR DESCRIPTION
**Pull request by NealSun96**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1768

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

The premise of TestZkConnectionLost is to test for the scenario of spotty ZK connection, and whether the connection retry delay is able to help Helix proceed.

The ZK server is shutdown repeatedly and restarted after 300ms. The connection retry delay was originally set at 1000ms. Based on local observation, it seems that the 1000ms delay is more than enough to wait until ZK server is restarted again, and the test failure is unable to be reproduced. In an effort to keep the test stable, the delay is increased to 5000ms. 

In the process, 2 unrelated errors are spotted with this test case: 1. the test is checking the wrong zk address for live instances, 2. the test is not asserting the check result. 

### Tests

- The following is the result of the "mvn test" command on the appropriate module:

Note: the test class is run for 20 times with consistent passing. 
```
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 441.106 s - in org.apache.helix.integration.TestZkConnectionLost
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Review by jiajunwang — APPROVED** [review]

**Comment by NealSun96** [comment]
This PR is ready to be merged, approved by @jiajunwang      
Final commit message:
## Fix TestZkConnectionLost ##
Fix TestZkConnectionLost by adding longer connection timeout and fixing logic that are incorrect.

File: helix-core/src/test/java/org/apache/helix/integration/TestZkConnectionLost.java [hunk 1]
```diff
@@ -139,13 +140,14 @@ public void run() {
...
-    System.setProperty(SystemPropertyKeys.ZK_SESSION_TIMEOUT, "1000");
+    System.setProperty(SystemPropertyKeys.ZK_WAIT_CONNECTED_TIMEOUT, "5000");
+    System.setProperty(SystemPropertyKeys.ZK_SESSION_TIMEOUT, "5000");
     try {
       String queueName = TestHelper.getTestMethodName();
       startParticipants(_zkAddr);
-      HelixDataAccessor accessor = new ZKHelixDataAccessor(CLUSTER_NAME, _baseAccessor);
-      TestHelper.verify(() -> {
+      HelixDataAccessor accessor =
+          new ZKHelixDataAccessor(CLUSTER_NAME, new ZkBaseDataAccessor(_zkAddr));
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/integration/TestZkConnectionLost.java:149]: Nit: Isn't this constructor deprecated?
