### PR TITLE
Change participant message monitor from static metric to dynamic metric

### LINKED ISSUE #1683: Convert legacy static monitors to use dynamic metrics
### Describe the bug
There are some legacy code in metrics component that use static monitor to report interested metrics. As we know, those static metrics are hard to maintain and cause a lot of boilerplate code. We should convert them to use our dynamic metric framework so that our code base is clean and concise.

### To Reproduce
Check Helix code base for static monitors. 

### Expected behavior
After conversion, all metrics should work the same as before.

### PR DESCRIPTION
**Pull request by zhangmeng916**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:
Fixed #1683 

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

ParticipantMessageMonitor used a static metric implementation. To uniform our metrics in Helix-core, we would like to convert all static metrics to dynamic metric framework. The PR serves as an example for this cleanup work.

### Tests

- [X] The following tests are written for this issue:

testReportMessageData

- The following is the result of the "mvn test" command on the appropriate module:

helix-core:
[ERROR] Failures:
[ERROR]   TestPauseSignal.testPauseSignal:106 expected:<true> but was:<false>
[ERROR]   TestDistributedControllerManager.simpleSessionExpiryTest:181->expireController:125 expected:<true> but was:<false>
[INFO]
[ERROR] Tests run: 1265, Failures: 2, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:36 h
[INFO] Finished at: 2021-04-06T16:56:00-07:00
[INFO] Final Memory: 28M/647M
### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ParticipantMessageMonitor.java [hunk 1]
```diff
@@ -19,10 +19,27 @@
  * under the License.
  */
 
-public class ParticipantMessageMonitor implements ParticipantMessageMonitorMBean {
-  public static final String PARTICIPANT_KEY = "ParticipantName";
+import java.util.ArrayList;
+import java.util.List;
```
Comment (dasahcc) [inline helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ParticipantMessageMonitor.java:23]: Question: was this formatted? If yes, then our formatter has problem.

**Review by dasahcc — APPROVED** [review]
Overall, LGTM

File: helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ParticipantMessageMonitor.java (hunk 1 above)
Comment (zhangmeng916) [reply helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ParticipantMessageMonitor.java:23]: Yes, it's formatted by `helix-style-intellij.xml`. What problem do you think we have here?

Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ParticipantMessageMonitor.java:23]: It seems good to me. @dasahcc, it is javax below, not java. If this is what concerns you : )

File: helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ParticipantMessageMonitorMBean.java [hunk 2]
```diff
@@ -21,7 +20,7 @@
 
 import org.apache.helix.monitoring.SensorNameProvider;
 
-
+@Deprecated
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ParticipantMessageMonitorMBean.java:23]: I think you can juat remove it, any other usages?

File: helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ParticipantStatusMonitor.java [hunk 3]
```diff
@@ -115,42 +122,36 @@ public void reportTransitionStat(StateTransitionContext cxt, StateTransitionData
...
+   * Build participant bean name
+   * @param participantName
+   * @return participant bean name
+   */
+  protected String getParticipantBeanName(String participantName) {
+    return String.format("%s=%s", PARTICIPANT_KEY, participantName);
   }
 
   public void shutDown() {
     if (_messageMonitor != null) {  // is participant
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ParticipantStatusMonitor.java:139]: These are not necessary anymore, right? Since you added the unregister() call below for _messageMonitor.

File: helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ParticipantMessageMonitorMBean.java (hunk 2 above)
Comment (zhangmeng916) [reply helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ParticipantMessageMonitorMBean.java:23]: Would like to keep a record. No need? No other usage at all.

Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ParticipantMessageMonitorMBean.java:23]: Let's remove it. This is 100% dead code. Leaving it in the repo will cause much confusing.

**Comment by zhangmeng916** [comment]
This PR is ready to be merged. Approved by @dasahcc 
Final commit message:
Change participant message monitor from static metric to dynamic metric
