### PR TITLE
Properly clean up TaskCurrentState sessions

### LINKED ISSUE #1735: TaskCurrentState Session Cleanup
### Describe the bug
Currently, old TaskCurrentState session cleanup is dependent on regular CurrentState sessions: for each session in the CurrentState path, the same session will be removed in the TaskCurrentState path. If there is a TaskCurrentState session that isn't also in the CurrentState path, then the session will not be cleaned up correctly. 

### To Reproduce
Create a mock TaskCurrentState session. It will never be cleaned up. 

### Expected behavior
All old sessions should be cleaned up automatically.

### PR DESCRIPTION
**Pull request by NealSun96**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1735 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Currently, old TaskCurrentState session cleanup is dependent on regular CurrentState sessions: for each session in the CurrentState path, the same session will be removed in the TaskCurrentState path. 

This is normally acceptable because both CurrentStates are created by the same session, however, under certain unusual circumstances, this may not behave correctly. For example, after creating a TaskCurrentState, if a user changes Helix versions to a version before TaskCurrentState is introduced, then the clean up logic will only clean up regular CurrentState and leave the TaskCurrentState - this leaves a TaskCurrentState session that doesn't exist on CurrentState side, which will never be cleaned up using the current logic. 

### Tests

- [x] The following tests are written for this issue:

TestHandleSession.testRemoveOldSession

- The following is the result of the "mvn test" command on the appropriate module:

(If CI test fails due to known issue, please specify the issue and test PR locally. Then copy & paste the result of "mvn test" to here.)

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/manager/zk/ParticipantManager.java [hunk 1]
```diff
@@ -418,7 +418,16 @@ private void carryOverPreviousCurrentState() {
       String path = _keyBuilder.currentStates(_instanceName, session).getPath();
       LOG.info("Removing current states from previous sessions. path: " + path);
       _zkclient.deleteRecursively(path);
-      path = _keyBuilder.taskCurrentStates(_instanceName, session).getPath();
+    }
+
+    // Remove all previous task current state sessions
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/manager/zk/ParticipantManager.java:423]: I suggest you move the task CS sessions removal logic to a separate method. Just call it carryOverPreviousTaskCurrentState or cleanPreviousCurrentState.

We should avoid huge methods whenever possible.

**Review by jiajunwang — COMMENTED** [review]
A minor comment. In general looks good to me.

**Review by jiajunwang — APPROVED** [review]
LGTM!

File: helix-core/src/main/java/org/apache/helix/manager/zk/ParticipantManager.java [hunk 2]
```diff
@@ -362,6 +363,7 @@ private void carryOverPreviousCurrentState() {
         }
 
         // If the the current state is related to tasks, there is no need to carry it over to new session.
+        // Note: this check is not necessary due to TaskCurrentStates, but keep it for backwards compatibility
```
Comment (alirezazamani) [inline helix-core/src/main/java/org/apache/helix/manager/zk/ParticipantManager.java:366]: I am not sure if I understand this comment. We have this check to not carry over task related current states. Why it is not necessary?

Comment (NealSun96) [reply helix-core/src/main/java/org/apache/helix/manager/zk/ParticipantManager.java:366]: Because this logic is working with `_keyBuilder.currentStates`. TaskCurrentStates have their own path now (`keyBuilder.taskCurrentStates`), meaning this check will not be used unless for backward compatibility purposes.

**Comment by NealSun96** [comment]
This PR is ready to be merged, approved by @jiajunwang      
Final commit message:
## Properly clean up TaskCurrentState sessions ##
This PR fixes TaskCurrentState session clean up to be independent from regular sessions.

**Review by alirezazamani — APPROVED** [review]
