### PR TITLE
Fix validation logic in GenericApiBuilders and add usage tests

### LINKED ISSUE #1121: Fix GenericZkHelixApiBuilder and GenericBaseDataAccessorBuilder
protected RealmAwareZkClient createZkClient(RealmAwareZkClient.RealmMode realmMode,
      RealmAwareZkClient.RealmAwareZkConnectionConfig connectionConfig,
      RealmAwareZkClient.RealmAwareZkClientConfig clientConfig, String zkAddress) {
    switch (realmMode) {
      case MULTI_REALM:
        try {
          return new FederatedZkClient(connectionConfig,
              clientConfig.setZkSerializer(new ZNRecordSerializer()));
        } catch (IOException | InvalidRoutingDataException | IllegalStateException e) {
          throw new HelixException("Failed to create FederatedZkClient!", e);
        }
      case SINGLE_REALM:
        // Create a HelixZkClient: Use a SharedZkClient because ClusterSetup does not need to do
        // ephemeral operations
        return SharedZkClientFactory.getInstance()
            .buildZkClient(new HelixZkClient.ZkConnectionConfig(zkAddress),
                clientConfig.createHelixZkClientConfig().setZkSerializer(new ZNRecordSerializer()));
      default:
        throw new HelixException("Invalid RealmMode given: " + realmMode);
    }
  }

the RealmMode set in RealmAwareZkConnectionConfig is not being honored.

### PR DESCRIPTION
**Pull request by narendly**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1121 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Some of the validation logic in GenericBaseDataAccessorBuilder and GenericZkHelixApiBuilder were confusing and there were no usage tests. This commit reviews the consistency between validate methods of BaseDataAccessor APIs and writes test cases to demonstrate how they should be used.

Also, connection timeout setting wasn't being honored in the createZkClient() methods, so this bug was fixed as well.

createZkConnectionConfig() was removed from RealmAwareZkClient because the intended purpose of this method isn't clear and was not being used anywhere else.

### Tests

- [x] The following tests are written for this issue:

TestMultiZkHelixJavaApis

- [x] The following is the result of the "mvn test" command on the appropriate module:

zookeeper-api:

```
[INFO] Tests run: 37, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 51.491 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 37, Failures: 0, Errors: 0, Skipped: 0
```

helix-core:

```
[ERROR] Failures: 
[ERROR]   TestEnableCompression.testEnableCompressionResource:116 » ThreadTimeout Method...
[ERROR]   TestAutoRebalanceWithDisabledInstance.testDisableEnableInstanceAutoRebalance:69 expected:<true> but was:<false>
[ERROR]   TestClusterInMaintenanceModeWhenReachingMaxPartition.testDisableCluster:119 expected:<true> but was:<false>
[ERROR]   TestTaskPerformanceMetrics.testTaskPerformanceMetrics:128 expected:<true> but was:<false>
[INFO] 
[ERROR] Tests run: 1149, Failures: 4, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```
Ran the failures individually:
```
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 50.52 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  56.059 s
[INFO] Finished at: 2020-07-01T12:05:50-07:00
```

helix-rest:
```
[INFO] Tests run: 163, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 33.513 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 163, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation (Optional)

- [ ] In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Code Quality

- [x] My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/manager/zk/GenericBaseDataAccessorBuilder.java [hunk 1]
```diff
@@ -123,23 +124,26 @@ protected RealmAwareZkClient createZkClient(RealmAwareZkClient.RealmMode realmMo
...
    * @param zkClientType
    * @param realmMode
    */
   private void validateZkClientType(ZkClientType zkClientType,
       RealmAwareZkClient.RealmMode realmMode) {
-    boolean isZkClientTypeSet = zkClientType != null;
-    // If ZkClientType is set, RealmMode must either be single-realm or not set.
-    if (isZkClientTypeSet && realmMode == RealmAwareZkClient.RealmMode.MULTI_REALM) {
-      throw new HelixException("ZkClientType cannot be set on multi-realm mode!");
+    if (realmMode == null) {
```
Comment (dasahcc) [inline helix-core/src/main/java/org/apache/helix/manager/zk/GenericBaseDataAccessorBuilder.java:134]: Do we have some default mode for it? Shall we make it default behavior as single realm?

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/api/client/ZkClientType.java [hunk 2]
```diff
@@ -25,18 +25,24 @@
    * creation, callback functionality, and session management. But note that this is more
    * resource-heavy since it creates a dedicated ZK connection so should be used sparingly only
    * when the aforementioned features are needed.
+   *
+   * Valid on SINGLE_REALM only.
    */
   DEDICATED,
```
Comment (jiajunwang) [inline zookeeper-api/src/main/java/org/apache/helix/zookeeper/api/client/ZkClientType.java:31]: In this case, shall we merge the realm option into the enum item's fields? Then we don't need to check since the user cannot configure this option.

Comment (narendly) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/api/client/ZkClientType.java:31]: @jiajunwang 
The user does have the ability to select the ZkClientType. Before ZooScalability, we allowed users to select the ZkClientType (Dedicated or Shared) when creating a BaseDataAccessor. We are doing this to keep things backward-compatible. See the following examples (copy-pasted from the test cases added as part of this PR) below:

 ```
   // Create ZkBaseDataAccessor, multi-realm, dedicated ZkClient (should fail)
    try {
      accessor = zkBaseDataAccessorBuilder.setRealmMode(RealmAwareZkClient.RealmMode.MULTI_REALM)
          .setZkClientType(ZkClientType.DEDICATED).setZkAddress(firstZkAddress)
          .setRealmAwareZkConnectionConfig(connectionConfigBuilder.build()).build();
      Assert.fail("MULTI_REALM and DEDICATED ZkClientType are an invalid combination!");
    } catch (HelixException e) {
      // Expected
    }

     // Create ZkBaseDataAccessor, multi-realm, shared ZkClient (should fail)
    try {
      accessor = zkBaseDataAccessorBuilder.setRealmMode(RealmAwareZkClient.RealmMode.MULTI_REALM)
          .setZkClientType(ZkClientType.SHARED).setZkAddress(firstZkAddress)
          .setRealmAwareZkConnectionConfig(connectionConfigBuilder.build()).build();
      Assert.fail("MULTI_REALM and SHARED ZkClientType are an invalid combination!");
    } catch (HelixException e) {
      // Expected
    }

     // Create ZkBaseDataAccessor, multi-realm, federated ZkClient, ZkAddress set (should fail)
    try {
      accessor = zkBaseDataAccessorBuilder.setRealmMode(RealmAwareZkClient.RealmMode.MULTI_REALM)
          .setZkClientType(ZkClientType.FEDERATED).setZkAddress(firstZkAddress)
          .setRealmAwareZkConnectionConfig(connectionConfigBuilder.build()).build();
      Assert.fail("MULTI_REALM and FEDERATED ZkClientType do not connect to one ZK!");
    } catch (HelixException e) {
      // Expected
    }


```

Comment (narendly) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/api/client/ZkClientType.java:31]: So to answer your question, because the user may want to choose which ZkClientType to use, it's appropriate that we leave this enum as a separate public enum.

Comment (jiajunwang) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/api/client/ZkClientType.java:31]: > The user does have the ability to select the ZkClientType.

Sure. My question is that once a user selects a certain type, do they have to specify a RealmMode in addition? Since based on your comment, it seems to be pure overhead. Because if they select DEDICATED, then the real mode has to be SINGLE_REALM.
I know this is for backward compatibility, so shall we just fill the RealmMode for the user when they configure the client using ZkClientType? In this case, we don't need the validation logic.

Comment (narendly) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/api/client/ZkClientType.java:31]: @jiajunwang 

That is actually something I've considered and the original implementation was somewhat doing that. But I realized that this type of "backfill" or doing this under the surface was more confusing to the user and adds more difficulty in the usage of the Builder API. We should make sure we require the users to explicitly set the types/configs, otherwise we run the risk of doing things without the user knowing and confusing them.

Comment (jiajunwang) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/api/client/ZkClientType.java:31]: So I have several questions after reviewing more code. Maybe you would like to clarify the plan?

1. The default builder build() method can actually create a client with MultiRealm enabled for DEDICATED client. However, we disable this option by enforcing the validation logic. Was it intentionally done?

2. If this is the case, then the actual build() code can be simplified, right? Since half of the branches won't be called forever.

3. 
Regarding what you replied,

> more confusing to the user and adds more difficulty in the usage of the Builder API

I guess what you meant is that if there are 2 ways of configuring the client and these 2 options are all available in one builder, it would be confusing that which one to use.

I think we discussed this topic before. To make it clearer, my suggestion would be,
1. The new builder does not allow ZkClientType config. Assume this is for backward compatibility. So we should not introduce to the new APIs.
2. For the older APIs (deprecated ones), as long as the type is passed in, we auto-fill the RealmMode based on the type. Since you mentioned in the comment that the mapping is one to one, this is doable.
3. In this case, there won't be a confusing part, IMO. And we won't need these validation logics everywhere. This helps with future maintenance work greatly.

Not sure if you agree, please feel free to schedule a discussion. Maybe I missed some usage.

BTW, if you are concerned about the already published version, then we can deprecate the ZkClientType setting method in the builders to suggest users not using it for now. The validation part can be left in the code until we make the API clean later.

Comment (narendly) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/api/client/ZkClientType.java:31]: 1. I think you're referring to 

```
      case MULTI_REALM:
        try {
          if (_zkClientType == ZkClientType.DEDICATED) {
            // Use a realm-aware dedicated zk client
            zkClient = DedicatedZkClientFactory.getInstance()
                .buildZkClient(connectionConfig, clientConfig);
          } else if (_zkClientType == ZkClientType.SHARED) {
            // Use a realm-aware shared zk client
            zkClient =
                SharedZkClientFactory.getInstance().buildZkClient(connectionConfig, clientConfig);
          } else {
            zkClient = new FederatedZkClient(connectionConfig, clientConfig);
          }
        } catch (IOException | InvalidRoutingDataException | IllegalStateException e) {
          throw new HelixException("Not able to connect on multi-realm mode.", e);
        }
        break;
```

Reviewing this logic again, I believe this was a bug. Multi-realm means it has to use FederatedZkClient only because it has to be able to talk to multiple ZKs. I've fixed this. Good catch!

2. I've removed some code in the createZkClient() method.

3. We can still support ZkClientType after fixing the bug. Like you said, ZkClientType is not set, we default to SHARED (original behavior).

Comment (jiajunwang) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/api/client/ZkClientType.java:31]: Given the current situation that user still has an option to choose between dedicated/shared clients when the realm mode is single realm, I agree that we still need to keep the methods in the builder.

File: helix-core/src/main/java/org/apache/helix/manager/zk/GenericBaseDataAccessorBuilder.java [hunk 3]
```diff
@@ -82,38 +82,28 @@ protected RealmAwareZkClient createZkClient(RealmAwareZkClient.RealmMode realmMo
...
-                .buildZkClient(connectionConfig, clientConfig);
-          } else if (_zkClientType == ZkClientType.SHARED) {
-            // Use a realm-aware shared zk client
-            zkClient =
-                SharedZkClientFactory.getInstance().buildZkClient(connectionConfig, clientConfig);
-          } else {
-            zkClient = new FederatedZkClient(connectionConfig, clientConfig);
-          }
-        } catch (IOException | InvalidRoutingDataException | IllegalStateException e) {
+          zkClient = new FederatedZkClient(connectionConfig, clientConfig);
```
Comment (dasahcc) [inline helix-core/src/main/java/org/apache/helix/manager/zk/GenericBaseDataAccessorBuilder.java:85]: If you think this is a bug we should fix, then we need to make clear definition of what is single realm and what is multi realm. My original thought was if you are using sharding key to determine the ZK address then it is mutli realm.

Then for dedicated zkclient, and shared zkclient, they can still use sharding key for searching zk address. Then it will be meaningless for dedicated/shared Zkclient to have the sharding key and they will only accept the ZK address. This conflict with what we have changed.

Comment (narendly) [reply helix-core/src/main/java/org/apache/helix/manager/zk/GenericBaseDataAccessorBuilder.java:85]: > If you think this is a bug we should fix, then we need to make clear definition of what is single realm and what is multi realm. My original thought was if you are using sharding key to determine the ZK address then it is mutli realm.

"Multi-realm" means it needs to be able to talk to different realms. "Single-realm" means it only connects to one realm.
If you're using a sharding key to locate which ZK to talk to, then it's "realm-aware", not multi-realm.

> Then for dedicated zkclient, and shared zkclient, they can still use sharding key for searching zk address. Then it will be meaningless for dedicated/shared Zkclient to have the sharding key and they will only accept the ZK address. This conflict with what we have changed.

RealmAware DedicatedZkClient and SharedZkClient do not require the ZK address. They instead require the ZK path sharding key and only connect to the ZK realm that the given ZK path sharding key maps to. Again, they fall under the single-realm use case.

@dasahcc Does this clarify?

Comment (dasahcc) [reply helix-core/src/main/java/org/apache/helix/manager/zk/GenericBaseDataAccessorBuilder.java:85]: Sounds good. We need to clear deliver this to users. Then for the change. I am totally fine with it.
