### PR TITLE
Consider fault zones when sorting combinedPreferenceList

### LINKED ISSUE #2885: Controller can violate fault zone placement constraints during intermediate state
### Describe the bug
Four resource with replication factor of 3, the controller allows an intermediate state where there are 3 replicas, but 2 are in the same fault zone.
This can occur from the following:
—
Replica 1 (FZ A), Replica 2 (FZ B), Replica 3 (FZ C)
Replica 1 (FZ A), Replica 2 (FZ B), Replica 3 (FZ C), Replica 4 (FZ B) <- n+1 movement
Replica 1 (FZ A), Replica 2 (FZ B), Replica 4 (FZ B)

This is still an intermediate state and the controller will immediately try to bootstrap a 4th replica to drop one of the replicas in FZ B. However, if the cluster cannot complete the n+1 movement on the targeted nodes due to capacity constraints, then it will remain in this state indefinitely. No WAGED calculations errors will be thrown. With no capacity constraints preventing movement, this state will remain for as long as it takes to bootstrap the other replica from OFFLINE→SLAVE.

There is also a follow-up issue that stoppable check will not prevent the fault zone where 2/3 replicas exist from being taken down. This is because stoppable parallelizes same MZ checks and works on the assumption there will not be more than 1 replica in  a single fault zone. 

### To Reproduce
Have not determined how to reproduce this specific case, but it occurs during movement within the cluster. Seems that it can occur when a node in the current state but not the preference list occupies the same fault zone as a node that is in the preference list but not the current state. Controller will create a n+1 replica on the node in the preference list, but then possibly drop a different node and not the one already in the same fault zone as newly bootstrapped replica. 

### Expected behavior
Controller should take into account topology when determining which replica to drop first. If the controller drops a replica from a fault zone that already has another replica in it, then we will not decrease the # of fault zones where replicas for the partition exist. 

### Additional context
There are two fixes needed:
1. Change the controller logic for deciding replica priority so that MZ's that have the most # of replicas are preferentially dropped. 
2. Address stoppable check not accounting for multiple replicas in the same MZ during the min_active_replica check

### PR DESCRIPTION
**Pull request by GrantPSpencer**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:
Fixes #2885 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

When determining which replica to drop between 2 replicas that are not in the preference list, controller should consider the fault zone representation. The controller should prioritize dropping a replica in a fault zone that already has another copy of the replica existing in it. If the controller drops a replica from a fault zone that already has another replica in it, then we will not decrease the # of fault zones where replicas for the partition exist.

TODO:
- [ ] Determine if sorting by MZ should only be done if the replica states are the same. With current change, sorting by MZ takes precedence of sorting by state for replicas that are both not in the preference list.

### Tests

- [x] The following tests are written for this issue:

`TestPreferenceListNodeComparatorWithTopologyAware.java`

- The following is the result of the "mvn test" command on the appropriate module:

```
$ mvn test -o -Dtest=TestPreferenceListNodeComparatorWithTopologyAware -pl=helix-core
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  29.011 s
[INFO] Finished at: 2024-08-28T21:30:03-07:00
[INFO] ------------------------------------------------------------------------
```

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

N/A

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/AbstractRebalancer.java [hunk 1]
```diff
@@ -557,20 +557,24 @@ protected static class PreferenceListNodeComparator implements Comparator<String
     protected final Map<String, String> _currentStateMap;
     protected final StateModelDefinition _stateModelDef;
     protected final List<String> _preferenceList;
+    ResourceControllerDataProvider _cache;
 
-    public PreferenceListNodeComparator(Map<String, String> currentStateMap,
-        StateModelDefinition stateModelDef, List<String> preferenceList) {
+    public PreferenceListNodeComparator(Map<String, String> currentStateMap, StateModelDefinition stateModelDef,
+        List<String> preferenceList, ResourceControllerDataProvider cache) {
```
Comment (junkaixue) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/AbstractRebalancer.java:563]: We cannot directly change the public constructor in open source.

You can add another constructor and keep the original one. So just pass null for the cache and invoke the new constructor for the old one like:
this (xxxxxx).


This can help you do the compute control as well. Means when cache is null, skip the MZ sorting and keep the old logic.

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/AbstractRebalancer.java [hunk 2]
```diff
@@ -581,6 +585,46 @@ public int compare(String ins1, String ins2) {
...
+
+            if (mz1.equals(currMz)) {
+              mz1Count++;
+            } else if (mz2.equals(currMz)) {
+              mz2Count++;
+            }
+        }
+        if (mz1Count != mz2Count) {
+          return mz1Count - mz2Count;
+        }
```
Comment (junkaixue) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/AbstractRebalancer.java:624]: You are counting instances per mz. It is expensive to recompute the counting looping through the current state map.

You can make a compute and loop current state to compute MZ counting mapping in constructor once. And every compare can leverage that map.

Comment (GrantPSpencer) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/AbstractRebalancer.java:624]: Good points on both issues, thank you for the review. I'll address this

**Review by junkaixue — APPROVED** [review]
Good job!
