### PR TITLE
Stabilize TestInstancesAccessor

### LINKED ISSUE #1821: [Failed CI Test] testInstancesStoppable_zoneBased(org.apache.helix.rest.server.TestInstancesAccessor)
This issue is created for tracking unstable test: testInstancesStoppable_zoneBased(org.apache.helix.rest.server.TestInstancesAccessor)

### PR DESCRIPTION
**Pull request by alirezazamani**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:
Fixes #1821  

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
TestInstancesAccessor is unstable because the cluster might not be stable while the test runs the stoppable check and cluster config and instance config can be missing. In this commit, the test waits until the cluster config and instance config get created and then proceeds for the stoppable checks.

### Tests

- [x] The following is the result of the "mvn test" command on the appropriate module:
Helix-rest:
```[INFO] Tests run: 179, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 127.842 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 179, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.6:report (generate-code-coverage-report) @ helix-rest ---
[INFO] Loading execution data file /home/anajari/my_repos/helix/helix-rest/target/jacoco.exec
[INFO] Analyzed bundle 'Apache Helix :: Restful Interface' with 79 classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:16 min
[INFO] Finished at: 2021-07-21T19:46:04-07:00
[INFO] ------------------------------------------------------------------------
```

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Comment by alirezazamani** [comment]
Running the test in a loop for 1000 times to make sure the test is stable. I will update the PR description after the test.

**Comment by alirezazamani** [comment]
> Running the test using the test script for 1000 times to make sure the test is stable. I will update the PR description after the test.

Ran the test 1000 times and all of them passed.

File: helix-rest/src/test/java/org/apache/helix/rest/server/TestInstancesAccessor.java [hunk 1]
```diff
@@ -46,8 +46,34 @@
   private final static String CLUSTER_NAME = "TestCluster_0";
 
   @Test
-  public void testInstancesStoppable_zoneBased() throws IOException {
+  public void testInstancesStoppable_zoneBased() throws Exception {
     System.out.println("Start test :" + TestHelper.getTestMethodName());
+    // Make sure that cluster config exists
```
Comment (jiajunwang) [inline helix-rest/src/test/java/org/apache/helix/rest/server/TestInstancesAccessor.java:51]: Shall we put the wait to the AbstractTestClass? Since the cluster and instances were created there. This check does not make sense in this specific test class scenario.

Comment (alirezazamani) [reply helix-rest/src/test/java/org/apache/helix/rest/server/TestInstancesAccessor.java]: Done.

File: helix-rest/src/test/java/org/apache/helix/rest/server/TestInstancesAccessor.java [hunk 2]
```diff
@@ -46,7 +46,7 @@
   private final static String CLUSTER_NAME = "TestCluster_0";
 
   @Test
-  public void testInstancesStoppable_zoneBased() throws IOException {
+  public void testInstancesStoppable_zoneBased() throws Exception {
```
Comment (jiajunwang) [inline helix-rest/src/test/java/org/apache/helix/rest/server/TestInstancesAccessor.java:49]: nit, No need to change this file with your new modification?

**Review by jiajunwang — APPROVED** [review]
LGTM! Please address the minor comment that I just added.

File: helix-rest/src/test/java/org/apache/helix/rest/server/TestInstancesAccessor.java (hunk 2 above)
Comment (alirezazamani) [reply helix-rest/src/test/java/org/apache/helix/rest/server/TestInstancesAccessor.java]: Done.

**Comment by alirezazamani** [comment]
This PR is ready to be merged.
Commit message: 
Stabilize TestInstancesAccessor

TestInstancesAccessor is unstable because the cluster might not be
stable while the test runs the stoppable check and cluster config and
instance config can be missing. In this commit, the test waits until the
cluster config and instance config get created and then proceeds for
the stoppable checks.
