### PR TITLE
fix TestHelixAdminCli testDeactivateCluster flakiness

### LINKED ISSUE #1300: Fix unstable TestHelixAdminCli.testDeactivateCluster
LOG: (368)
>2020-08-21T06:26:35.4891005Z [ERROR] testDeactivateCluster(org.apache.helix.tools.TestHelixAdminCli)  Time elapsed: 2.182 s  <<< FAILURE!
2020-08-21T06:26:35.4899581Z org.apache.helix.HelixException: There are still LEADER in the cluster, shut them down first.
2020-08-21T06:26:35.4907516Z 	at org.apache.helix.tools.TestHelixAdminCli.testDeactivateCluster(TestHelixAdminCli.java:604)
2020-08-21T06:26:35.4909023Z 

>2020-08-21T04:51:16.5818512Z START testDeactivateCluster at Fri Aug 21 04:51:16 UTC 2020
2020-08-21T04:51:16.5823028Z START TestHelixAdminCli at Fri Aug 21 04:51:16 UTC 2020
2020-08-21T04:51:18.6654306Z 2360301 [HelixController-pipeline-default-TestHelixAdminCli-(f85f62bd_DEFAULT)] ERROR org.apache.helix.controller.GenericHelixController  - Exception while executing DEFAULT pipeline: TestHelixAdminCli for cluster [org.apache.helix.zookeeper.zkclient.ZkClient.retryUntilConnected(ZkClient.java:1689), org.apache.helix.zookeeper.zkclient.ZkClient.getChildren(ZkClient.java:1046), org.apache.helix.zookeeper.zkclient.ZkClient.getChildren(ZkClient.java:1039), org.apache.helix.manager.zk.ZkBaseDataAccessor.getChildNames(ZkBaseDataAccessor.java:669), org.apache.helix.manager.zk.ZkBaseDataAccessor.getChildren(ZkBaseDataAccessor.java:625), org.apache.helix.manager.zk.ZkBaseDataAccessor.getChildren(ZkBaseDataAccessor.java:601), org.apache.helix.manager.zk.ZKHelixDataAccessor.getChildValues(ZKHelixDataAccessor.java:415), org.apache.helix.manager.zk.ZKHelixDataAccessor.getChildValuesMap(ZKHelixDataAccessor.java:476), org.apache.helix.common.caches.PropertyCache.doSimpleCacheRefresh(PropertyCache.java:168), org.apache.helix.common.caches.PropertyCache.refresh(PropertyCache.java:160), org.apache.helix.controller.dataproviders.BaseControllerDataProvider.doRefresh(BaseControllerDataProvider.java:333), org.apache.helix.controller.dataproviders.ResourceControllerDataProvider.refresh(ResourceControllerDataProvider.java:143), org.apache.helix.controller.stages.ReadClusterDataStage.process(ReadClusterDataStage.java:63), org.apache.helix.controller.pipeline.Pipeline.handle(Pipeline.java:68), org.apache.helix.controller.GenericHelixController.handleEvent(GenericHelixController.java:777), org.apache.helix.controller.GenericHelixController.access$500(GenericHelixController.java:128), org.apache.helix.controller.GenericHelixController$ClusterEventProcessor.run(GenericHelixController.java:1407)]. Will not continue to next pipeline
2020-08-21T04:51:18.6656197Z 2360302 [HelixController-pipeline-task-TestHelixAdminCli-(252a0738_TASK)] ERROR org.apache.helix.controller.GenericHelixController  - Cluster manager: controller_9001 is not leader for TestHelixAdminCli. Pipeline will not be invoked
2020-08-21T04:51:24.8112618Z END testDeactivateCluster at Fri Aug 21 04:51:24 UTC 2020, took: 8235ms.

### PR DESCRIPTION
**Pull request by kaisun2000**
### Issues

- [ ] My PR addresses the following Helix issues and references them in the PR description:

fix #1300 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
fix TestHelixAdminCli testDeactivateCluster flakiness. As this
test does not wait till the cluster converge before tearing it
down. The tearing down process can have exceptions depending on
timing.

(Write a concise description including what, why, how)

### Tests

- [ ] The following tests are written for this issue:

(List the names of added unit/integration tests)

- [ ] The following is the result of the "mvn test" command on the appropriate module:

(Before CI test pass, please copy & paste the result of "mvn test")

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/test/java/org/apache/helix/tools/TestHelixAdminCli.java [hunk 1]
```diff
@@ -603,6 +611,12 @@ public void testDeactivateCluster() throws Exception {
     command = "-zkSvr localhost:2183 -dropCluster " + clusterName;
     ClusterSetup.processCommandLineArgs(command.split("\\s"));
 
+    boolean leaderNotExists = TestHelper.verify(() -> {
+      boolean isLeaderExists = _gZkClient.exists(path);
+      return isLeaderExists == false;
+    }, 10000L);
```
Comment (jiajunwang) [inline helix-core/src/test/java/org/apache/helix/tools/TestHelixAdminCli.java:617]: nit, TestHelper.WAIT_DURATION?

**Review by jiajunwang — APPROVED** [review]
Please address the minor comment.

**Comment by kaisun2000** [comment]
This PR is approved, please help to merge in

>fix TestHelixAdminCli testDeactivateCluster flakiness. As this
test does not wait till the cluster converge before tearing it
down. The tearing down process can have exceptions depending on
timing.

File: helix-core/src/test/java/org/apache/helix/tools/TestHelixAdminCli.java (hunk 1 above)
Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/tools/TestHelixAdminCli.java]: changed.
