### PR TITLE
Replace Thread.sleep() with TestHelper.verify() to fix the flaky unit tests

### LINKED ISSUE #1446: TestHelper verify() enhancement to the unit test
Quite some unit test still use Thread.sleep(xxx) to wait for a condition to happen. This is a source of falkiness of test. They may also make the test running unnecessarily long. We should address them with TestHelper.verify() method.

### PR DESCRIPTION
**Pull request by kaisun2000**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

fix #1446 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Quite some unit test still use Thread.sleep(xxx) to wait for a
condition to happen. This is a source of falkiness of test. This
may also make the test running unnecessarily long. We address
this issue with TestHelper.verify() method.

### Tests

- [ ] The following tests are written for this issue:

(List the names of added unit/integration tests)

- [x] The following is the result of the "mvn test" command on the appropriate module:

https://github.com/apache/helix/runs/1218717184?check_suite_focus=true
See above link. All test passed.
### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/test/java/org/apache/helix/TestZKCallback.java [hunk 1]
```diff
@@ -165,8 +166,10 @@ public void testInvocation() throws Exception {
 
       ExternalView extView = new ExternalView("db-12345");
       accessor.setProperty(keyBuilder.externalView("db-12345"), extView);
-      Thread.sleep(100);
-      AssertJUnit.assertTrue(testListener.externalViewChangeReceived);
+      boolean result = TestHelper.verify(() -> {
+        return testListener.externalViewChangeReceived == true;
```
Comment (jiajunwang) [inline helix-core/src/test/java/org/apache/helix/TestZKCallback.java:170]: nit, "== true" is not necessary.

File: helix-core/src/test/java/org/apache/helix/TestListenerCallback.java [hunk 2]
```diff
@@ -131,22 +131,28 @@ public void testConfigChangeListeners() throws Exception {
     TestConfigListener listener = new TestConfigListener();
     listener.reset();
     _manager.addInstanceConfigChangeListener(listener);
-    Assert.assertTrue(listener._instanceConfigChanged,
-        "Should get initial instanceConfig callback invoked");
+    boolean result = TestHelper.verify(()-> {
+      return listener._instanceConfigChanged == true;
```
Comment (jiajunwang) [inline helix-core/src/test/java/org/apache/helix/TestListenerCallback.java:135]: nit, "== true" is not necessary.

File: helix-core/src/test/java/org/apache/helix/TestHelper.java [hunk 3]
```diff
@@ -76,7 +76,7 @@
 
 public class TestHelper {
   private static final Logger LOG = LoggerFactory.getLogger(TestHelper.class);
-  public static final long WAIT_DURATION = 20 * 1000L; // 20 seconds
+  public static final long WAIT_DURATION = 60 * 1000L; // 60 seconds
```
Comment (jiajunwang) [inline helix-core/src/test/java/org/apache/helix/TestHelper.java:79]: This reminds me that we are not testing for the latency for now. For example, if the callback does not happen within one second, then we may want to fail the test.
Will it be a good idea to have at least 2 Duration?
Pipeline_Wait_Duration = 60000;
Callback_Wait_Duration = 2000;

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java [hunk 4]
```diff
@@ -152,15 +152,15 @@ public void testDuplicateMsg() throws Exception {
     Assert.assertTrue(messages.get(0).getFromState().equalsIgnoreCase("SLAVE"));
     Assert.assertTrue(messages.get(0).getToState().equalsIgnoreCase("MASTER"));
 
-    runPipeline(event, dataRefresh);
-
+    Thread.sleep(MessageGenerationPhase.DEFAULT_OBSELETE_MSG_PURGE_DELAY);
     // Verify the stale message should be deleted
     Assert.assertTrue(TestHelper.verify(() -> {
+      runPipeline(event, dataRefresh);
```
Comment (jiajunwang) [inline helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java:158]: This changes the original test logic. We shall only need one pipeline run after the delay. And it shall guarantee the operation is done correctly.
If there is a concern about the delay time, we can wait for 2 * DEFAULT_OBSELETE_MSG_PURGE_DELAY.

File: helix-core/src/test/java/org/apache/helix/integration/rebalancer/TestClusterInMaintenanceModeWhenReachingOfflineInstancesLimit.java [hunk 5]
```diff
@@ -130,18 +130,24 @@ public void testWithDisabledInstancesLimit() throws Exception {
...
+    Assert.assertTrue(result);
 
     String instance = _participants.get(i).getInstanceName();
     admin.enableInstance(CLUSTER_NAME, instance, false);
 
-    Thread.sleep(500);
-    maintenanceSignal = _dataAccessor.getProperty(_dataAccessor.keyBuilder().maintenance());
-    Assert.assertNotNull(maintenanceSignal);
-    Assert.assertNotNull(maintenanceSignal.getReason());
+    ZkHelixClusterVerifier clusterVerifier1 =
```
Comment (jiajunwang) [inline helix-core/src/test/java/org/apache/helix/integration/rebalancer/TestClusterInMaintenanceModeWhenReachingOfflineInstancesLimit.java:142]: Please mind the naming of the variables. A meaningful name is required in all cases.

File: helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java (hunk 4 above)
Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/controller/stages/TestRebalancePipeline.java:158]: Ok. 

```
Thread.sleep(2 * MessageGenerationPhase.DEFAULT_OBSELETE_MSG_PURGE_DELAY);
runPipeline(event, dataRefresh);
Assert.assertTrue(TestHelper.verify(() -> {
if (dataCache.getStaleMessages().size() != 0) {
        return false;
      }
      return true;
    }, TestHelper.WAIT_DURATION));
```

File: helix-core/src/test/java/org/apache/helix/TestHelper.java (hunk 3 above)
Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/TestHelper.java:79]: In this pull request, we don't have the case of waiting too long, we should fail the test case. How about let us add them once we have this case.

File: helix-core/src/test/java/org/apache/helix/TestListenerCallback.java (hunk 2 above)
Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/TestListenerCallback.java:135]: removed all.

File: helix-core/src/test/java/org/apache/helix/TestZKCallback.java (hunk 1 above)
Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/TestZKCallback.java:170]: removed all

File: helix-core/src/test/java/org/apache/helix/integration/rebalancer/TestClusterInMaintenanceModeWhenReachingOfflineInstancesLimit.java (hunk 5 above)
Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/integration/rebalancer/TestClusterInMaintenanceModeWhenReachingOfflineInstancesLimit.java:142]: changed to clusterVerifier. there is only 1 verifier in this test case.

**Comment by lei-xia** [comment]
minor: suggest to change the PR (commit) title to "Replace Thread.sleep() with TestHelper.verify() to fix the flaky unit tests".

File: helix-core/src/test/java/org/apache/helix/TestHelper.java (hunk 3 above)
Comment (jiajunwang) [reply helix-core/src/test/java/org/apache/helix/TestHelper.java:79]: Sure. This is not a big concern.

File: helix-core/src/test/java/org/apache/helix/TestListenerCallback.java [hunk 6]
```diff
@@ -206,21 +206,24 @@ public void testScopedConfigChangeListener() throws Exception {
...
     }, TestHelper.WAIT_DURATION);
     Assert.assertTrue(result,"Should get initial clusterConfig callback invoked");
     Assert.assertEquals(listener._configSize, 1, "Cluster Config size should be 1");
 
     listener.reset();
     _manager.addConfigChangeListener(listener, ConfigScopeProperty.RESOURCE);
+    result = TestHelper.verify(()-> {
+      return listener._configChanged;
+    }, TestHelper.WAIT_DURATION);
     Assert.assertTrue(listener._configChanged,
```
Comment (jiajunwang) [inline helix-core/src/test/java/org/apache/helix/TestListenerCallback.java:219]: nit, this one shall assert the result.

**Review by jiajunwang — APPROVED** [review]

File: helix-core/src/test/java/org/apache/helix/TestListenerCallback.java (hunk 6 above)
Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/TestListenerCallback.java:219]: Good catch.

Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/TestListenerCallback.java]: fixed.

**Comment by kaisun2000** [comment]
This diff is approved. Please help to merge

> fix #1446 
Quite some unit test still use Thread.sleep(xxx) to wait for a
condition to happen. This is a source of falkiness of test. This
may also make the test running unnecessarily long. We address
this issue with TestHelper.verify() method.

**Comment by pkuwm** [comment]
3 PRs have duplicate code which increases the effort for reviewers to review. I suggest you make them one by one or clean the duplicate code

**Comment by kaisun2000** [comment]
The PRs are all broke out from #1227. We need to make them individually compiles. Thus the duplicate code. Once I merge them in to #1227, the duplication would be gone.

File: helix-core/src/test/java/org/apache/helix/TestHelper.java [hunk 7]
```diff
@@ -799,7 +799,12 @@ public static boolean verify(Verifier verifier, long timeout) throws Exception {
     long start = System.currentTimeMillis();
     do {
       boolean result = verifier.verify();
-      if (result || (System.currentTimeMillis() - start) > timeout) {
+      boolean isTimedout = (System.currentTimeMillis() - start) > timeout;
+      if (result || isTimedout) {
+        if (isTimedout && !result) {
+          LOG.error("verifier time out, consider try longer timeout, stack trace{}",
+              Arrays.asList(Thread.currentThread().getStackTrace()));
```
Comment (pkuwm) [inline helix-core/src/test/java/org/apache/helix/TestHelper.java:806]: The stack trace will be printed in one line with this code. I suggest we use `new throwable().printstacktrace()`

Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/TestHelper.java:806]: The is intentional one line. `new throwable().printstacktrace()` would give you multiple lines. That is used for true exception logging. 

This is not really exception. Just a hint that verify() did not finish in time. We don't want to mix both case for easy reading the test output.

This Arrays.asList is used also in other places in our test.

**Comment by kaisun2000** [comment]
The diff is approved, please help to merge into trunk.

>fix #1446
Quite some unit test still use Thread.sleep(xxx) to wait for a
condition to happen. This is a source of falkiness of test. This
may also make the test running unnecessarily long. We address
this issue with TestHelper.verify() method.
