### PR TITLE
Fix MaxCapacityUsageGauge value not updated

### LINKED ISSUE #1463: MaxCapacityUsageGauge value is always 0
### Describe the bug
From metrics reporting result in mbean server, we find that the MaxCapacityUsageGauge is always 0.

### To Reproduce
Use jconsole to check the MaxCapacityUsageGauge attribute metric, no matter what capacity value we change, the value is not updated.

### Expected behavior
MaxCapacityUsageGauge should be correctly updated according to the capacity configs.

### Additional context
The root cause is, the resourceToMonitor map is empty because the resources are filtered out.

### PR DESCRIPTION
**Pull request by pkuwm**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1463 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

MaxCapacityUsageGauge value not updated because the resourcesToMonitor map is empty.

This PR fixes the bug and also add an integration test to protect the metrics reporting logic.

image

### Tests

- [x] The following tests are written for this issue:

testInstanceCapacityMetrics()

- [x] The following is the result of the "mvn test" command on the appropriate module:

```
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   TestRoutingTableProviderPeriodicRefresh.testPeriodicRefresh:214 expected:<4> but was:<3>
[INFO]
[ERROR] Tests run: 1214, Failures: 1, Errors: 0, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:23 h
[INFO] Finished at: 2020-10-13T01:54:46-07:00
[INFO] ------------------------------------------------------------------------
```

The failed test is a known one: https://github.com/apache/helix/issues/1250
@kaisun2000 is working on it.

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/util/WagedValidationUtil.java [hunk 1]
```diff
@@ -88,4 +90,16 @@
...
     return partitionCapacity;
   }
+
+  /**
+   * Checks whether or not a resource has enabled WAGED rebalancer.
+   *
+   * @param idealState {@code IdealState} of the resource being checked.
+   * @return {@code true} if WAGED is enabled; otherwise, {@code false}.
+   */
+  public static boolean isWagedEnabled(IdealState idealState) {
```
Comment (NealSun96) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/util/WagedValidationUtil.java:100]: This could be used in `BestPossibleStateCalcStage.computeResourceBestPossibleStateWithWagedRebalancer` as well. Could you check for other similar usages? Replacing those logic with this function is a step up for cleanness.

File: helix-core/src/main/java/org/apache/helix/controller/stages/CurrentStateComputationStage.java [hunk 2]
```diff
@@ -283,10 +284,10 @@ private void reportInstanceCapacityMetrics(ClusterStatusMonitor clusterStatusMon
     asyncExecute(dataProvider.getAsyncTasksThreadPool(), () -> {
       try {
         // ResourceToRebalance map also has resources from current states.
-        // Only use the resources in ideal states to parse all replicas.
+        // Only use the resources in ideal states that enable WAGED to parse all replicas.
         Map<String, IdealState> idealStateMap = dataProvider.getIdealStates();
         Map<String, Resource> resourceToMonitorMap = resourceMap.entrySet().stream()
-            .filter(idealStateMap::containsKey)
+            .filter(entry -> WagedValidationUtil.isWagedEnabled(idealStateMap.get(entry.getKey())))
```
Comment (NealSun96) [inline helix-core/src/main/java/org/apache/helix/controller/stages/CurrentStateComputationStage.java:290]: Is this a behavior change (all resources -> waged only)?

**Review by NealSun96 — CHANGES_REQUESTED** [review]

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/util/WagedValidationUtil.java (hunk 1 above)
Comment (pkuwm) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/util/WagedValidationUtil.java:100]: Ideally, replacing those places with this API should be done in another PR. Since you've pointed out that place, I just made the change. If there are more places, let's make the change in another PR.

File: helix-core/src/main/java/org/apache/helix/controller/stages/CurrentStateComputationStage.java (hunk 2 above)
Comment (pkuwm) [reply helix-core/src/main/java/org/apache/helix/controller/stages/CurrentStateComputationStage.java:290]: Ideally, we would report every resource. But currently for those non WAGED resources, validation won't pass and `HelixException` would be thrown. So we'll skip non WAGED resources here.

**Review by NealSun96 — APPROVED** [review]

**Comment by pkuwm** [comment]
This PR is ready to be merged, approved by @NealSun96 @jiajunwang 

MaxCapacityUsageGauge value not updated because the resourcesToMonitor map is empty.

This commit fixes the bug and also adds an integration test to protect the metrics reporting logic.
