### PR TITLE
Fix waitToStop method in TaskDriver

### LINKED ISSUE #1082: TaskDriver waitToStop returns if workflow is not IN_PROGRESS
In TaskDriver, when we call waitToStop, We only check when workflow is not IN_PROGRESS and then return from this call. However, if workflow is in STOPPING state and the jobs are still running and user might have the impression that the jobs are stopped and the jobs can be deleted. It can cause problems such and stale znodes, and quota leak because job is still in progress. This needs to be fixed.

### PR DESCRIPTION
**Pull request by alirezazamani**
### Issues
- [x] My PR addresses the following Helix issues and references them in the PR title:
Fixes #1082 

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
In this PR, waitToStop has been changed to make sure workflow/queue is in stopped state if waitToStop returns successfully without Exception. When the queue targetState is set to stop, the queue will go to STOPPING state. STOPPING state is a transient state which means some of the jobs has not ben completely stopped or in terminal state. In other words, some of that tasks within the jobs have not reached the terminal state yet.

### Tests
- [x] The following tests are written for this issue:
TestStoppingQueueFailToStop
- [x] The following is the result of the "mvn test" command on the appropriate module:

helix-core:
```
[ERROR] Tests run: 1140, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 5,244.233 s <<< FAILURE! - in TestSuite
[ERROR] testJobQueueAutoCleanUp(org.apache.helix.integration.task.TestJobQueueCleanUp)  Time elapsed: 300.016 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testJobQueueAutoCleanUp() didn't finish within the time-out 300000

[ERROR] testControllerSwitch(org.apache.helix.task.TestAssignableInstanceManagerControllerSwitch)  Time elapsed: 1.352 s  <<< FAILURE!
java.lang.AssertionError: expected:<5> but was:<0>
	at org.apache.helix.task.TestAssignableInstanceManagerControllerSwitch.testControllerSwitch(TestAssignableInstanceManagerControllerSwitch.java:105)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestJobQueueCleanUp.testJobQueueAutoCleanUp » ThreadTimeout Method org.testng....
[ERROR]   TestAssignableInstanceManagerControllerSwitch.testControllerSwitch:105 expected:<5> but was:<0>
[INFO] 
[ERROR] Tests run: 1140, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:27 h
[INFO] Finished at: 2020-06-10T14:07:27-07:00
[INFO] ------------------------------------------------------------------------
```
The failed test succeed when run individually.
mvn test -Dtest="TestJobQueueCleanUp,TestAssignableInstanceManagerControllerSwitch"
```
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.077 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.503 s
[INFO] Finished at: 2020-06-10T14:37:42-07:00
[INFO] ------------------------------------------------------------------------
```
helix-rest:
```
[INFO] Tests run: 162, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 46.785 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 162, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  52.195 s
[INFO] Finished at: 2020-06-10T14:36:25-07:00
[INFO] ------------------------------------------------------------------------
```

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- [x] My diff has been formatted using helix-style.xml

### CODE REVIEW

File: helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+import com.google.common.collect.Sets;
+
+
+/**
+ * Test to check if waitToStop method correctly throws an Exception if Queue stuck in STOPPING
+ * state.
+ */
+public class TestStoppingQueueFailToStop extends TaskTestBase {
+  private static final String DATABASE = WorkflowGenerator.DEFAULT_TGT_DB;
+  protected HelixDataAccessor _accessor;
```
Comment (pkuwm) [inline helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java:55]: Is this unused?

File: helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java [hunk 2]
```diff
@@ -0,0 +1,137 @@
...
+  private boolean TASK_STOPPABLE = false;
```
Comment (pkuwm) [inline helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java:56]: Why upper case for a private field?

File: helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java [hunk 3]
```diff
@@ -0,0 +1,137 @@
...
+
+    NewMockTask(TaskCallbackContext context) {
+      super(context);
+    }
+
+    @Override
+    public void cancel() {
+      while (!TASK_STOPPABLE) {
+        try {
+          Thread.sleep(1000L);
```
Comment (pkuwm) [inline helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java:129]: This while-loop-sleep doesn't look the best option. Would a countdown solve this wait better?

File: helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java [hunk 4]
```diff
@@ -0,0 +1,137 @@
...
+import org.apache.helix.task.TaskDriver;
+import org.apache.helix.task.TaskFactory;
+import org.apache.helix.task.TaskState;
+import org.apache.helix.task.TaskStateModelFactory;
+import org.apache.helix.task.TaskUtil;
+import org.testng.Assert;
+import org.testng.annotations.BeforeClass;
+import org.testng.annotations.Test;
+
+import com.google.common.collect.ImmutableMap;
```
Comment (pkuwm) [inline helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java:45]: It doesn't seem these imports are formatted by helix-style?

Comment (alirezazamani) [reply helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java:42]: I just did reformat.

File: helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java (hunk 1 above)
Comment (alirezazamani) [reply helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java]: Deleted.

File: helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java (hunk 3 above)
Comment (alirezazamani) [reply helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java]: No. We want to be in this loop for a long time until in the main part of the test we want to the task to stop.

File: helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java (hunk 2 above)
Comment (alirezazamani) [reply helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java]: Changed. Thanks.

**Comment by alirezazamani** [comment]
This PR is ready to be merged, approved by @dasahcc

Final commit message:
Fix waitToStop method in TaskDriver

In this commit, waitToStop has been changed to make sure workflow/queue is in stopped state if waitToStop returns successfully without Exception. 
When the queue targetState is set to stop, the queue will go to STOPPING state. STOPPING state is a transient state which means some of the jobs has not ben completely stopped or in terminal state. In other words, some of the tasks within the jobs have not reached the terminal state yet.

File: helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java [hunk 5]
```diff
@@ -0,0 +1,132 @@
...
+
+    NewMockTask(TaskCallbackContext context) {
+      super(context);
+    }
+
+    @Override
+    public void cancel() {
+      while (!_taskStoppable) {
+        try {
+          Thread.sleep(1000L);
```
Comment (pkuwm) [inline helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java:124]: If I understand the logic here right, Countdown latch does exactly the job you need and does it better. Countdown latch could await until latch is release. I may not have insisted this since it is a test. But I am curious. Could you help understand why countdown latch doesn’t solve this? Isn’t it better than this high cpu switch  sleep polling?

Comment (alirezazamani) [reply helix-core/src/test/java/org/apache/helix/integration/task/TestStoppingQueueFailToStop.java]: Done.
