### PR TITLE
Populate helix cloud property using cloud config

### LINKED ISSUE #1985: Helix HelixManagerProperty with null cloudConfig causing null ptr error when participant auto join.
### Describe the bug
Helix user notice that when ZooScalability is enabled, property configured helix cloud participant could not auto register in cluster. This is because when ZooScalability is enabled, Helix need user to pass a cloudConfig object when initiating ZkHelixManager. Helix does not read cloudConfig from ZK.

### To Reproduce
This is constantly reproducible. Cloud participant will fail to join cluster with correct cloud config. 

### Expected behavior
When participant has correct cloudConfig, it should be able to join cluster when no cloudConfig object is passed to ZkHelixManager constructor.

### PR DESCRIPTION
**Pull request by mgao0**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1985

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

This is a fix based on a previous [PR](https://github.com/apache/helix/pull/1986). The previous PR retrieves cloud config from zk and replace entire HelixCloudProperty object, which may cause some fields that user pass in in HelixCloudProperty that are not  included in cloud config get missing. This commit changes the logic to only populate fields in HelixCloudProperty with values that are present in cloud config, and leave other fields unchanged.

### Tests

- [x] The following tests are written for this issue:

TestMultiZkHelixJavaApis.testZKHelixManagerCloudConfig

- The following is the result of the "mvn test" command on the appropriate module:

[info] ./helix-core/target/surefire-reports/TestSuite.txt: Tests run: 1296, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5,863.791 s - in TestSuite

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/HelixManagerProperty.java [hunk 1]
```diff
@@ -66,11 +66,8 @@ private HelixManagerProperty(String version, long healthReportLatency,
   }
 
   public HelixCloudProperty getHelixCloudProperty() {
-    return _helixCloudProperty;
-  }
-
-  public void setHelixCloudProperty(CloudConfig cloudConfig) {
-    _helixCloudProperty = new HelixCloudProperty(cloudConfig);
+    return _helixCloudProperty == null ? HelixCloudProperty.EMPTY_HELIX_CLOUD_PROPERTY
+        : _helixCloudProperty;
```
Comment (qqu0127) [inline helix-core/src/main/java/org/apache/helix/HelixManagerProperty.java:70]: Can we pre-populate the default value so that `_helixCloudProperty` is always not null?

**Comment by junkaixue** [comment]
Have a test for this change of code?

File: helix-core/src/main/java/org/apache/helix/HelixManagerProperty.java (hunk 1 above)
Comment (mgao0) [reply helix-core/src/main/java/org/apache/helix/HelixManagerProperty.java:70]: Thanks for the suggestion, but pre-populate default value won't help here because this variable is assigned in `HelixManagerProperty` constructor, not in a setter. So if null is passed into the constructor, even with pre-populated value, it will still be assigned to null.

File: helix-core/src/main/java/org/apache/helix/HelixCloudProperty.java [hunk 2]
```diff
@@ -69,16 +69,28 @@
...
    * @param
    */
   public HelixCloudProperty(CloudConfig cloudConfig) {
+    this();
+    populateFieldsWithCloudConfig(cloudConfig);
+  }
+
+  public void populateFieldsWithCloudConfig(CloudConfig cloudConfig) {
+    if (cloudConfig == null || !cloudConfig.isCloudEnabled()) {
+      reset();
```
Comment (xyuanlu) [inline helix-core/src/main/java/org/apache/helix/HelixCloudProperty.java:87]: Can we create a default CloudConfig using `buildEmptyCloudConfig()` and populate the fields in cloudConfig to cloudProperty? 
It would be simpler I guess.

Comment (mgao0) [reply helix-core/src/main/java/org/apache/helix/HelixCloudProperty.java:87]: It will still skip the assignments to the variables because `cloudConfig.isCloudEnabled` returns false. But this reminds me, maybe I should change the assignment logic in this method. Let me try and update the PR if it works.

File: helix-core/src/main/java/org/apache/helix/HelixManagerProperty.java (hunk 1 above)
Comment (qqu0127) [reply helix-core/src/main/java/org/apache/helix/HelixManagerProperty.java]: Thanks for the info.
`it will still be assigned to null.` This is technically right, but is also the confusing part. Does a null value make sense or even be accessible at all? The public getter returns either the non-null assigned value, or an empty new instance. If possible, let's try to do the null check at assignment time. Also please let me know if I misunderstood anything.

Comment (mgao0) [reply helix-core/src/main/java/org/apache/helix/HelixManagerProperty.java]: Thanks for explaining. I was trying to prevent a potential NPE so I return a new instance instead of null, but practically the old code doesn't have functionality concerns.
Do a null check at assignment time is technically correct but is not necessary because:
1. There are multiple places (two constructors and a setter function) that this value is set, so this can lead to duplicated code.
2. There are Helix managers that will not be related to cloud at all, so this field is not useful. If we assign default value to it, it can cause memory waste.
I modified my change to do lazy instantiation on this field, but kept it in the getter. Hope you find this reasonable. Thanks.

File: helix-core/src/main/java/org/apache/helix/HelixCloudProperty.java (hunk 2 above)
Comment (mgao0) [reply helix-core/src/main/java/org/apache/helix/HelixCloudProperty.java]: Updated! @xyuanlu

File: helix-core/src/main/java/org/apache/helix/HelixManagerProperty.java (hunk 1 above)
Comment (qqu0127) [reply helix-core/src/main/java/org/apache/helix/HelixManagerProperty.java]: That makes sense, thanks.

File: helix-core/src/main/java/org/apache/helix/model/CloudConfig.java [hunk 3]
```diff
@@ -94,6 +94,10 @@ public CloudConfig(String cluster, boolean enabled, CloudProvider cloudProvider,
     }
   }
 
+  public static CloudConfig buildEmptyCloudConfig() {
```
Comment (xyuanlu) [inline helix-core/src/main/java/org/apache/helix/model/CloudConfig.java:97]: Do you think is it better to change this to a default constructor?

**Comment by xyuanlu** [comment]
Thanks for addressing the comment. 
Generally looks good to me.

File: helix-core/src/main/java/org/apache/helix/model/CloudConfig.java (hunk 3 above)
Comment (mgao0) [reply helix-core/src/main/java/org/apache/helix/model/CloudConfig.java]: Good point. Updated.

**Comment by junkaixue** [comment]
@xyuanlu do you mean approval for this PR? If yes, then just review with approval  option.

File: helix-core/src/main/java/org/apache/helix/HelixPropertyFactory.java [hunk 4]
```diff
@@ -113,10 +109,10 @@ public static CloudConfig getCloudConfig(String zkAddress, String clusterName) {
       // The try-catch logic is for backward compatibility reason only. Even if the cluster is not set
       // up yet, constructing a new ZKHelixManager should not throw an exception
       try {
-        cloudConfig = configAccessor.getCloudConfig(clusterName) == null ? buildEmptyCloudConfig()
+        cloudConfig = configAccessor.getCloudConfig(clusterName) == null ? new CloudConfig()
             : configAccessor.getCloudConfig(clusterName);
```
Comment (qqu0127) [inline helix-core/src/main/java/org/apache/helix/HelixPropertyFactory.java:113]: This queries cloudConfig twice, and not atomic... Can we assign it with `configAccessor.getCloudConfig(clusterName)` first and then do null check? 
(sorry I missed this one in the first pass)

Comment (mgao0) [reply helix-core/src/main/java/org/apache/helix/HelixPropertyFactory.java]: Updated.

**Review by qqu0127 — APPROVED** [review]
LGTM, thanks for addressing the comments

**Comment by mgao0** [comment]
This PR is ready to be merged, approved by @qqu0127 .
