### PR TITLE
Remove a potential deadlock when shutting down a RoutingTableProvider.

### LINKED ISSUE #1748: Deadlock in RoutingTableProvider shutdown process
### Describe the bug
In a race condition, the RoutingTableProvider shutdown process will be deadlocked. In detail, considering the following 2 threads,
Thread A: Application shutdown the provider.
A.1. shutting down all the provider threads.
A.2. lock  _lastSeenSessions in updateCurrentStatesListeners method
A.3. manager.removeListener, lock the HelixManager.
A.4. unlock HelixManager.
A.5. unlock _lastSeenSessions
A.6. Continue other shutting down logic

Thread B (Event processing thread): process Current State change event, and trigger onLiveInstanceChange() of the RoutingTableProvider.
B.1. Lock HelixManager for invoking the listner (RoutingTableProvider.onLiveInstanceChange)
B.2. lock  _lastSeenSessions in updateCurrentStatesListeners method
B.3. manager.removeListener, lock the HelixManager.
B.4. unlock HelixManager.
B.5. unlock _lastSeenSessions
B.6. continue other event processing logic.

Note that on A.3. and B.2., Thread A holds _lastSeenSessions lock, and requests locking HelixManager. While Thread B holds HelixManager lock and requests locking _lastSeenSessions. This is a perfect example of deadlock.

### To Reproduce
I find this bug when investigating testCurrentStatePathLeakingByAsycRemoval() test unstable. Usually, this deadlock only happens in a rare race condition. That's also why the test is not failing definitely.
To guarantee reproducing the issue, we need to temporary suspend the RoutingTableProvider.onLiveInstanceChange methods after the HelixManager is locked. Then we call RoutingTableProvider.shutdown(). After the shutdown() thread is blocked, we can resume the onLiveInstanceChange event handling threads. And the test case or the 2 threads will be locked forever.

### Expected behavior
We shall remove the deadlock.

### Additional context
This bug directly causes https://github.com/apache/helix/issues/1284. I will close issue #1284 and use this issue to track the fix.

### PR DESCRIPTION
**Pull request by jiajunwang**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1748 

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

This PR aims to avoid a potential deadlock that happens in a race condition when shutting down RoutingTableProvider.

The race condition happens when the RoutingTableProvider is shut down and the corresponding HelixManager is processing an onLiveInstanceChange event. Both threads require 2 locks, HelixManager lock, and RoutingTableProvider._lastSeenSessions, in different orders.
To resolve this problem, this PR changes 2 logic.
1. Remove the _lastSeenSessions lock usage. So no more deadlock. The logic correctness is now ensured by the AtomicReference.getAndSet method.
2. Remove LiveInstanceChangeListener in the shutdown call before processing the other logic. This is a missing logic and should be done regardless of the deadlock problem. Moreover, this change also avoids a more complicated race condition introduced by the previous change that may lead to CurrentStates callback handler leakage.

Test cases in TestZkCallbackHandlerLeak have been updated to validate the logic changes.

### Tests

- [X] The following tests are written for this issue:

TestZkCallbackHandlerLeak

I run the test over the weekend, passed continuously 3533 times already.

- The following is the result of the "mvn test" command on the appropriate module:

(If CI test fails due to known issue, please specify the issue and test PR locally. Then copy & paste the result of "mvn test" to here.)

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/spectator/RoutingTableProvider.java [hunk 1]
```diff
@@ -751,51 +754,49 @@ private void updateCurrentStatesListeners(List<LiveInstance> liveInstances,
...
 
-    Map<String, LiveInstance> curSessions = new HashMap<>();
-    for (LiveInstance liveInstance : liveInstances) {
-      curSessions.put(liveInstance.getEphemeralOwner(), liveInstance);
-    }
+    Map<String, LiveInstance> curSessions = liveInstances.stream().collect(
+        Collectors.toConcurrentMap(LiveInstance::getEphemeralOwner, liveInstance -> liveInstance));
 
-    // Go though the live instance list and update CurrentState listeners
-    synchronized (_lastSeenSessions) {
```
Comment (junkaixue) [inline helix-core/src/main/java/org/apache/helix/spectator/RoutingTableProvider.java:764]: Question, if we remove lock, could be there any in memory leakage of watchers?

**Review by junkaixue — COMMENTED** [review]
Overall, looks good

File: helix-core/src/main/java/org/apache/helix/spectator/RoutingTableProvider.java (hunk 1 above)
Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/spectator/RoutingTableProvider.java:764]: Here's my proof: Every _lastSeenSessions update is followed by cleanup. If clean-up does not fail, then we won't have leakage. Otherwise, there is no recovery anyway.
One potential exception is that the shutdown happens earlier than the final onLiveInstance event processing. In this case, the final event processing logic actually sees a clean session record (updated by the shutdown process). However, this is not possible. Because in this PR, I remove the onLiveInstance listener before initializing the shutdown process. It is guaranteed that there is no onLiveInstance event being processed after shutdown.

**Review by junkaixue — APPROVED** [review]

**Comment by jiajunwang** [comment]
Approved by @junkaixue , I will merge the PR.
