### PR TITLE
Fix bugs in ZkRoutingDataReader and ZkRoutingDataWriter

### LINKED ISSUE #828: Fix bugs in ZkRoutingDataReader and ZkRoutingDataWriter
Fix the following bugs:
1. When the routing data is not initialized for a namespace, creating a `ZkRoutingDataReader` for that namespace causes a NoNodeException due to a `getChildren` call. Fix: initialize the base node for routing data across all zookeeper-related actors (`ZkMetadataStoreDirectory`, `ZkRoutingDataReader`, `ZkRoutingDataWriter`)
2. In the `getRoutingData()` method of `ZkRoutingDataReader`, a null check is necessary before getting sharding keys from a realm node, because the realm node may be an invalid ZNRecord. Fix: add null check. 
3. The hostname provided from system properties does not have the protocol. `ZkRoutingDataWriter` was using the hostname directly for request forwarding. Fix: add protocol to the hostname before request forwarding. 
4. `ZkRoutingDataReader`'s `handleDataDeleted` is missing an unsubscribe operation which may lead to watcher leak; `handleChildChange` is missing the resubscription operation. Fix: add both.

### PR DESCRIPTION
**Pull request by NealSun96**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #828, #832 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR fixes the following bugs:
1. When the routing data is not initialized for a namespace, creating a `ZkRoutingDataReader` for that namespace causes a NoNodeException due to a `getChildren` call. Fix: initialize the base node for routing data across all zookeeper-related actors (`ZkMetadataStoreDirectory`, `ZkRoutingDataReader`, `ZkRoutingDataWriter`)
2. In the `getRoutingData()` method of `ZkRoutingDataReader`, a null check is necessary before getting sharding keys from a realm node, because the realm node may be an invalid ZNRecord. Fix: add null check. 
3. The hostname provided from system properties does not have the protocol. `ZkRoutingDataWriter` was using the hostname directly for request forwarding. Fix: add protocol to the hostname before request forwarding. 
4. `ZkRoutingDataReader`'s `handleDataDeleted` is missing an unsubscribe operation which may lead to watcher leak; `handleChildChange` is missing the resubscription operation. Fix: add both.

This PR also introduced an improvement to `MetadataStoreDirectoryAccessor` endpoints. Previously, the endpoints in `MetadataStoreDirectoryAccessor` are missing proper status codes for some cases: for example for `IllegalArgumentException`, it's most fitting to return 400 Bad Request to users, but currently the exception will not be handled and cause a 500 to be returned. 
A change that can fix this issue while improving the status code behavior is to bind exception types with status codes. `NoSuchElementException` should be paired with 404, `IllegalArgumentException` should be paired with 400, while `IllegalStateException` (currently used when underlying ZkClients are closed) should be paired with 500. This has two major benefits:
1. Code maintenance is made easier. The exception types clearly and meaningfully translate to status codes. Developers no longer need to traverse layer by layer to figure out what happened to each exception; all of them are handled at the accessor layer.
2. The status codes are verbose and helpful, because they now contain the underlying exception messages that explain the exact reason behind the exceptions. 

### Tests
- [x] The following is the result of the "mvn test" command on the appropriate module:

[INFO] Tests run: 136, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 22.201 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 136, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  52.954 s
[INFO] Finished at: 2020-02-27T12:06:15-08:00
[INFO] ------------------------------------------------------------------------

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- [x] My diff has been formatted using helix-style.xml

### CODE REVIEW

File: helix-rest/src/main/java/org/apache/helix/rest/metadatastore/accessor/ZkRoutingDataReader.java [hunk 1]
```diff
@@ -134,6 +147,7 @@ public synchronized void handleChildChange(String s, List<String> list) {
 
     // Subscribe data changes again because some children might have been deleted or added
     _zkClient.unsubscribeAll();
+    _zkClient.subscribeChildChanges(MetadataStoreRoutingConstants.ROUTING_DATA_PATH, this);
```
Comment (NealSun96) [inline helix-rest/src/main/java/org/apache/helix/rest/metadatastore/accessor/ZkRoutingDataReader.java]: After making the fix, `handleChildChange` and `handleDataDeleted` are completely equal now. I added a comment on line 127 based on what you told me to justify the duplication - sometimes the callbacks may go missing. Should we consider calling `handleDataDeleted` from `handleChildChange`, for example, to reduce duplication? @narendly

Comment (NealSun96) [reply helix-rest/src/main/java/org/apache/helix/rest/metadatastore/accessor/ZkRoutingDataReader.java]: Resolved offline.

File: helix-rest/src/main/java/org/apache/helix/rest/common/HttpConstants.java [hunk 2]
```diff
@@ -26,4 +26,6 @@
     PUT,
     DELETE
   }
+
+  public static final String HTTP_PROTOCOL = "http://";
```
Comment (narendly) [inline helix-rest/src/main/java/org/apache/helix/rest/common/HttpConstants.java]: Nit: How about something like HTTP_PREFIX?

File: helix-rest/src/main/java/org/apache/helix/rest/metadatastore/accessor/ZkRoutingDataReader.java [hunk 3]
```diff
@@ -90,10 +99,12 @@ public ZkRoutingDataReader(String namespace, String zkAddress,
     for (String realmAddress : allRealmAddresses) {
```
Comment (narendly) [inline helix-rest/src/main/java/org/apache/helix/rest/metadatastore/accessor/ZkRoutingDataReader.java]: Null check on allRealmAddress just in case?

File: helix-rest/src/main/java/org/apache/helix/rest/metadatastore/accessor/ZkRoutingDataReader.java [hunk 4]
```diff
@@ -128,17 +142,7 @@ public synchronized void handleDataDeleted(String s) {
...
-    }
-
-    // Subscribe data changes again because some children might have been deleted or added
-    _zkClient.unsubscribeAll();
-    for (String child : _zkClient.getChildren(MetadataStoreRoutingConstants.ROUTING_DATA_PATH)) {
-      _zkClient.subscribeDataChanges(MetadataStoreRoutingConstants.ROUTING_DATA_PATH + "/" + child,
-          this);
-    }
-    _routingDataListener.refreshRoutingData(_namespace);
+    handleDataDeleted(s);
```
Comment (narendly) [inline helix-rest/src/main/java/org/apache/helix/rest/metadatastore/accessor/ZkRoutingDataReader.java]: Please refactor the logic out into a private method and call it `handleResubscription()` and call it in both of these methods.

File: helix-rest/src/main/java/org/apache/helix/rest/common/HttpConstants.java (hunk 2 above)
Comment (NealSun96) [reply helix-rest/src/main/java/org/apache/helix/rest/common/HttpConstants.java]: Good point, I'll opt for `HTTP_PROTOCAL_PREFIX`. It is a protocol and it is also a prefix.

File: helix-rest/src/main/java/org/apache/helix/rest/metadatastore/accessor/ZkRoutingDataReader.java (hunk 3 above)
Comment (NealSun96) [reply helix-rest/src/main/java/org/apache/helix/rest/metadatastore/accessor/ZkRoutingDataReader.java]: I'll add it, but is that case actually possible?

File: helix-rest/src/main/java/org/apache/helix/rest/metadatastore/accessor/ZkRoutingDataReader.java (hunk 4 above)
Comment (NealSun96) [reply helix-rest/src/main/java/org/apache/helix/rest/metadatastore/accessor/ZkRoutingDataReader.java]: Ack.

**Comment by NealSun96** [comment]
This PR is ready to be merged, approved by @narendly
Final commit message:
## Improve MetadataStoreDirectoryAccessor endpoints and fix bugs in ZkRoutingDataReader/Writer ##
Improve the current status code design of MetadataStoreDirectoryAccessor endpoints by more clearly translate underlying exceptions to status codes. Fix 4 bugs in Reader/Writer.

File: helix-rest/src/main/java/org/apache/helix/rest/metadatastore/accessor/ZkRoutingDataReader.java [hunk 5]
```diff
@@ -87,13 +96,18 @@ public ZkRoutingDataReader(String namespace, String zkAddress,
...
+      for (String realmAddress : allRealmAddresses) {
+        ZNRecord record =
+            _zkClient.readData(MetadataStoreRoutingConstants.ROUTING_DATA_PATH + "/" + realmAddress);
+        if (record != null) {
+          List<String> shardingKeys =
+              record.getListField(MetadataStoreRoutingConstants.ZNRECORD_LIST_FIELD_KEY);
+          routingData
+              .put(realmAddress, shardingKeys != null ? shardingKeys : Collections.emptyList());
+        }
+      }
```
Comment (narendly) [inline helix-rest/src/main/java/org/apache/helix/rest/metadatastore/accessor/ZkRoutingDataReader.java]: format
