### PR TITLE
Fix unexpected result when resuming a cluster from paused/maintenance mode.

### LINKED ISSUE #1661: Flaky test: TestCleanupExternalView.test
### Problem
The test is flaky. It may be due to thread leakage.
```
[ERROR] test(org.apache.helix.integration.TestCleanupExternalView)  Time elapsed: 60.628 s  <<< FAILURE!
java.lang.AssertionError: external-view for TestDB0 should be removed, but was: ZnRecord=TestDB0, {BUCKET_SIZE=0, IDEAL_STATE_MODE=AUTO, NUM_PARTITIONS=2, REBALANCE_MODE=SEMI_AUTO, REBALANCE_STRATEGY=DEFAULT, REPLICAS=2, STATE_MODEL_DEF_REF=MasterSlave, STATE_MODEL_FACTORY_NAME=DEFAULT}{TestDB0_0={localhost_12918=SLAVE, localhost_12919=MASTER}, TestDB0_1={localhost_12918=MASTER, localhost_12919=SLAVE}}{}, Stat=Stat {_version=5, _creationTime=1614716622978, _modifiedTime=1614716623193, _ephemeralOwner=0} expected:<true> but was:<false>
        at org.apache.helix.integration.TestCleanupExternalView.test(TestCleanupExternalView.java:118)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   TestCleanupExternalView.test:118 external-view for TestDB0 should be removed, but was: ZnRecord=TestDB0, {BUCKET_SIZE=0, IDEAL_STATE_MODE=AUTO, NUM_PARTITIONS=2, REBALANCE_MODE=SEMI_AUTO, REBALANCE_STRATEGY=DEFAULT, REPLICAS=2, STATE_MODEL_DEF_REF=MasterSlave, STATE_MODEL_FACTORY_NAME=DEFAULT}{TestDB0_0={localhost_12918=SLAVE, localhost_12919=MASTER}, TestDB0_1={localhost_12918=MASTER, localhost_12919=SLAVE}}{}, Stat=Stat {_version=5, _creationTime=1614716622978, _modifiedTime=1614716623193, _ephemeralOwner=0} expected:<true> but was:<false>


BeforeClass: TestCleanupExternalView called.
START TestCleanupExternalView test at Tue Mar 02 12:23:42 PST 2021
START TestCleanupExternalView_test at Tue Mar 02 12:23:42 PST 2021
pending zk-events in queue: []
3452624 [TestNGInvoker-test()] ERROR org.apache.helix.TestHelper  - verifier time out, consider try longer timeout, stack trace[java.lang.Thread.getStackTrace(Thread.java:1556), org.apache.helix.TestHelper.verify(TestHelper.java:813), org.apache.helix.integration.TestCleanupExternalView.test(TestCleanupExternalView.java:113), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76), org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46), org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511), java.util.concurrent.FutureTask.run(FutureTask.java:266), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)]
END TestCleanupExternalView test at Tue Mar 02 12:24:43 PST 2021, took: 60627ms.
AfterClass: TestCleanupExternalView called.
************ SYSTEM Physical Memory:67386290176
************ total memory:3954 free memory:3148
---------- Test Class TestCleanupExternalView thread leakage detected! ---------------
```

### PR DESCRIPTION
**Pull request by jiajunwang**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:

Resolves #1661 

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

Fix unexpected results when resuming a cluster from paused/maintenance mode.

This PR aims to fix a race condition that the resume event could be pushed to the event queue before the cluster status has been updated. In this case, when the event is processed, the controller might still think the cluster is in paused/maintenance mode. As a result, the resume event is discarded and the rebalance won't be done until the next event happens.

### Tests

- [X] The following tests are written for this issue:

A new test for the race condition is not easy unless we add some stubs for the test only. That will potentially slow the pipeline or introduce confusion. So I suggest that we rely on the existing test to ensure the changes are good. This logic is called in almost all the integration test, so if it has any regression, we shall see many failures.

In addition, I have repeatedly run TestCleanupExternalView more than **295** times. And it works fine.

- The following is the result of the "mvn test" command on the appropriate module:

(If CI test fails due to known issue, please specify the issue and test PR locally. Then copy & paste the result of "mvn test" to here.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/controller/GenericHelixController.java [hunk 1]
```diff
@@ -1469,35 +1463,41 @@ private void shutdownPipeline(Thread thread, ClusterEventBlockingQueue queue)
...
+  private void triggerResumeEvent(NotificationContext changeContext, boolean prevPaused,
+      boolean prevInMaintenanceMode) {
+    /**
+     * WARNING: the logic here is tricky.
+     * 1. Only resume if not paused. So if the Maintenance mode is removed but the cluster is still
+     * paused, the resume event should not be sent.
+     * 2. Only send resume event if the status is changed back to active. So we don't send multiple
+     * event unnecessarily.
+     */
+    if (!_paused && (prevPaused || (prevInMaintenanceMode && !_inMaintenanceMode))) {
```
Comment (dasahcc) [inline helix-core/src/main/java/org/apache/helix/controller/GenericHelixController.java:1495]: Could this check let first event missed when leaderswitch? Because when leaderswitch, prevPaused is false and current paused is false as well.

Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/controller/GenericHelixController.java:1495]: Do we need a resume event for the leaderswitch? I think it would send init event, right?

**Review by dasahcc — APPROVED** [review]

**Comment by jiajunwang** [comment]
Approved by @dasahcc, I will merge soon.
