### PR TITLE
fix TestRawZkClient unstableness

### LINKED ISSUE #1294: Fix flaky test TestRawZkClient.testZkClientMonitor()
LOG:
>2020-08-19T06:04:57.4143926Z [ERROR] testZkClientMonitor(org.apache.helix.zookeeper.impl.client.TestRawZkClient)  Time elapsed: 0.036 s  <<< FAILURE!
2020-08-19T06:04:57.4147601Z java.lang.AssertionError: expected:<0> but was:<1>
2020-08-19T06:04:57.4154957Z 	at org.apache.helix.zookeeper.impl.client.TestRawZkClient.testZkClientMonitor(TestRawZkClient.java:288)
2020-08-19T06:04:57.4155636Z

See the following code, there is a race condition here. connect() would cause a process() callback in zookeeper object eventThread.. If the _monitor is not constructed, the state changed value would be 0, otherwise, it would be 1.

github is slow, the value is 1.
```
 protected ZkClient(IZkConnection zkConnection, int connectionTimeout, long operationRetryTimeout,
      PathBasedZkSerializer zkSerializer, String monitorType, String monitorKey,
      String monitorInstanceName, boolean monitorRootPathOnly) {
    if (zkConnection == null) {
      throw new NullPointerException("Zookeeper connection is null!");
    }

    _uid = UID.getAndIncrement();

    _connection = zkConnection;
    _pathBasedZkSerializer = zkSerializer;
    _operationRetryTimeoutInMillis = operationRetryTimeout;
    _isNewSessionEventFired = false;

    _asyncCallRetryThread = new ZkAsyncRetryThread(zkConnection.getServers());
    _asyncCallRetryThread.start();
    LOG.info("ZkClient created with _uid {}, _asyncCallRetryThread id {}, stack {}", _uid, _asyncCallRetryThread.getId(),
        Arrays.asList(Thread.currentThread().getStackTrace()));

    connect(connectionTimeout, this);

    // initiate monitor
    try {
      if (monitorKey != null && !monitorKey.isEmpty() && monitorType != null && !monitorType
          .isEmpty()) {
        _monitor =
            new ZkClientMonitor(monitorType, monitorKey, monitorInstanceName, monitorRootPathOnly,
                _eventThread);
        _monitor.register();
      } else {
        LOG.info("ZkClient monitor key or type is not provided. Skip monitoring.");
      }
    } catch (JMException e) {
      LOG.error("Error in creating ZkClientMonitor", e);
    }
  }
```

### PR DESCRIPTION
**Pull request by kaisun2000**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fix #1294 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

ZkClient connect to ZooKeeper client first before monitor bean
initialization. If the monitor is not fully constructed, the
test would pass. Otherwise, as in github, it would not. Fix this
issue by properly construct the object.

### Tests

- [x] The following tests are written for this issue:

None

- [x] The following is the result of the "mvn test" command on the appropriate module:

In Old connection New session
After session expiry sessionId= 72277739317428225
Shut down zookeeper at port 2127 in thread main
Starting ZK server at localhost:2358
[INFO] Tests run: 44, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 701.476 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 44, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11:47 min
[INFO] Finished at: 2020-08-19T18:11:02-07:00
[INFO] ------------------------------------------------------------------------
ksun-mn1:zookeeper-api ksun$ git status 

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java [hunk 1]
```diff
@@ -124,6 +125,13 @@
   private PathBasedZkSerializer _pathBasedZkSerializer;
   private ZkClientMonitor _monitor;
 
+  final private String _monitorKey;
```
Comment (jiajunwang) [inline zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:128]: These fields are not helpful to the ZkClient.
Could you try to change the ZkClientMonitor instead so as to avoid these fields? What I am thinking is that, allowing the _eventThread sub-monitor to be added later after the ZkClientMonitor has been constructed. So it can be done in the connect() by referring to _monitor.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/TestHelper.java [hunk 2]
```diff
@@ -32,7 +32,7 @@
 
 public class TestHelper {
   private static final Logger LOG = LoggerFactory.getLogger(TestHelper.class);
-  public static final long WAIT_DURATION = 20 * 1000L; // 20 seconds
+  public static final long WAIT_DURATION = 60 * 1000L; // 20 seconds
```
Comment (jiajunwang) [inline zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/TestHelper.java:35]: 1. the comment is not updated accordingly.
2. Could you please justify the reason we need to triple the wait duration?

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java [hunk 3]
```diff
@@ -285,18 +285,26 @@ public void testZkClientMonitor()
...
-    zkClient.exists(TEST_ROOT);
+    // Note, we need to wait here for the reason that doAsyncSync() blocks only the zkClient event thread. The main
+    // thread of zkClient would issue exits(TEST_ROOT) without blocking. The return of doAsyncSync() would be asyc
+    // to main thread. doAsyncSync() is a source of 1 read and main thread exists(TEST_ROOT) would be another.
+    TestHelper.verify(()->{
+      return ((org.apache.helix.zookeeper.zkclient.ZkClient)zkClient).getSyncStatus();
+    }, TestHelper.WAIT_DURATION);
+
     Assert.assertEquals((long) beanServer.getAttribute(rootname, "ReadCounter"), 1);
+    //Assert.assertEquals((long) beanServer.getAttribute(rootname, "ReadTotalLatencyCounter"), 1);
```
Comment (jiajunwang) [inline zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:302]: What happen to these 2 checks?

Comment (jiajunwang) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:302]: Do we really need this check? If we ensure after exists(), the read is 2, then we shall be good, right?
Note that to check this read counter one by one, we need to add one method just for this purpose. I think it is an overkill and it is not necessary.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java [hunk 4]
```diff
@@ -1281,6 +1279,10 @@ protected void doRetry() throws Exception {
         });
   }
 
+  public boolean getSyncStatus() {
```
Comment (jiajunwang) [inline zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:1282]: I have multiple questions.
1. If this is just for test, please make it package-private.
2. Do we really need to check the read count one by one increase?

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java [hunk 5]
```diff
@@ -2156,6 +2160,21 @@ public void connect(final long maxMsToWaitUntilConnected, Watcher watcher)
 
       LOG.debug("ZkClient created with _uid {}, _eventThread {}", _uid, _eventThread.getId());
 
+      // initiate monitor
+      try {
+        if (_monitorKey != null && !_monitorKey.isEmpty() && _monitorType != null && !_monitorType
+            .isEmpty()) {
+          _monitor =
+              new ZkClientMonitor(_monitorType, _monitorKey, _monitorInstanceName, _monitorRootPathOnly,
```
Comment (pkuwm) [inline zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:2168]: We should consider closing the monitor to avoid leakage. If the later part of code zk connection timeout and throws exception, the monitor should also be closed.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/TestHelper.java (hunk 2 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/TestHelper.java:35]: Github zookeeper is slow. See #1268 for profiling result. Using 60 secs does not really hurt anything, as we still poll the condition every 500ms. 

Otherwise, the test can be flaky.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 3 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:302]: You are right. line 302 and 303 can/should be removed.  The time value is indeterministic. 

line 301 is fine.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java (hunk 5 above)
Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:2168]: My thinking is that ZkClientMonitor does not hold any session object, nor thread. Let GC deal with it would be fine. Or do you see otherwise?

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 3 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:302]: Seems you have concern about this one by increase it one by one https://github.com/apache/helix/pull/1295/files#r474338328

Let me share my thinking here. 

The doAsyncSync() callback finishing is async to main thread here. It can increase the read counter anytime.  Thus, we need TestHelper.verify to wait for this read from sync(). Here, delete line 301  assert is also ok, just wait for 307 having read counter as 2. Same reason, assert 301 is 1 is fine. 

In sum, either way it is fine. But without TestHelper.verify waiting is not fine.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java (hunk 4 above)
Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:1282]: 1/ Will make this package level by removing public.

2/ See my comment https://github.com/apache/helix/pull/1295/files#r474351453. See if this address the concern.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java (hunk 5 above)
Comment (lei-xia) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:2168]: Why we move this into connect()? what problem we try to solve here?

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 3 above)
Comment (jiajunwang) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: 2 ways are different because you will need to add code for supporting the check. If you think both ways of checking are fine, let's do the simpler one.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java [hunk 6]
```diff
@@ -222,22 +226,16 @@ protected ZkClient(IZkConnection zkConnection, int connectionTimeout, long opera
...
-      } else {
-        LOG.info("ZkClient monitor key or type is not provided. Skip monitoring.");
-      }
-    } catch (JMException e) {
-      LOG.error("Error in creating ZkClientMonitor", e);
+    if (monitorKey != null && !monitorKey.isEmpty() && monitorType != null && !monitorType
+        .isEmpty()) {
+      _monitor =
+          new ZkClientMonitor(monitorType, monitorKey, monitorInstanceName, monitorRootPathOnly,
+              _eventThread);
```
Comment (jiajunwang) [inline zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:233]: Let's give it a more complete change.
1. The constructor will not require _eventThread anymore, it will be null anyway.
2. setAndInitZkEventThreadMonitor shall create the event thread monitor and call updateAttributesInfo() to update the attribute. Re-register the whole monitor is wrong, you will end up either having 2 mbeans or the 2nd register will fail.

Comment (jiajunwang) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:233]: Synced with Kai offline, the 2nd point is fine since the register will be postpone to the connect. Given this, I would prefer making the registration logic closer to the monitor construct logic.

So shall we pass the ZkClientMonitor into connect() to explicitly update it in the call. Then register the monitor after the connect(), but still in the constructor.

pseudo code:

_monitor = new ZkClientMonitor();
// Comment that we need to update the _monitor in the event lock to avoid missing any records about event thread.
connect(connectTimeout, this, _monitor);
_monitor.register()

Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:233]: This does not seem to work. 

First  it is not necessary to pass _monitor into `connect(connectTimeout, this, _monitor);` as _monitor is instance variable and connect is method. Connect can see it anyway.

Second, the gist to avoid all these racing issue is that we must make sure _monitor is fully constructed and also register-ed before ZkClient either get callback from ZK.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/ZkTestBase.java [hunk 7]
```diff
@@ -143,7 +143,11 @@ protected ZkServer startZkServer(final String zkAddress) {
     int port = Integer.parseInt(zkAddress.substring(zkAddress.lastIndexOf(':') + 1));
     ZkServer zkServer = new ZkServer(dataDir, logDir, defaultNameSpace, port);
     System.out.println("Starting ZK server at " + zkAddress);
-    zkServer.start();
+    try {
+      zkServer.start();
+    } catch (Exception e) {
```
Comment (pkuwm) [inline zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/ZkTestBase.java:148]: What's the reason to catch exception and print? I guess you want to have the stacktrace for debugging. But please be noted that if exception is thrown, this change will return a zkServer that's not started. I don't think this is what you expected, is it?
I guest keeping it to throw exception so the test would not proceed.

Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/ZkTestBase.java:148]: You are right. Let me re-throw the exception to prevent the test from proceeding.

Without printing it out here, the problem is that Intellij will not print out the exception here. Thus, it seems to be a mystery as why all the test is skipped.

Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/ZkTestBase.java]: Revert this part.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java [hunk 8]
```diff
@@ -285,18 +285,24 @@ public void testZkClientMonitor()
...
+    // Note, we need to wait here for the reason that doAsyncSync() blocks only the zkClient event thread. The main
+    // thread of zkClient would issue exits(TEST_ROOT) without blocking. The return of doAsyncSync() would be asyc
+    // to main thread. doAsyncSync() is a source of 1 read and main thread exists(TEST_ROOT) would be another.
+    TestHelper.verify(()->{
+      return ((org.apache.helix.zookeeper.zkclient.ZkClient)zkClient).getSyncStatus();
+    }, TestHelper.WAIT_DURATION);
+
     Assert.assertEquals((long) beanServer.getAttribute(rootname, "ReadCounter"), 1);
+
+    zkClient.exists(TEST_ROOT);
```
Comment (pkuwm) [inline zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:303]: Nit: If we need to check exits(), we should assert true? I actually don't think it is necessary as below already checks. But if really check, assert true is needed.
```
if (!_zkClient.exists(TEST_ROOT)) {
       _zkClient.createPersistent(TEST_ROOT, true);
}
```

Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:303]: This is not to assert exists() return true. This is to make sure the next `Assert.assertEquals((long) beanServer.getAttribute(rootname, "ReadCounter"), 2);` would be true. Namely this trigger a read and get recorded by bean.

This is not functionality added by me. It is basically line 298 in previous version.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java (hunk 6 above)
Comment (jiajunwang) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:233]: 1. This is to make the code cleaner. It is a good practice for module the code that the private method does not refer to the class private fields directly.

2. The thread monitor is the only one impacted, so if you do the set there, there should be no problem. Mix everything together is chaotic. Ideally, I would suggest splitting the ZK client monitor and ZK thread monitor.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/TestHelper.java (hunk 2 above)
Comment (jiajunwang) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/TestHelper.java:35]: "the comment is not updated accordingly."

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java (hunk 4 above)
Comment (jiajunwang) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:1283]: Sorry that I cannot make the link work. Maybe because code has been changed. Could you please copy-paste your comment here? I still think this is not necessary.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 3 above)
Comment (jiajunwang) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: "But without TestHelper.verify waiting is not fine." why is that? You can TestHelper.verify to wait until the count is 2.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java (hunk 4 above)
Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:1283]: See the discussion above about why think we can't get rid of this getSyncStatus().

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 3 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: Unfortunately, you can't or you have race condition in this case, if my understanding is right. Let me illustrate:

doAsycSync(), when the success code returns, it would increase by read counter one from the asyncThread in the ZkClient. 

Note, the main thread running `zkClient.exist(Test_Root )` would increase read counter synchronously from main thread.

The problem is that the doAsynSync() increase to read counter is totally async to the main thread. It is the case that after main thread finish `zkClient.exist(Test_Root )`, the doAsyncSync() would finish for sure. Recent github test actually illustrate this point. Previous we don't realize as it did not happen.

In fact, theoretically, the doAsyncSync() increase can happen a lot later too. 

Let me know if there is other ways you think that we can make the test stable while also no need to use getSyncStatus().

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/TestHelper.java (hunk 2 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/TestHelper.java:35]: Good point, will update this one. Let us first resolve the bigger issue about how to initialize and how to make test stable.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java (hunk 6 above)
Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:233]: Maybe I mis-understand what do you mean. Can you draw the code a little bit more specific? 

from the above pseduo code

```
_monitor = new ZkClientMonitor();
// Comment that we need to update the _monitor in the event lock to avoid missing any records about event thread.
connect(connectTimeout, this, _monitor);
_monitor.register()
```

construction of ZkMonitor and ZkThreadMonitor and their registration must be done before the first doAsyncSync() is sent out, or you have race condition of missing some read/write.

In the above pseudo code, `_monitor.register()` is too late, the first sycn() is already out and complete earlier than this register().  This violate the above assertion. 

I may not fully understand your idea. Let us be more specific. As long as it works, I can change it to that way.

Comment (jiajunwang) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:233]: The registration does not need to happen prior. Even not registered, the metric can record data.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 3 above)
Comment (jiajunwang) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: Let's sync up tomorrow. I didn't get why waiting for the read count = 2 won't work.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java (hunk 6 above)
Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:231]: I test it. It seems not true. We need to register the bean in connect() under the lock. Otherwise, depends on timing, you may lose one read.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java [hunk 9]
```diff
@@ -2152,6 +2150,19 @@ public void connect(final long maxMsToWaitUntilConnected, Watcher watcher)
 
       IZkConnection zkConnection = getConnection();
       _eventThread = new ZkEventThread(zkConnection.getServers());
+
+      if (_monitor != null) {
+        _monitor.setAndInitZkEventThreadMonitor(_eventThread);
+      }
+
+      try {
```
Comment (kaisun2000) [inline zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:2158]: Note, It seems crucial to register here. Or depending on timing, we may lose read of the first sync().

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java (hunk 4 above)
Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java]: removed.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 3 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java]: changed to waiting for 2

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java (hunk 9 above)
Comment (jiajunwang) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:2158]: I debugged with your code, so the ZkClientPathMonitor objects are currently only created in the register() method. So that's the reason we lose the count if register later.

There is a simple fix, we can instantiate all the ZkClientPathMonitors in the ZkClientMonitor constructor. Like this,
    for (ZkClientPathMonitor.PredefinedPath path : 
```
ZkClientPathMonitor.PredefinedPath.values()) {
      // If monitor root path only, check if the current path is Root.
      // Otherwise, add monitors for every path.
      if (!_monitorRootOnly || path.equals(ZkClientPathMonitor.PredefinedPath.Root)) {
        _zkClientPathMonitorMap.put(path,
            new ZkClientPathMonitor(path, _monitorType, _monitorKey, _monitorInstanceName));
      }
    }
```
Then in the register(), just register all the ZkClientPathMonitor objects that are in the _zkClientPathMonitorMap.

The good thing is that it seems to be the right thing to do.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java [hunk 10]
```diff
@@ -96,6 +96,12 @@ public static ObjectName getObjectName(String monitorType, String monitorKey,
             (monitorKey + (monitorInstanceName == null ? "" : "." + monitorInstanceName)));
   }
 
+  public void setAndInitZkEventThreadMonitor(ZkEventThread zkEventThread) {
+    if (_zkEventThreadMetric == null) {
+      _zkEventThreadMetric = new ZkThreadMetric(zkEventThread);
```
Comment (jiajunwang) [inline zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java:101]: nit, throw Exception if the _zkEventThreadMetric has already been set or the monitor object has already been registered. Otherwise, we may see an unexpected monitor value in the final result.

Comment (jiajunwang) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java:101]: BTW, you can check for registration status by checking _objectName with a synchronized lock on the monitor object.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java [hunk 11]
```diff
@@ -285,18 +285,20 @@ public void testZkClientMonitor()
     Assert.assertTrue(beanServer.isRegistered(idealStatename));
 
     Assert.assertEquals((long) beanServer.getAttribute(name, "DataChangeEventCounter"), 0);
-    Assert.assertEquals((long) beanServer.getAttribute(name, "StateChangeEventCounter"), 0);
+    Assert.assertEquals((long) beanServer.getAttribute(name, "StateChangeEventCounter"), 1);
     Assert.assertEquals((long) beanServer.getAttribute(name, "ExpiredSessionCounter"), 0);
     Assert.assertEquals((long) beanServer.getAttribute(name, "OutstandingRequestGauge"), 0);
-    // account for doAsyncSync()
-    Assert.assertEquals((long) beanServer.getAttribute(name, "TotalCallbackCounter"), 1);
```
Comment (jiajunwang) [inline zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:292]: Is this value still validatable?

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java [hunk 12]
```diff
@@ -31,9 +31,11 @@
 import java.util.concurrent.ConcurrentHashMap;
 import java.util.concurrent.CopyOnWriteArraySet;
 import java.util.concurrent.TimeUnit;
+import java.util.concurrent.atomic.AtomicBoolean;
```
Comment (jiajunwang) [inline zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:34]: no need anymore?

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java [hunk 13]
```diff
@@ -31,9 +31,11 @@
...
 import java.util.concurrent.atomic.AtomicLong;
 import javax.management.JMException;
 
+import com.google.common.annotations.VisibleForTesting;
```
Comment (jiajunwang) [inline zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:38]: With the latest proposal, this one can be removed too.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java [hunk 14]
```diff
@@ -285,18 +285,20 @@ public void testZkClientMonitor()
...
 
-    // Test exists
-    Assert.assertEquals((long) beanServer.getAttribute(rootname, "ReadCounter"), 0);
```
Comment (jiajunwang) [inline zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:295]: Actually, can we wait here before "zkClient.exists(TEST_ROOT);" for ReadCounter == 1. Then wait here for 2? So we ensure exist call will increase one counter too.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java [hunk 15]
```diff
@@ -285,18 +285,20 @@ public void testZkClientMonitor()
...
-    Assert.assertEquals((long) beanServer.getAttribute(rootname, "ReadTotalLatencyCounter"), 0);
-    Assert.assertEquals((long) beanServer.getAttribute(rootname, "ReadLatencyGauge.Max"), 0);
```
Comment (jiajunwang) [inline zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:297]: If you wait for the counter in the previous line, then here we can still check for

    Assert.assertTrue((long) beanServer.getAttribute(rootname, "ReadTotalLatencyCounter") >= 0);
    Assert.assertTrue((long) beanServer.getAttribute(rootname, "ReadLatencyGauge.Max") >= 0);	    

right?

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java [hunk 16]
```diff
@@ -285,18 +285,20 @@ public void testZkClientMonitor()
...
+
+    // Assert.assertEquals((long) beanServer.getAttribute(rootname, "ReadCounter"), 2);
+    // wait for both doAysncSync() finish and zkClient.exists(Test_ROOT) finish from 2 different threads.
+    // The condition would be ReadCounter is 2.
+    boolean verifyResult = TestHelper.verify(()->{
+       return (long) beanServer.getAttribute(rootname, "ReadCounter") == 2;
+    }, TestHelper.WAIT_DURATION);
+    Assert.assertTrue(verifyResult, " did not see 2 read yet");
+
     Assert.assertTrue((long) beanServer.getAttribute(rootname, "ReadTotalLatencyCounter") >= 0);
```
Comment (jiajunwang) [inline zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:302]: I propose that we record the ReadTotalLatencyCounter that we get before exists() call. Then we check if this counter is equal to the previous value or is increased here.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java [hunk 17]
```diff
@@ -285,18 +285,20 @@ public void testZkClientMonitor()
...
     Assert.assertTrue((long) beanServer.getAttribute(rootname, "ReadLatencyGauge.Max") >= 0);
```
Comment (jiajunwang) [inline zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:303]: If we checked "ReadLatencyGauge.Max" before, then this one can be ignored.

**Review by jiajunwang — COMMENTED** [review]
I took a deeper look at the test logic. Since this might be the most important test in our code base, let's be careful to not lose any coverage.

For more details, we can discuss in next week's meeting.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java (hunk 10 above)
Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java:101]: What type of exception would be good here?

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java (hunk 12 above)
Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:34]: fix.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java (hunk 13 above)
Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:38]: fixed.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java (hunk 10 above)
Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java:101]: Let me put a return value as false and let the calling layer log error

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 17 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:303]: fixed.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 16 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:302]: fixed.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 14 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:295]: right.

File: zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java (hunk 11 above)
Comment (kaisun2000) [reply zookeeper-api/src/test/java/org/apache/helix/zookeeper/impl/client/TestRawZkClient.java:292]: no, not realiably I guess.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java (hunk 9 above)
Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java:2158]: implemeted this way

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java [hunk 18]
```diff
@@ -38,9 +38,13 @@
 import org.apache.helix.monitoring.mbeans.dynamicMBeans.SimpleDynamicMetric;
 import org.apache.helix.monitoring.mbeans.exception.MetricException;
 import org.apache.helix.zookeeper.zkclient.ZkEventThread;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 
 
 public class ZkClientMonitor extends DynamicMBeanProvider {
+  private static final Logger LOG = LoggerFactory.getLogger(ZkClientMonitor.class);
```
Comment (jiajunwang) [inline zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java:46]: _logger exists in the super class. There is no need to add a new one here.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java [hunk 19]
```diff
@@ -109,12 +135,8 @@ public DynamicMBeanProvider register() throws JMException {
...
         getObjectName(_monitorType, _monitorKey, _monitorInstanceName));
     for (ZkClientPathMonitor.PredefinedPath path : ZkClientPathMonitor.PredefinedPath.values()) {
-      // If monitor root path only, check if the current path is Root.
-      // Otherwise, add monitors for every path.
-      if (!_monitorRootOnly || path.equals(ZkClientPathMonitor.PredefinedPath.Root)) {
-        _zkClientPathMonitorMap.put(path,
-            new ZkClientPathMonitor(path, _monitorType, _monitorKey, _monitorInstanceName)
-                .register());
+      if (_zkClientPathMonitorMap.get(path) != null)  {
+        _zkClientPathMonitorMap.get(path).register();
```
Comment (jiajunwang) [inline zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java:139]: nit, it could be simpler to be:

_zkClientPathMonitorMap.values().stream().foreach(...);

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientPathMonitor.java [hunk 20]
```diff
@@ -32,6 +32,9 @@
 import org.apache.helix.monitoring.mbeans.dynamicMBeans.DynamicMetric;
 import org.apache.helix.monitoring.mbeans.dynamicMBeans.HistogramDynamicMetric;
 import org.apache.helix.monitoring.mbeans.dynamicMBeans.SimpleDynamicMetric;
+import org.apache.helix.zookeeper.zkclient.ZkClient;
```
Comment (jiajunwang) [inline zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientPathMonitor.java:35]: Unnecessary?

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java (hunk 18 above)
Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java:46]: fixed.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientPathMonitor.java (hunk 20 above)
Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientPathMonitor.java:35]: removed.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java (hunk 19 above)
Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java]: There are many ways to write a loop and now we have stream. 

Still, I will just change it anyway.

**Review by jiajunwang — APPROVED** [review]
LGTM! Please address the last comment.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientPathMonitor.java [hunk 21]
```diff
@@ -34,6 +34,7 @@
 import org.apache.helix.monitoring.mbeans.dynamicMBeans.SimpleDynamicMetric;
 
 
+
```
[the remark this answers is not in the document]
Comment (kaisun2000) [reply zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientPathMonitor.java]: removed.

**Comment by kaisun2000** [comment]
This diff is approved. Please help to merge

>ZkClient connects to ZooKeeper client first before monitor bean
initialization and registration. This cause race condition that fails
metrics test.Fix this issue by properly construct the object.

File: zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java [hunk 22]
```diff
@@ -96,7 +96,7 @@ public ZkClientMonitor(String monitorType, String monitorKey, String monitorInst
 
     for (ZkClientPathMonitor.PredefinedPath path : ZkClientPathMonitor.PredefinedPath.values()) {
       // If monitor root path only, check if the current path is Root.
-      // Otherwise, add monitors for every path.
+      // Otherwise, add monitors for every  path.
```
Comment (jiajunwang) [inline zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/metric/ZkClientMonitor.java:99]: nit, but could you please revert this "touch" change?

**Comment by jiajunwang** [comment]
@kaisun2000 Please run helix-core tests since the change impacts almost all logics.

**Comment by jiajunwang** [comment]
@kaisun2000 you can rerun the test job in Github UI. There is no need to touch code for a re-run.

**Comment by pkuwm** [comment]
I've triggered rerun the workflow. 
FYI, @kaisun2000 This is a button for us to **Re-run jobs**.
image

**Comment by kaisun2000** [comment]
@jiajunwang, @pkuwm, as we looked, my github page does not have this UI button to re-run. Other than that, any other concerns? Or let us merge this in.

**Comment by pkuwm** [comment]
> @jiajunwang, @pkuwm, as we looked, my github page does not have this UI button to re-run. Other than that, any other concerns? Or let us merge this in.

@kaisun2000 I've helped re-run all the jobs.

File: helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java [hunk 23]
```diff
@@ -215,7 +215,7 @@ public void testANYtypeThrottle() throws InterruptedException {
     DelayedTransition.setDelay(20);
     DelayedTransition.enableThrottleRecord();
 
-    // start another 3 nodes
+    // start another 3 nodes
```
Comment (jiajunwang) [inline helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java:218]: Please remove the extra space before merge.

Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/integration/TestPartitionMovementThrottle.java]: removed.

**Comment by kaisun2000** [comment]
@jiajunwang, removed the extra space to trigger run from my side. Please help to merge.
