### PR TITLE
Stabilize TestEnqueueJobs 

### LINKED ISSUE #1345: TestEnqueueJobs is unstable
### Describe the bug
TestEnqueueJobs is unstable due to not stopping the queue before adding a job.

### To Reproduce
Keep adding a jobs to the queue in a loop without stop and resuming it.

### Expected behavior
It is recommended to stop the queue, add the job and resume the queue. Also, if there are many jobs needs to be added to a queue, it is recommended to use batch enqueueing the job.

### PR DESCRIPTION
**Pull request by alirezazamani**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:
Fixes #1345 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
In this PR TestEnqueueJobs has been stabilized by stopping the queue before addition and resuming it after adding the new jobs. Also, instead of adding job one by one, batch enqueue job has been used.

### Tests
- [x] The following is the result of the "mvn test" command on the appropriate module:

```
[ERROR] Failures: 
[ERROR]   TestDisableCustomCodeRunner.test:233 expected:<false> but was:<true>
[ERROR]   TestEnableCompression.testEnableCompressionResource:117 expected:<true> but was:<false>
[INFO] 
[ERROR] Tests run: 1200, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:18 h
[INFO] Finished at: 2020-09-03T15:52:44-07:00
[INFO] ------------------------------------------------------------------------
```

The failed test passed when run individually.
mvn test -Dtest="TestDisableCustomCodeRunner,TestEnableCompression"
```
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 34.693 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  40.827 s
[INFO] Finished at: 2020-09-03T16:00:18-07:00
[INFO] ------------------------------------------------------------------------
```

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Comment by kaisun2000** [comment]
Thanks for the effort to stabilize this test. A related question:

 #1278 TestEnqueueJobs.testQueueJobsMaxCapacity, and #1310 TestEnqueueJobs.testJobQueueAddingJobsAtSametime are also not stable sometimes. They timed out. Do they share similar root cause?

**Comment by kaisun2000** [comment]
Also, you may need this config change to let github to finish mvn test; 
https://github.com/apache/helix/pull/1335

File: helix-core/src/test/java/org/apache/helix/integration/task/TestEnqueueJobs.java [hunk 1]
```diff
@@ -135,10 +146,18 @@ public void testQueueParallelJobs() throws InterruptedException {
...
+
     // Add 4 jobs to the queue
+    List<String> jobNames = new ArrayList<>();
+    List<JobConfig.Builder> jobBuilders = new ArrayList<>();
     for (int i = 0; i < numberOfJobsAddedBeforeControllerSwitch; i++) {
-      _driver.enqueueJob(queueName, "JOB" + i, jobBuilder);
+      jobNames.add("JOB" + i);
+      jobBuilders.add(jobBuilder);
     }
+    _driver.enqueueJobs(queueName, jobNames, jobBuilders);
```
Comment (dasahcc) [inline helix-core/src/test/java/org/apache/helix/integration/task/TestEnqueueJobs.java:158]: From my understanding, is this batching operation helped? It should impact the testing result, right? As long as the queue is STOPPED, the number of jobs added to queue one by one should not matter the final result before resume?

Comment (alirezazamani) [reply helix-core/src/test/java/org/apache/helix/integration/task/TestEnqueueJobs.java:158]: Yeah. Batching would help. The issue seems to be in the nature of Helix/ZK if user adds jobs in a row. So if this is the behavior, it is better to do batch job addition. So let's say user is adding jobs one by one. Let's say user is job1, job2 and job3. 
At T1: Job1 and job2 are added and jobDAG is changed.
At T2: We get children of config and know new configs of job1 and job2 and change in DAG.
At T3: job3 is added and is being added to DAG.
At T4: Refresh is started and and controller see config of job1, job2 and DAG will be Job1, job2 and job3.
Now in the pipeline since we see job3 in the DAG and we do not see config, we purge job3 and remove config from ZK. Hence job3 will not be finished at all.

**Review by dasahcc — APPROVED** [review]
LGTM. As we discussed, let's create a issue to track it.

**Comment by alirezazamani** [comment]
This PR is ready to be merged.

File: helix-core/src/test/java/org/apache/helix/integration/task/TestEnqueueJobs.java (hunk 1 above)
Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/integration/task/TestEnqueueJobs.java:158]: This fix only minimize the change, it does not really eliminate the chance.

The really issue is the race condition of workFlowControllerDataProvider updating sequence and job config and workflow config updating sequence. I will write a doc later to illustrate the cases here and potentially proposed solution.
