### PR TITLE
fix TestCrushAutoRebalanceNonRack.testLackEnoughInstances unstable issue (#1630)

### LINKED ISSUE #1630: Flaky test TestCrushAutoRebalanceNonRack. testLackEnoughInstances
Log> [ERROR] testLackEnoughInstances(org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceNonRack)  Time elapsed: 0.545 s  <<< FAILURE!
2021-02-04T02:19:29.8130317Z org.apache.helix.HelixException: Failed to drop instance: localhost_12920. Retry times: 3
2021-02-04T02:19:29.8134877Z 	at org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceNonRack.testLackEnoughInstances(TestCrushAutoRebalanceNonRack.java:281)
2021-02-04T02:19:29.8142900Z Caused by: org.apache.helix.zookeeper.exception.ZkClientException: Failed to delete /CLUSTER_TestCrushAutoRebalanceNonRack/INSTANCES/localhost_12920/MESSAGES
2021-02-04T02:19:29.8148267Z 	at org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceNonRack.testLackEnoughInstances(TestCrushAutoRebalanceNonRack.java:281)
2021-02-04T02:19:29.8154189Z Caused by: org.apache.helix.zookeeper.zkclient.exception.ZkException: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /CLUSTER_TestCrushAutoRebalanceNonRack/INSTANCES/localhost_12920/MESSAGES
2021-02-04T02:19:29.8160075Z 	at org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceNonRack.testLackEnoughInstances(TestCrushAutoRebalanceNonRack.java:281)
2021-02-04T02:19:29.8165107Z Caused by: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /CLUSTER_TestCrushAutoRebalanceNonRack/INSTANCES/localhost_12920/MESSAGES
2021-02-04T02:19:29.8170141Z 	at org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceNonRack.testLackEnoughInstances(TestCrushAutoRebalanceNonRack.java:281)
2021-02-04T02:19:29.8173864Z 
2021-02-04T02:19:29.8176834Z [ERROR] testLackEnoughInstances(org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceNonRack)  Time elapsed: 0.015 s  <<< FAILURE!
2021-02-04T02:19:29.8181238Z org.apache.helix.HelixException: Cluster CLUSTER_TestCrushAutoRebalanceNonRack, instance: localhost_12920, instance config does not exist
2021-02-04T02:19:29.8187135Z 	at org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceNonRack.testLackEnoughInstances(TestCrushAutoRebalanceNonRack.java:273)
2021-02-04T02:19:29.8282933Z 
2021-02-04T02:19:29.8289351Z [ERROR] testLackEnoughInstances(org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceTopoplogyAwareDisabled)  Time elapsed: 0.552 s  <<< FAILURE!
2021-02-04T02:19:29.8306843Z org.apache.helix.HelixException: Failed to drop instance: localhost_12920. Retry times: 3
2021-02-04T02:19:29.8312848Z 	at org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceTopoplogyAwareDisabled.testLackEnoughInstances(TestCrushAutoRebalanceTopoplogyAwareDisabled.java:86)
2021-02-04T02:19:29.8332444Z Caused by: org.apache.helix.zookeeper.exception.ZkClientException: Failed to delete /CLUSTER_TestCrushAutoRebalanceTopoplogyAwareDisabled/INSTANCES/localhost_12920/MESSAGES
2021-02-04T02:19:29.8339283Z 	at org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceTopoplogyAwareDisabled.testLackEnoughInstances(TestCrushAutoRebalanceTopoplogyAwareDisabled.java:86)
2021-02-04T02:19:29.8346898Z Caused by: org.apache.helix.zookeeper.zkclient.exception.ZkException: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /CLUSTER_TestCrushAutoRebalanceTopoplogyAwareDisabled/INSTANCES/localhost_12920/MESSAGES
2021-02-04T02:19:29.8354598Z 	at org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceTopoplogyAwareDisabled.testLackEnoughInstances(TestCrushAutoRebalanceTopoplogyAwareDisabled.java:86)
2021-02-04T02:19:29.8425842Z Caused by: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /CLUSTER_TestCrushAutoRebalanceTopoplogyAwareDisabled/INSTANCES/localhost_12920/MESSAGES
2021-02-04T02:19:29.8436793Z 	at org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceTopoplogyAwareDisabled.testLackEnoughInstances(TestCrushAutoRebalanceTopoplogyAwareDisabled.java:86)
2021-02-04T02:19:29.8441831Z 
2021-02-04T02:19:30.2150311Z [ERROR] Failures: 
2021-02-04T02:19:30.2158585Z [ERROR] org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceNonRack.testLackEnoughInstances(org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceNonRack)
2021-02-04T02:19:30.2196371Z [ERROR]   Run 1: TestCrushAutoRebalanceNonRack.testLackEnoughInstances:281 » Helix Failed to dr...
2021-02-04T02:19:30.2199157Z [ERROR]   Run 2: TestCrushAutoRebalanceNonRack.testLackEnoughInstances:273 » Helix Cluster CLUS...
2021-02-04T02:19:30.2207049Z [ERROR] org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceTopoplogyAwareDisabled.testLackEnoughInstances(org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceTopoplogyAwareDisabled)
2021-02-04T02:19:30.2216641Z [ERROR]   Run 2: TestCrushAutoRebalanceTopoplogyAwareDisabled.testLackEnoughInstances:86->TestCrushAutoRebalanceNonRack.testLackEnoughInstances:281 » Helix
2021-02-04T02:19:30.2219427Z [ERROR] Tests run: 1257, Failures: 2, Errors: 0, Skipped: 0
2021-02-04T02:19:30.2296392Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project helix-core: There are test failures.

code>
```
  public void testLackEnoughInstances(String rebalanceStrategyName, String rebalanceStrategyClass)
      throws Exception {
    System.out.println("TestLackEnoughInstances " + rebalanceStrategyName);
    enablePersistBestPossibleAssignment(_gZkClient, CLUSTER_NAME, true);

    // shutdown participants, keep only two left
    HelixDataAccessor helixDataAccessor =
        new ZKHelixDataAccessor(CLUSTER_NAME, InstanceType.PARTICIPANT, _baseAccessor);
    for (int i = 2; i < _participants.size(); i++) {
      MockParticipantManager p = _participants.get(i);
      p.syncStop();
      _gSetupTool.getClusterManagementTool().enableInstance(CLUSTER_NAME, p.getInstanceName(),
          false);
      Assert.assertTrue(TestHelper.verify(() -> {
        _gSetupTool.getClusterManagementTool()
            .enableInstance(CLUSTER_NAME, p.getInstanceName(), false);
        return !InstanceValidationUtil.isEnabled(helixDataAccessor, p.getInstanceName())
            && !InstanceValidationUtil.isAlive(helixDataAccessor, p.getInstanceName());
      }, TestHelper.WAIT_DURATION), "Instance should be disabled and offline");
      _gSetupTool.dropInstanceFromCluster(CLUSTER_NAME, p.getInstanceName());
    }

```

### PR DESCRIPTION
**Pull request by kaisun2000**
### Issues

- [ ] My PR addresses the following Helix issues and references them in the PR description:

resolve #1630 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
   fix TestCrushAutoRebalanceNonRack.testLackEnoughInstances unstable issue (#1630)
    This test still fails in production due to race condition that controller
    may see liveinstance already disabled and send messages to them. Thus
    when dropping the instance with messages in Zk would cause exception.

### Tests

- [ ] The following tests are written for this issue:

(List the names of added unit/integration tests)

- The following is the result of the "mvn test" command on the appropriate module:

(If CI test fails due to known issue, please specify the issue and test PR locally. Then copy & paste the result of "mvn test" to here.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java [hunk 1]
```diff
@@ -278,6 +280,17 @@ public void testLackEnoughInstances(String rebalanceStrategyName, String rebalan
...
+
+      // There is still a possibility that controller may see the liveinstance before the instance
+      // is stopped, even from admin tool perspective the node is not alive and disabled. Thus sending
+      // messages before or during instance getting dropped.
+      Assert.assertTrue(TestHelper.verify(() -> {
+        PropertyKey.Builder propertyKeyBuilder = helixDataAccessor.keyBuilder();
+        Message messages =
+            helixDataAccessor.getProperty(propertyKeyBuilder.messages(p.getInstanceName()));
+        return messages == null;
+      }, TestHelper.WAIT_DURATION));
```
Comment (pkuwm) [inline helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java:292]: As synced offline, checking messages empty is not good enough as messages might be sent before dropping instance and hence the test will be flaky again. We should ensure the state is stable after instance is disabled, so messages won't be sent to the instance. Then dropping instance is safe.

Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java]: Right. In fact, the more fundamental issue seems to be liek this:
Dropping instance from test or admin tool vs controller adding messages to the same instance are async operations. The have race condition fundamentally. This also happens in production. This is a design flaw in Helix IMO. 
That said, to stabilize the test, we can disable controller and enable it again afterward. This is workaround for test, not production though.

**Comment by alirezazamani** [comment]
So here we decided to fix the test instead of the issue? Is there any issue tracking the actual issue aside from this stabilizing the test?

**Comment by kaisun2000** [comment]
> So here we decided to fix the test instead of the issue? Is there any issue tracking the actual problem that can be linked to this PR?

Good point. Here is the issue tracking the production issue. #1640

File: helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java [hunk 2]
```diff
@@ -43,6 +44,7 @@
 import org.apache.helix.model.IdealState;
 import org.apache.helix.model.IdealState.RebalanceMode;
 import org.apache.helix.model.InstanceConfig;
+import org.apache.helix.model.Message;
```
Comment (alirezazamani) [inline helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java:47]: Please remove unused imports

File: helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java [hunk 3]
```diff
@@ -30,6 +30,7 @@
 import org.apache.helix.ConfigAccessor;
 import org.apache.helix.HelixDataAccessor;
 import org.apache.helix.InstanceType;
+import org.apache.helix.PropertyKey;
```
Comment (alirezazamani) [inline helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java:33]: Please remove unused imports

**Review by alirezazamani — APPROVED** [review]
I am ok to check in this fix for the test. Please check with others as well to see if they have any objections or not.

File: helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java [hunk 4]
```diff
@@ -264,6 +266,12 @@ public void testLackEnoughInstances(String rebalanceStrategyName, String rebalan
     System.out.println("TestLackEnoughInstances " + rebalanceStrategyName);
     enablePersistBestPossibleAssignment(_gZkClient, CLUSTER_NAME, true);
 
+    // Drop instance from admin tools and controller sending message to the same instance are
+    // fundamentally async. The race condition can also happen in production.  For now we stabilize
+    // the test by disable controller and re-enable controller to eliminate this race condition as
+    // a workaround. New design is needed to fundamentally resolve the expose issue.
+    _controller.syncStop();
```
Comment (jiajunwang) [inline helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java:273]: Stop the controller will work, but it is not what we do in the production.
Why not using the maintenance mode as I suggested originally?

**Review by jiajunwang — CHANGES_REQUESTED** [review]

File: helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java (hunk 4 above)
Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java:273]: That needs a sleep() afterward. Otherwise, it won't work as it take at least one pipeline run cycle there. 

Are we ok with adding a sleep()?

File: helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java (hunk 2 above)
Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java]: removed.

File: helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java (hunk 3 above)
Comment (kaisun2000) [reply helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java]: removed.

File: helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java (hunk 4 above)
Comment (jiajunwang) [reply helix-core/src/test/java/org/apache/helix/integration/rebalancer/CrushRebalancers/TestCrushAutoRebalanceNonRack.java:271]: Yeah, I get what you said. Let's keep the sync stop here.

**Review by jiajunwang — APPROVED** [review]

**Comment by kaisun2000** [comment]
The PR is approved. Please help to merge. 
>fix TestCrushAutoRebalanceNonRack.testLackEnoughInstances unstable issue (#1630)
This test still fails in production due to race condition that controller
may see liveinstance already disabled and send messages to them. Thus
when dropping the instance with messages in Zk would cause exception.
