### PR TITLE
Test routing data cache

### LINKED ISSUE #1252: Flaky test TestRoutingDataCache
**Describe the bug**
Different mvn versions may have different test running order.
If `testCurrentStatesSelectiveUpdate` is run before the other tests in `TestRoutingDataCache`, the later tests may fail.

**To Reproduce**
Add dependency to make testCurrentStatesSelectiveUpdate run before testUpdateOnNotification.
```
  @Test(dependsOnMethods = "testCurrentStatesSelectiveUpdate")
  public void testUpdateOnNotification()
```

**Expected behavior**
All tests should pass

**Additional context**
It is because one participant is stopped in `testCurrentStatesSelectiveUpdate` but the storage cluster is not rebalanced and cluster state is not verified.

### PR DESCRIPTION
**Pull request by pkuwm**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1252 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Different mvn versions may have different test running order.
If testCurrentStatesSelectiveUpdate is run before the other tests in TestRoutingDataCache, the later tests may fail. This PR fixes the test by adding a new participant to cluster and dropping the participant, verifying cluster state after the test.

### Tests

- [x] The following tests are written for this issue:

(List the names of added unit/integration tests)

- [x] The following is the result of the "mvn test" command on the appropriate module:

(Before CI test pass, please copy & paste the result of "mvn test")

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/test/java/org/apache/helix/spectator/TestRoutingDataCache.java [hunk 1]
```diff
@@ -24,20 +24,21 @@
...
+import org.apache.helix.zookeeper.datamodel.ZNRecord;
 import org.testng.Assert;
 import org.testng.annotations.Test;
 
 public class TestRoutingDataCache extends ZkStandAloneCMTestBase {
 
-  @Test()
-  public void testUpdateOnNotification() throws Exception {
+  @Test
+  public void testUpdateOnNotification() {
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/spectator/TestRoutingDataCache.java:41]: Good work!

Since the original issue mentions that the instability is caused by a non-deterministic execution order of tests, should we add the `dependsOnMethods` annotation to enforce the order across different environments?

Comment (pkuwm) [reply helix-core/src/test/java/org/apache/helix/spectator/TestRoutingDataCache.java:41]: I thought about it. But since `testCurrentStatesSelectiveUpdate` does not necessarily depend on the other two tests, adding dependsOnMethods may hide flaw of test. This test should be independent with other tests -- it should not change the global/parent states that may affect other tests -- it should restore the original states after the method. 

So making it independent should be a better idea: no matter what the running order is, the tests should not fail.

**Comment by pkuwm** [comment]
This PR is ready to be merged, approved by @narendly
