### PR TITLE
[apache/helix] -- Fixes #2646 (Part-1), Optimize WagedInstanceCapacity Calculation to improve Helix Controller Pipeline

### LINKED ISSUE #2646: Optimize WagedInstanceCapacity Calculation to improve Helix Controller Pipeline
### Describe the bug
In WAGED n - n + 1, we filter out the host from the map-field of idealState if it doesn't have capacity to hold the partition. The instance capacity is determined from the resource-partition weights, instance currentState, and pending messages to build WagedInstanceCapacity data structure. This data-structure is computed every time during a pipeline run as any cluster event can cause capacity change. In case of large clusters, this computation takes ~80% of total time and hence, it's important to improve its performance. 

### To Reproduce
This issue is quite apparent in all the integration and release certification tests. 

### Expected behavior
The additional calculation will take some portion of time but should not incur high latency in the overall pipeline runtime.

### PR DESCRIPTION
**Pull request by himanshukandwal**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:
#2646 

### Description
WagedInstanceCapacity data-structure is computed every time during a pipeline run and in case of large clusters, this computation takes ~80% of total time and hence, it's important to improve its performance.

- [x] Here are some details about my PR, including screenshots of any UI changes:

In this PR, we are performing following changes:
* Created `WagedInstanceCapacityManager` class to cleanly factor-out the operations on WagedInstanceCapacity cache. It contains the condition on when the full build of cache should or shouldn't happen. With this we are skipping the full cache building in case of `TaskCurrentStateChange`, `MessageChange`, and `Resume` events.
* In WagedInstanceCapacity, we are creating merged ResourceConfig once to determine the partition weights for all the partitions and not every time for each partition.

### Tests

- [x] `TestWagedInstanceCapacityManager`
* testProcessEventWithNoWagedResources
* testProcessEventWithSomeWagedResources
* testProcessEventWithAllWagedResources
* testShouldNoOp

- [x] `TestWagedInstanceCapacity`
* testProcessCurrentState
* testProcessCurrentStateWithDoubleCharge
* testProcessCurrentStateWithUnableToAssignPart

- [x] `TestPipelinePerformance`
* testWagedInstanceCapacityCalculationPerformance

- The following is the result of the "mvn test" command on the appropriate module:

```console
mvn clean install -Dmaven.test.skip.exec=true && mvn test -o -Dtest=TestWagedInstanceCapacity,TestWagedInstanceCapacityManager -pl=helix-core

1425 [main] ERROR org.apache.helix.model.IdealState [] - could NOT determine replicas. set to 0
1438 [main] ERROR org.apache.helix.model.IdealState [] - could NOT determine replicas. set to 0
1447 [main] ERROR org.apache.helix.model.IdealState [] - could NOT determine replicas. set to 0
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.21 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jacoco:0.8.6:report (generate-code-coverage-report) @ helix-core ---
[INFO] Loading execution data file /Users/hkandwal/Documents/workspaces/projects/helix_os_hk/helix-core/target/jacoco.exec
[INFO] Analyzed bundle 'Apache Helix :: Core' with 949 classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.627 s
[INFO] Finished at: 2023-10-09T15:00:30-07:00
[INFO] ------------------------------------------------------------------------
```

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java [hunk 1]
```diff
@@ -130,28 +136,29 @@ public void processPendingMessages(ResourceControllerDataProvider cache,
...
-      WagedResourceWeightsProvider weightProvider) {
+  void processCurrentState(ResourceControllerDataProvider cache,
+      CurrentStateOutput currentStateOutput, Map<String, Resource> resourceMap) {
 
     // Iterate through all the resources
     for (Map.Entry<String, Resource> entry : resourceMap.entrySet()) {
       String resName = entry.getKey();
       Resource resource = entry.getValue();
 
-      // if Resource is WAGED managed, then we need to manage the capacity.
```
Comment (desaikomal) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java:143]: I am assuming you moved the check for WAGED resource somewhere else?

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java [hunk 2]
```diff
@@ -130,28 +136,29 @@ public void processPendingMessages(ResourceControllerDataProvider cache,
...
+      IdealState is = cache.getIdealState(resName);
+      ResourceConfig mergedResourceConfig =
+          ResourceConfig.mergeIdealStateWithResourceConfig(resourceConfig, is);
+
       for (Partition partition : partitions) {
         String partitionName = partition.getPartitionName();
         // Get Partition Weight
-        Map<String, Integer> partCapacity = weightProvider.getPartitionWeights(resName, partitionName);
+        Map<String, Integer> partCapacity =
+            WagedRebalanceUtil.fetchCapacityUsage(partitionName, mergedResourceConfig, cache.getClusterConfig());
```
Comment (desaikomal) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java:160]: i have 2 questions: 1. do we need to update mergedResourceConfig everytime?   2.  resource/partition weight doesn't change frequently. so where are we caching this value?

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacityManager.java [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+    }
+
+    ResourceControllerDataProvider dataProvider = (ResourceControllerDataProvider) cache;
+    if (Objects.isNull(dataProvider.getWagedInstanceCapacity())) {
+      return false;
+    }
+
+    switch (event.getEventType()) {
+      case TaskCurrentStateChange:
+      case MessageChange:
```
Comment (desaikomal) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacityManager.java:103]: MessageChange - won't this result in change in pendingMessages ?

Comment (desaikomal) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacityManager.java:103]: Looking at ClusterEventType, there are many events for which we can skip re-building cache. 
-  IdealStateChange,  CustomizedStateChange,  CustomizeStateConfigChange,  ExternalViewChange,   CustomizedViewChange,   TargetExternalViewChange,   PeriodicalRebalance,   OnDemandRebalance,     RetryRebalance,
  StateVerifier

**Review by desaikomal — COMMENTED** [review]
Initial comments. will do second pass later. THANKS a lot for working.
wondering if we can have some profile numbers

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java (hunk 1 above)
Comment (himanshukandwal) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java:143]: Yes this has been moved to `WagedInstanceCapacityManager`, as we are passing in only WAGED enabled `Map<String, Resource> resourceMap`.

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java (hunk 2 above)
Comment (himanshukandwal) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java:160]: So earlier, we were computing `mergedResourceConfig` everytime i.e. for each partition of a resource. Now, we are computing this at resource level, and using same for all partitions.

We can cache it as well. Can I do it as part of next PR as to keep the size of this limited and bringing one change at a time..

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacityManager.java (hunk 3 above)
Comment (himanshukandwal) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacityManager.java:103]: Actually yes, let me add these. Thanks @desaikomal

Comment (himanshukandwal) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacityManager.java]: Updated the PR. Thanks for your review. :)

**Comment by himanshukandwal** [comment]
> Initial comments. will do second pass later. THANKS a lot for working. wondering if we can have some profile numbers

Yes, this is quite important. I am working on the Integ test and will share the numbers.

**Comment by himanshukandwal** [comment]
> > Initial comments. will do second pass later. THANKS a lot for working. wondering if we can have some profile numbers
> 

Hey @desaikomal here are the results from the performance testing (CurrentStateComputationStage):

```
durationWithComputation: 502, durationWithoutComputation: 32, pctDecrease: 93.0
durationWithComputation: 996, durationWithoutComputation: 29, pctDecrease: 97.0
```

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacityManager.java [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+    if (resourceMap == null || resourceMap.isEmpty()) {
+      return true;
+    }
+
+    ResourceControllerDataProvider dataProvider = (ResourceControllerDataProvider) cache;
+    if (Objects.isNull(dataProvider.getWagedInstanceCapacity())) {
+      return false;
+    }
+
+    switch (event.getEventType()) {
```
Comment (junkaixue) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacityManager.java:101]: This almost cover every thing... We don't need to have such filtering.

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacityManager.java [hunk 5]
```diff
@@ -0,0 +1,119 @@
...
+import org.apache.helix.model.Resource;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+
+/**
+ * Manager class responsible for abstracting the management operations on the {@link WagedInstanceCapacity}
+ * cache such as rebuild and update operations on various scenarios.
+ */
+public class WagedInstanceCapacityManager {
```
Comment (junkaixue) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacityManager.java:40]: Let's try to minimize class creation. I think we can have the Wagedcapacity in the cache. We don't have to build such manager.

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java [hunk 6]
```diff
@@ -130,28 +136,29 @@ public void processPendingMessages(ResourceControllerDataProvider cache,
...
-      }
-
       // list of partitions in the resource
       Collection<Partition> partitions = resource.getPartitions();
 
+      // calculate merge resource-config one for each resource.
+      ResourceConfig resourceConfig = cache.getResourceConfig(resName);
+      IdealState is = cache.getIdealState(resName);
+      ResourceConfig mergedResourceConfig =
+          ResourceConfig.mergeIdealStateWithResourceConfig(resourceConfig, is);
```
Comment (junkaixue) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java:154]: Why we merge here... Original design is because some config in IS should be stay with Resource Config. But even there is IS change event, I don't think we need to merge any change from IS to resource config. I don't get the merge operation here...

**Review by junkaixue — COMMENTED** [review]
Maybe we need to chat offline... I have few questions about this PR.

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java (hunk 2 above)
Comment (desaikomal) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java:160]: you can check it in next change. Also based on Junkai comment, please evaulate if we even need it?

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java [hunk 7]
```diff
@@ -215,7 +221,7 @@ public synchronized boolean checkAndReduceInstanceCapacity(String instance, Stri
     }
     _allocatedPartitionsMap.computeIfAbsent(instance, k -> new HashMap<>())
         .computeIfAbsent(resName, k -> new HashSet<>()).add(partitionName);
-    LOG.info("Reduced capacity for instance: " + instance + " for resource: " + resName
+    LOG.debug("Reduced capacity for instance: " + instance + " for resource: " + resName
```
Comment (desaikomal) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java:224]: great ...

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacityManager.java (hunk 4 above)
Comment (desaikomal) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacityManager.java:101]: essentially, we need to recompute only for few events, so may be having other way check may be good

**Review by desaikomal — COMMENTED** [review]
Overall looks good, performance number looks good. also please update the change description as events are different.  once you address Junkai's comment, will review it last time. almost there.

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java (hunk 6 above)
Comment (himanshukandwal) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java]: Yes, this merge operation is not needed as partition capacity map is directly present in the ResourceConfig. I have also updated this in `WagedResourceWeightsProvider`. Thanks!

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacityManager.java (hunk 5 above)
Comment (himanshukandwal) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacityManager.java]: Yes, thats correct. I have removed this class now. Thanks Junkai!

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacityManager.java (hunk 4 above)
Comment (himanshukandwal) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacityManager.java]: Yes, changed it to other way, Thanks!

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java (hunk 2 above)
Comment (himanshukandwal) [reply helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/WagedInstanceCapacity.java]: Yes, I have removed this.

File: helix-core/src/main/java/org/apache/helix/controller/stages/CurrentStateComputationStage.java [hunk 8]
```diff
@@ -339,4 +333,61 @@ private void reportResourcePartitionCapacityMetrics(ExecutorService executorServ
...
+      case ControllerChange:
+      case LiveInstanceChange:
+      case CurrentStateChange:
+      case PeriodicalRebalance:
+      case MessageChange:
+        return false;
+      default:
+        return true;
+    }
+  }
```
Comment (junkaixue) [inline helix-core/src/main/java/org/apache/helix/controller/stages/CurrentStateComputationStage.java:391]: Let's skip this one. I think you already listed all the events.

File: helix-core/src/main/java/org/apache/helix/controller/stages/CurrentStateComputationStage.java [hunk 9]
```diff
@@ -339,4 +333,61 @@ private void reportResourcePartitionCapacityMetrics(ExecutorService executorServ
...
+
+  void handleResourceCapacityCalculation(ClusterEvent event, ResourceControllerDataProvider cache,
+      CurrentStateOutput currentStateOutput) {
+    Map<String, Resource> resourceMap = event.getAttribute(AttributeName.RESOURCES.name());
+    if (skipCapacityCalculation(cache, resourceMap, event)) {
+      return;
+    }
+
+    Map<String, Resource> wagedEnabledResourceMap = resourceMap.entrySet()
+        .stream()
```
Comment (junkaixue) [inline helix-core/src/main/java/org/apache/helix/controller/stages/CurrentStateComputationStage.java:345]: We can do parallelStream() here.

Comment (himanshukandwal) [reply helix-core/src/main/java/org/apache/helix/controller/stages/CurrentStateComputationStage.java]: Yes, updated. Thanks Junkai!

File: helix-core/src/main/java/org/apache/helix/controller/stages/CurrentStateComputationStage.java (hunk 8 above)
Comment (himanshukandwal) [reply helix-core/src/main/java/org/apache/helix/controller/stages/CurrentStateComputationStage.java:392]: Thanks Junkai. Discussed offline, I have added a TODO to revisit and handle this logic by event-type and depending on the resource type.

**Review by junkaixue — APPROVED** [review]

**Comment by himanshukandwal** [comment]
This PR is approved by @junkaixue and is ready to be merged.

Final commit message:
WagedInstanceCapacity data-structure is computed every time during a pipeline run and in case of large clusters, this computation takes ~80% of total time. Hence, in this PR we are skipping certain cluster events when this cache should not be rebuild, and improving the overall runtime.
