### PR TITLE
Fix ZkAddress null case for TaskStateModelFactory

### LINKED ISSUE #1626: ZkAddress null case for TaskStateModelFactory
### Describe the bug
If zkAddress is null for the HelixManager passed to TaskStateModelFactory and multizk is not enabled, a NullPointerException will be raised. 

### To Reproduce
Create a HelixManager with null as its zkAddress, then create a TaskStateModelFactory based on said HelixManager. 

### Expected behavior
No NullPointerException.

### PR DESCRIPTION
**Pull request by NealSun96**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fix #1626 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

If zkAddress is null for the HelixManager passed to TaskStateModelFactory and multizk is not enabled, a NullPointerException will be raised. This PR fixes that by adding a null check. 

When https://github.com/apache/helix/pull/1183 was introduced and null checks were added, this section of code was in a feature branch, and was therefore not covered by the PR 1183. 

### Tests

- [x] The following tests are written for this issue:

(List the names of added unit/integration tests)

- The following is the result of the "mvn test" command on the appropriate module:

(If CI test fails due to known issue, please specify the issue and test PR locally. Then copy & paste the result of "mvn test" to here.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/test/java/org/apache/helix/task/TestTaskStateModelFactory.java [hunk 1]
```diff
@@ -86,6 +90,15 @@ public void testConfigAccessorCreationMultiZk() throws Exception {
         .getTargetThreadPoolSize(zkClient, anyParticipantManager.getClusterName(),
             anyParticipantManager.getInstanceName()), TEST_TARGET_TASK_THREAD_POOL_SIZE);
 
+    // Turn off multiZk mode in System config, and remove zkAddress
+    System.setProperty(SystemPropertyKeys.MULTI_ZK_ENABLED, "false");
+    HelixManager participantManager = Mockito.spy(anyParticipantManager);
+    when(participantManager.getMetadataStoreConnectionString()).thenReturn(null);
+    zkClient = TaskStateModelFactory.createZkClient(participantManager);
+    Assert.assertEquals(TaskUtil
```
Comment (narendly) [inline helix-core/src/test/java/org/apache/helix/task/TestTaskStateModelFactory.java:98]: Another good check to add here is `zkClient isinstanceof FederatedZkClient`?

**Review by narendly — APPROVED** [review]
Thanks for fixing. Good job!

**Comment by NealSun96** [comment]
This PR is ready to be merged, approved by @narendly  
Final commit message:
## Fix ZkAddress null case for TaskStateModelFactory ##
If zkAddress is null for the HelixManager passed to TaskStateModelFactory and multizk is not enabled, a NullPointerException will be raised. This PR fixes that by adding a null check.
