### PR TITLE
Fix NPE for RoutingDataCache.refresh

### LINKED ISSUE #1086: NPE for RoutingDataCache.refresh
If sourceDataTypeMap doesn't contain PropertyType.CUSTOMIZEDVIEW then RoutingDataCache.refresh() will throw exception if debug is enabled

### PR DESCRIPTION
**Pull request by alirezazamani**
### Issues
- [x] My PR addresses the following Helix issues and references them in the PR title:
Fixes #1086

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
If sourceDataTypeMap doesn't contain PropertyType.CUSTOMIZEDVIEW
then RoutingDataCache.refresh() will throw exception if debug is enabled.
This PR fixes the issue by adding additional checks.

### Tests
- [x] The following is the result of the "mvn test" command on the appropriate module:
helix-core:
```
[ERROR] Failures: 
[ERROR]   TestJobQueueCleanUp.testJobQueueAutoCleanUp » ThreadTimeout Method org.testng....
[ERROR]   TestTaskThrottling.testTaskThrottle:73 expected:<60> but was:<57>
[ERROR]   TestWorkflowTermination.testWorkflowJobFail:223 » Helix Workflow "testWorkflow...
[INFO] 
[ERROR] Tests run: 1139, Failures: 3, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:26 h
[INFO] Finished at: 2020-06-11T22:01:21-07:00
[INFO] ------------------------------------------------------------------------
```
The failed tests have passed when run individually:
mvn test -Dtest="TestJobQueueCleanUp,TestTaskThrottling,TestWorkflowTermination"
```
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 58.681 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:04 min
[INFO] Finished at: 2020-06-11T22:13:49-07:00
[INFO] ------------------------------------------------------------------------
```
helix-rest:
```
[INFO] Tests run: 162, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 45.296 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 162, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  51.131 s
[INFO] Finished at: 2020-06-11T22:14:57-07:00
[INFO] ------------------------------------------------------------------------
```
### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- [x] My diff has been formatted using helix-style.xml

### CODE REVIEW

**Comment by alirezazamani** [comment]
This PR is ready to be merged, approved by @narendly 

Final commit message:
Fix NPE for RoutingDataCache.refresh

This commit fixes NPE that is thrown in RoutingDataCache.refresh()
method when CUSTOMIZEDVIEW has not being used as an entry of 
sourceDataTypeMap.

File: helix-core/src/main/java/org/apache/helix/spectator/RoutingDataCache.java [hunk 1]
```diff
@@ -142,9 +142,11 @@ public synchronized void refresh(HelixDataAccessor accessor) {
     if (LOG.isDebugEnabled()) {
       LOG.debug("CurrentStates: " + _currentStateCache);
       LOG.debug("TargetExternalViews: " + _targetExternalViewCache.getExternalViewMap());
-      for (String customizedStateType : _sourceDataTypeMap.get(PropertyType.CUSTOMIZEDVIEW)) {
-        LOG.debug("CustomizedViews customizedStateType: " + customizedStateType + " "
-            + _customizedViewCaches.get(customizedStateType).getCustomizedViewMap());
+      if (_sourceDataTypeMap.containsKey(PropertyType.CUSTOMIZEDVIEW)) {
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/spectator/RoutingDataCache.java:145]: getOrDefault(PropertyType.CUSTOMIZEDVIEW, Collections.emptyMap()) would be easier.

Comment (alirezazamani) [reply helix-core/src/main/java/org/apache/helix/spectator/RoutingDataCache.java]: @jiajunwang Addressed. Could you please confirm? Then we can merge it.
