### PR TITLE
Remove possible score-tie between two AssignableNodes

### LINKED ISSUE #772: Unexpected randomness in the WAGED rebalancer partition assignment
One problem we noticed in the test is that the Baseline and Best possible assignment diverge dramatically when a single resource is scaled up or down. One of the most possible root causes is some unexpected randomness in the algorithm so the baseline and best possible assignment are calculated in a slightly different way.
Based on my current investigation, this is caused by a tie evaluation score. For example, when we scale down a resource from 2 replicas to 1 replica, the algorithm finds 2 potential locations (from the previous assignment) with the same evaluation score. It is possible that the baseline calculation chooses placement A and the best possible calculation chooses placement B.

To address this problem, the following code in the ConstraintBasedAlgorithm.java is most related.

>     return candidateNodes.parallelStream().map(node -> new HashMap.SimpleEntry<>(node,
>         getAssignmentNormalizedScore(node, replica, clusterContext)))
>         .max((nodeEntry1, nodeEntry2) -> {
>           int scoreCompareResult = nodeEntry1.getValue().compareTo(nodeEntry2.getValue());
>           if (scoreCompareResult == 0) {
>             // If the evaluation scores of 2 nodes are the same, the algorithm assigns the replica
>             // to the idle node first.
>             int idleScore1 = busyInstances.contains(nodeEntry1.getKey().getInstanceName()) ? 0 : 1;
>             int idleScore2 = busyInstances.contains(nodeEntry2.getKey().getInstanceName()) ? 0 : 1;
>             return idleScore1 - idleScore2;
>           } else {
>             return scoreCompareResult;
>           }
>         }).map(Map.Entry::getKey);

We need to sort the candidates even their scores and isBusy flags are all equal.

### PR DESCRIPTION
**Pull request by NealSun96**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #772 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

When a single resource is scaled up or down, we noticed dramatic divergence between Baseline and Best possible assignments. We concluded initially that it could be caused by some unexpected randomness in the algorithm, and we found out this potential score-tie during node evaluation. This PR fixes a potential situation where two AssignableNodes will receive the same score; the fix makes the algorithm more deterministic. 

After further experiments and discussions, we realized that the divergence might be caused by Baseline recalculation after IdealState changes. See #772. This topic will be explored further in another issue. 

### Tests

- [x] The following tests are written for this issue:

TestConstraintBasedAlgorithm.testCalculateScoreDeterminism

- [x] The following is the result of the "mvn test" command on the appropriate module:

```
Failed tests: 
  TestResourceChangeDetector.testRemoveInstance:284 Â» ZkClient Failed to delete ...
  TestControllerLeadershipChange.testMissingTopStateDurationMonitoring:262 expected:<true> but was:<false>

Tests run: 1088, Failures: 2, Errors: 0, Skipped: 5

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:06 h
[INFO] Finished at: 2020-03-12T13:12:33-07:00
[INFO] ------------------------------------------------------------------------
```

(Rerun)
```
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 36.204 sec - in TestSuite

Results :

Tests run: 14, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  40.600 s
[INFO] Finished at: 2020-03-12T13:30:22-07:00
[INFO] ------------------------------------------------------------------------
```

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- [x] My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/constraints/ConstraintBasedAlgorithm.java [hunk 1]
```diff
@@ -122,9 +121,12 @@ public OptimalAssignment calculate(ClusterModel clusterModel)
...
             // If the evaluation scores of 2 nodes are the same, the algorithm assigns the replica
             // to the idle node first.
-            int idleScore1 = busyInstances.contains(nodeEntry1.getKey().getInstanceName()) ? 0 : 1;
-            int idleScore2 = busyInstances.contains(nodeEntry2.getKey().getInstanceName()) ? 0 : 1;
-            return idleScore1 - idleScore2;
+            String instanceName1 = nodeEntry1.getKey().getInstanceName();
+            String instanceName2 = nodeEntry2.getKey().getInstanceName();
+            int idleScore1 = busyInstances.contains(instanceName1) ? 0 : 1;
+            int idleScore2 = busyInstances.contains(instanceName2) ? 0 : 1;
+            return idleScore1 != idleScore2 ? idleScore1 - idleScore2
```
Comment (jiajunwang) [inline helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/constraints/ConstraintBasedAlgorithm.java]: nit, adding parenthesis to the calculation so it is cleaner and safer.

**Comment by NealSun96** [comment]
This PR is ready to be merged, approved by @jiajunwang 
Final commit message:
## Remove possible score-tie between two AssignableNodes ##
This PR fixes a potential situation where two AssignableNodes will receive the same score; the fix makes the algorithm more deterministic.
