### PR TITLE
Fix for -  Stale message redundant logs #1940

### LINKED ISSUE #1940: Stale message redundant logs
### Describe the bug
Stale messages seem to be logged multiple times for unrelated resources. 

### To Reproduce
Having a stale message in a multi-resource cluster and check controller logs. 

### Expected behavior
The stale message should be logged once for its corresponding resource.

### PR DESCRIPTION
**Pull request by desaikomal**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:
#1940  resolves

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
Do not generate unnecessary stale messages for irrelevant resources for instances.
We generate all stale messages for instance ignoring resource context.
We need to also verify that the partition is valid. The message can be a
simple message where it can be for a particular partition or message can be
in the form of batch, where we can have list of partitions. We need to skip
generating message only if resource and partition matches.

### Tests

- [x] The following tests are written for this issue:

(List the names of added unit/integration tests)

- The following is the result of the "mvn test" command on the appropriate module:
[INFO] Results:
[INFO]
[INFO] Tests run: 1287, Failures: 0, Errors: 0, Skipped: 0
[INFO]

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

It is a bug fix and doesn't change API

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/controller/stages/MessageGenerationPhase.java [hunk 1]
```diff
@@ -53,6 +52,7 @@
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 
+
```
Comment (NealSun96) [inline helix-core/src/main/java/org/apache/helix/controller/stages/MessageGenerationPhase.java:55]: @desaikomal It occurred to me that you might not be using helix-style-intellij.xml to format the code. It's a requirement for Helix PRs, and you can find guidelines here: https://github.com/apache/helix/wiki/Helix-Code-Style-in-Intellij-IDE :)

File: helix-core/src/main/java/org/apache/helix/controller/stages/MessageGenerationPhase.java [hunk 2]
```diff
@@ -200,11 +200,17 @@ private void generateMessage(final Resource resource, final BaseControllerDataPr
...
               .getEndTime(resourceName, partition, instanceName)
-              > DEFAULT_OBSELETE_MSG_PURGE_DELAY) {
-            logAndAddToCleanUp(messagesToCleanUp, staleMessage, instanceName, resourceName,
-                partition, currentState, STALE_MESSAGE);
+              > DEFAULT_OBSELETE_MSG_PURGE_DELAY)
+              && staleMessage.getResourceName().equals(resourceName)) {
+              // staleMessage can be simple or batch mode
+              if ((staleMessage.getPartitionName().equals(partition.getPartitionName()))
+                 || (staleMessage.getBatchMessageMode()
+                     && staleMessage.getPartitionNames().contains(partition.getPartitionName()))) {
```
Comment (NealSun96) [inline helix-core/src/main/java/org/apache/helix/controller/stages/MessageGenerationPhase.java:210]: Could you please combine the two if conditions into one?

**Review by NealSun96 — CHANGES_REQUESTED** [review]
After the two code style issues, this PR should be good to go.

File: helix-core/src/main/java/org/apache/helix/controller/stages/MessageGenerationPhase.java (hunk 1 above)
Comment (desaikomal) [reply helix-core/src/main/java/org/apache/helix/controller/stages/MessageGenerationPhase.java:55]: I am using intellij-code-style but since my tests were failing on local machine while worked on linux-box, i did from that box.

**Review by NealSun96 — APPROVED** [review]

**Comment by desaikomal** [comment]
This PR is ready to be merged, approved by @NealSun96 
Final commit message:

Avoid printing redundant log messages for unrelated partitions and resources.
