### PR TITLE
Don't output the best possible state calculate result if the result is not valid.

### LINKED ISSUE #1358: Resource metric for the rebalance state could be overwritten unexpectedly
### Describe the bug
The rebalance state metric for each resource is the way Helix provides to identify if a resource is being rebalanced normally. We identify an issue that may lead this metric to report wrong information.
In detail, even though the bestpossiblestate calculation fails, the state might remain to be NORMAL.

### To Reproduce
1. Use DelayedRebalance since it may not throw an exception even the rebalance is not possible.
2. Try to rebalance a resource with no available instances.
3. Check the ResourceMonitor attribute RebalanceState, it would be showing BEST_POSSIBLE_CAL_FAILED and then be overwritten to NORMAL by the later pipeline stage.

### Expected behavior
The BEST_POSSIBLE_CAL_FAILED state should remain in the ResourceMonitor until enough instances appear and the resource is normally rebalanced.

### PR DESCRIPTION
**Pull request by jiajunwang**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1358 

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

The invalid result may mislead the following stages in the pipeline and cause problems. For example, this change fixes the issue that resource monitor rebalance state may be inaccurately reported.

### Tests

- [X] The following tests are written for this issue:

Modified the existing test to cover change.

- [X] The following is the result of the "mvn test" command on the appropriate module:

[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestDeleteJobFromJobQueue.testForceDeleteJobFromJobQueue:75 » Helix Failed to ...
[INFO] 
[ERROR] Tests run: 1200, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:14 h
[INFO] Finished at: 2020-09-10T17:51:36-07:00
[INFO] ------------------------------------------------------------------------

Rerun

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.305 s - in org.apache.helix.integration.task.TestDeleteJobFromJobQueue
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.473 s
[INFO] Finished at: 2020-09-10T17:56:04-07:00
[INFO] ------------------------------------------------------------------------

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

File: helix-core/src/main/java/org/apache/helix/controller/stages/BestPossibleStateCalcStage.java [hunk 1]
```diff
@@ -347,36 +347,39 @@ private boolean computeSingleResourceBestPossibleState(ClusterEvent event,
...
-        partitionStateAssignment = mappingCalculator
+        ResourceAssignment partitionStateAssignment = mappingCalculator
             .computeBestPossiblePartitionState(cache, idealState, resource, currentStateOutput);
 
         if (partitionStateAssignment == null) {
           LogUtil.logWarn(logger, _eventId,
-              "PartitionStateAssignment is null, resource: " + resourceName);
+              "The calculated partitionStateAssignment is null, resource: " + resourceName);
           return false;
         }
```
Comment (narendly) [inline helix-core/src/main/java/org/apache/helix/controller/stages/BestPossibleStateCalcStage.java:373]: Question: if `checkBestPossibleStateCalculation(idealState)` is true, will we ever get a null `partitionStateAssignment`?

File: helix-core/src/main/java/org/apache/helix/controller/stages/BestPossibleStateCalcStage.java [hunk 2]
```diff
@@ -347,36 +347,39 @@ private boolean computeSingleResourceBestPossibleState(ClusterEvent event,
...
 
+        // Set the calculated result to the output.
+        output.setPreferenceLists(resourceName, idealState.getPreferenceLists());
```
Comment (narendly) [inline helix-core/src/main/java/org/apache/helix/controller/stages/BestPossibleStateCalcStage.java:376]: Is this to make sure if we ever get a null value for partitionStateAssignment, we don't set anything in the output? 

I wonder if this might cause a behavior change. Before this change, did `output` get populated with some preferenceList value (maybe the one from the previous, last successful pipeline)? After this change, if the `computeBestPossiblePartitionState` returns a `null`, then output will start having nothing, which is a different behavior from before this change?

File: helix-core/src/main/java/org/apache/helix/controller/stages/BestPossibleStateCalcStage.java (hunk 1 above)
Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/controller/stages/BestPossibleStateCalcStage.java:373]: This depends on the mapping calculator implementation. There is no guarantee. So we'd better keep the check.

File: helix-core/src/main/java/org/apache/helix/controller/stages/BestPossibleStateCalcStage.java (hunk 2 above)
Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/controller/stages/BestPossibleStateCalcStage.java:376]: Yeah, this is a behavior change. But the original behavior is the problem here. If any value is set in the output, then the later stage will just use without any doubt. This is very dangerous.

I checked later stages like intermediate state calc, and message generating, they can handle a null output gracefully. But they cannot handle the output with the wrong information gracefully.=

Comment (kaisun2000) [reply helix-core/src/main/java/org/apache/helix/controller/stages/BestPossibleStateCalcStage.java:376]: It seems to me that the original code, `return checkBestPossibleStateCalculation(idealState);` would still return false. Does it feed the wrong info in `output` to later stage? 

The main thing is that the new code fixed the issue of missing metric for invalid idealState.

Comment (jiajunwang) [reply helix-core/src/main/java/org/apache/helix/controller/stages/BestPossibleStateCalcStage.java:376]: The original code returns false while the output is filled with an empty mapping. However, this empty mapping is misleading.

**Review by kaisun2000 — APPROVED** [review]
Appoved as there seems concerns are addressed.

**Comment by jiajunwang** [comment]
This PR has been approved and ready to be merged.
